// report.typ — Scale-out evaluation of the GridTokenX on-chain settlement layer.
// Compile: typst compile report.typ report.pdf
// IEEE-style condensed research report; academic register, no source-line citations.
// Spine: (2) the test case → (3) how it works → (4) how it is verified → (5) future work.

#set page(paper: "a4", margin: (x: 1.6cm, y: 1.55cm), numbering: "1", columns: 2)
#set columns(gutter: 0.9cm)
#set text(size: 9pt)
#set par(justify: true)
#set heading(numbering: none)
#show heading: it => block(above: 0.7em, below: 0.4em, text(size: 9.5pt, it))
#set math.equation(numbering: "(1)", supplement: [Eq.])
#show math.equation: set text(size: 8.5pt)

#let ok = text(fill: rgb("#1f7a53"), weight: "bold")[✓]
#let no = text(fill: rgb("#b23a2a"), weight: "bold")[✗]

// Shared table style — one definition for every data table in the paper.
// head: a table.header(...) value; rows: a flat array of cells.
#let restab(cols, aligns, head, rows, cap) = figure(
  block(width: 100%)[
    #set text(size: 8pt)
    #table(
      columns: cols,
      align: aligns,
      stroke: none,
      inset: (x: 3pt, y: 2.6pt),
      table.hline(stroke: 0.6pt),
      head,
      table.hline(stroke: 0.4pt),
      ..rows,
      table.hline(stroke: 0.6pt),
    )
  ],
  caption: cap,
  supplement: [Table],
)

#place(top + center, scope: "parent", float: true)[
  #text(size: 13.5pt, weight: "bold")[Scale-Out Behaviour of an On-Chain Settlement Layer for
  Peer-to-Peer Energy Trading: An Empirical Study from 160 to 760 Physical Smart Meters]
  #v(0.2em)
  #text(size: 9pt)[GridTokenX: Solana/Anchor Programs — Experimental Results Report]
  #v(0.5em)
  #block(inset: (left: 2.5em, right: 2.5em))[
    #set par(justify: true)
    #text(size: 8.5pt)[
      *Abstract* — A settlement architecture for peer-to-peer (P2P) energy
      trading must sustain continuous device telemetry, guarantee that traded
      energy value is conserved, and remain auditable as the community grows.
      We evaluate GridTokenX — six cooperating Anchor programs on a
      permissioned Solana runtime — by replaying one simulated week of
      *physically-modelled* community electricity through its complete
      lifecycle (telemetry ingest, GRID token mint, continuous-double-auction
      order entry, dual-signature off-chain-match settlement, burn-on-delivery,
      and renewable-energy-certificate issuance) at four community sizes:
      80, 160, 380, and 760 smart meters, each with a 15% rooftop-solar prosumer
      share. Energy data is generated by device-level models — clear-sky
      photovoltaic generation @pvlib, voltage-dependent ZIP loads, and full
      alternating-current power flow @pandapower solved on an 80-bus
      distribution network every fifteen minutes. Every headline figure is
      re-derived from live chain state by an independent on-chain auditor. We
      find that telemetry throughput scales *super-linearly* with fleet size
      (230 to 1,016 readings per second) because hot-path state resides in
      disjoint per-entity program-derived accounts (PDAs); that energy
      conservation — minted equals settled equals burned — closes to the
      atomic watt-hour on uncontended runs; and that settlement is the system
      bottleneck, gated by a single global write-lock at approximately
      0.6 transactions per second. A controlled re-run isolates this
      bottleneck as contention-driven rather than a protocol defect, and
      demonstrates that the on-chain auditor reliably detects the resulting
      state divergence. Total wall-clock compression of a simulated week
      ranges from 993× to 510×.
    ]
  ]
  #v(0.4em)
]

= 1. Introduction

Thailand's draft Power Development Plan (PDP 2026–2050) @moe_factsheet_2026
initiates Direct Power Purchase Agreement frameworks that will, for the first
time, allow distributed rooftop-solar prosumers to contract with one another.
Executing such agreements at P2P scale imposes requirements a general-purpose
blockchain does not meet by default: high-frequency ingest from many devices,
provable dual-authorised and non-replayable settlement, and physical backing
so that a kilowatt-hour token traces to an attested measurement rather than
being minted at will — a shortcoming of early microgrid pilots @ref3.
GridTokenX @ref1 addresses these by routing every hot-path write to a
per-entity PDA, so transactions with disjoint write sets execute in parallel.

A prior study established feasibility on a single 80-meter community. This
report answers the next question — *how the layer behaves as the community
grows* — and is organised around four questions: what is tested (§2, the test
case), how it works (§3), how each result is verified (§4), and what remains
(§5, future work). The contributions are: (i) a physics-grounded, deterministic
dataset generator that drives the on-chain programs from modelled solar, load,
and grid power flow; (ii) an automated per-fleet harness that provisions a fresh
validator, runs the lifecycle, and audits the outcome against chain state; and
(iii) an empirical characterisation of the scaling limits, isolating settlement
contention from a distinct trading-layer effect.

= 2. The Test Case

The test case is a run matrix that varies community size while holding the
generation model, seed, prosumer share, market rules, and horizon fixed, so that
any change in outcome is attributable to scale alone (@tbl-matrix). Three primary
scenarios span a 4.75× range — 160, 380, and 760 meters — each at a 15%
rooftop-solar prosumer share under a 10 kWh per-day sell cap, trading across 16
zone shards over a 7-day horizon of 96 fifteen-minute ticks per day. A fourth
scenario re-runs the 380-meter case on a *quiescent* host to isolate
host-contention effects (§4.3), and a reduced 20-meter, 2-day scenario serves as
a pipeline smoke test that validates the export-to-audit chain before the
primary matrix. Each scenario provisions a fresh validator and is audited
independently, so no run's state can influence another.

#restab(
  (auto, auto, auto, auto, auto, auto),
  (left, right, right, right, right, right),
  table.header[*Scenario*][*Meters*][*Pros.*][*Cons.*][*Readings*][*Ticks*],
  (
    [A · Baseline], [160], [24], [136], [107,520], [672],
    [B · Mid], [380], [57], [323], [255,360], [672],
    [C · Stress], [760], [114], [646], [510,720], [672],
    [B′ · Idle re-run], [380], [57], [323], [255,360], [672],
    [S · Smoke], [20], [3], [17], [3,840], [192],
  ),
  [Run matrix. All scenarios share seed, generation model, 15% prosumer share,
  10 kWh/day cap, and 16 zone shards; only fleet size varies across A–C. B′
  repeats B on an idle host; S is a smoke test.],
) <tbl-matrix>

= 3. How the Test Case Works

*3.1 Physical layer (data generation).* Each meter is an independent device
model. Prosumers carry a 5–15 kW photovoltaic array modelled with clear-sky
irradiance, plane-of-array transposition, cell-temperature derate, and an
inverter model @pvlib; every meter carries a ZIP load with constant-impedance,
constant-current, and constant-power components responding to bus voltage. An
80-bus distribution topology is solved each fifteen-minute tick by
backward/forward-sweep alternating-current power flow @pandapower, yielding bus
voltages, line losses, transformer loading, and system frequency. Generation is
deterministic (fixed seed) and exported to a replay dataset; each case simulates
7 days × 96 ticks = 672 ticks per meter. Timestamps are historical, so the week
replays back-to-back with no inter-epoch waiting.

The resulting energy profile (@tbl-energy) grounds the physical realism of the
test. Per-prosumer generation is $approx 48$ kWh per day ($approx 333$–$347$ kWh
over the week), consistent with a 5–15 kW rooftop array under the seeded weather,
and near-identical across fleets because the profiles are seed-fixed. Per-meter
consumption is $approx 55$–$59$ kWh per day. Crucially the community is
*net-importing*: total consumption exceeds generation roughly seven- to
eight-fold, because only 15% of meters are prosumers — a consumer-heavy
residential feeder with rooftop solar, not a surplus microgrid. The raw
tick-surplus, $S_"raw" = sum_p sum_t max(0, g_(p,t) - c_(p,t))$ summed over
prosumers $p$ and ticks $t$, is the exportable energy before any cap. Two on-chain
filters then route it. First, the anomaly gate rejects implausible readings, so
only the gate-passing fraction is tokenisable. Second, the 10 kWh/day sell cap
binds on roughly three-quarters of prosumer-days (66 of 84, 122 of 168, 298 of
399, and 597 of 798 at 80, 160, 380, and 760 meters): the within-cap portion becomes tradeable
GRID and the cap-withheld remainder is certified as RECs, so
$E_"settle" + E_"REC"$ equals the gate-passing surplus and is bounded above by
metered generation (@eq-conserve). At 160 m, for instance, 5,107 kWh of raw
surplus yields 1,321 kWh traded plus 2,610 kWh certified — the balance being
readings the gate rejected. Every quantity scales near-linearly with fleet size,
confirming that the seed-fixed profiles isolate scale as the sole variable.

#restab(
  (auto, auto, auto, auto, auto, auto),
  (left, right, right, right, right, right),
  table.header[*Fleet*][*Gen.*][*Cons.*][*Raw surplus*][*Traded*][*REC*],
  (
    [80 m], [4,296], [32,053], [3,086], [700], [1,349],
    [160 m], [7,998], [62,594], [5,107], [1,321], [2,610],
    [380 m], [19,475], [158,037], [12,718], [3,178], [6,804],
    [760 m], [39,541], [289,689], [25,905], [6,381], [14,206],
  ),
  [Community energy profile (kWh over the 7-day week). Consumption is $7$–$8 times$
  generation (15% prosumer share); the raw tick-surplus splits into cap-limited
  traded GRID and cap-withheld RECs after the anomaly gate.],
) <tbl-energy>

Concretely, a dataset is three files. `meters.json` fixes each device's
identity; `readings.jsonl` holds one record per meter-tick — energy in
watt-hours per fifteen-minute interval, integer, exactly what the oracle
ingests; `daily.json` is the per-meter daily rollup (kilowatt-hours) that
drives order sizing. @fig-dataset shows the 80-meter export used in §4.7:
meter 2's photovoltaic output is zero before dawn, exceeds load mid-morning
(the exportable tick-surplus), and is *curtailed to exactly match load* once
the day's 5 kWh export cap is reached — visible as $g = c$ — so the daily
rollup's surplus field pins at the cap.

#figure(
  block(width: 100%)[
    #set text(size: 7.5pt)
    #set align(left)
```json
// meters.json — device identity
{"idx": 2, "chain_id": "SIM42-0002",
 "meter_type": "Solar_Prosumer", "solar": true}
{"idx": 0, "chain_id": "SIM42-0000",
 "meter_type": "Grid_Consumer",  "solar": false}

// readings.jsonl — one record per meter-tick
// (g/c = generated/consumed Wh per 15 min)
{"m": 2, "t": 1736139600, "g": 0,   "c": 196} // PV idle
{"m": 2, "t": 1736150400, "g": 901, "c": 396} // surplus
{"m": 2, "t": 1736168400, "g": 209, "c": 209} // curtailed
{"m": 0, "t": 1736168400, "g": 0,   "c": 419} // consumer

// daily.json — per-meter daily rollup (kWh)
{"g": 17.642, "c": 33.472, "s": 5.0} // s pinned at cap
```
  ],
  caption: [Dataset example (80-meter export, seed 42, day 1). Readings are
  integer watt-hours per tick as ingested by the oracle; the sell/export cap
  manifests physically as curtailment ($g = c$) once the day's surplus is
  exhausted, and the daily rollup's surplus $s$ saturates at the cap.],
) <fig-dataset>

*3.2 On-chain lifecycle.* (1) *Telemetry* — meter readings are submitted to the
oracle program in batches of up to ten instructions per transaction across
parallel per-meter chains; readings that trip the on-chain anomaly gate
(produced·100 > 1000·consumed) are sent individually so the rejection is
recorded on-ledger. (2) *Trading* — daily continuous-double-auction sessions
across 16 zone shards: each prosumer offers $min$(daily surplus, 10 kWh cap),
each consumer bids its actual consumption. (3) *Lifecycle* — per prosumer per
day: registry synchronisation and $"settle\_and\_mint"$ (GRID, an SPL
Token-2022 mint), escrow deposit, $"settle\_offchain\_match"$ with two inline
Ed25519 signature-verify instructions (versioned transaction with an
address-lookup table), buyer withdrawal, and burn. At week-end, cap-withheld
surplus is certified as renewable-energy certificates (RECs) via $"issue\_erc"$,
which enforces $"GRID" + "REC" <= "metered generation"$ on chain at a rate of
one REC token per megawatt-hour. Each case runs on a *freshly reset* validator
(programs redeployed, state re-bootstrapped) so fixed-identifier settlement
pollution cannot cross runs. @fig-dataflow traces one quantum of energy from the
physical model through every program it touches to final retirement.

#figure(
  block(width: 100%)[
    #set text(size: 7pt)
    #let node(fill, body) = rect(
      width: 100%, inset: (x: 5pt, y: 3.5pt), radius: 2.5pt,
      stroke: 0.5pt + rgb("#888"), fill: fill, body,
    )
    #let arr = align(center, text(size: 8pt, fill: rgb("#666"))[$arrow.b$])
    #let sim = rgb("#eef3fb")
    #let orc = rgb("#eef7f0")
    #let trd = rgb("#fdf3ea")
    #let inv = rgb("#f6eef8")
    #stack(dir: ttb, spacing: 3.5pt,
      node(sim)[*Simulator* (off-chain) — pandapower AC power-flow / meter chain
        $arrow.r$ `readings.jsonl` (g, c, t per 15-min tick)],
      arr,
      node(orc)[*Oracle* · `submit_meter_reading` — per-meter PDA, anomaly gate
        (produced·100 > 1000·consumed rejected). Oracle-accepted generation is
        the sole source of truth],
      arr,
      node(trd)[*Trading* · `submit_limit_order_sharded` — daily CDA across 16
        zone shards; seller offers $min$(surplus, 10 kWh), buyer bids demand],
      arr,
      node(trd)[*Registry* $arrow.r.long$ *Energy-Token* · `settle_and_mint_tokens`
        (CPI) — mint GRID (Token-2022); registry bounds mint by oracle total.
        #box(text(fill: rgb("#1f7a53"))[$E_"mint"$])],
      arr,
      node(trd)[*Trading* · `deposit_escrow` $arrow.b$ `settle_offchain_match`
        (2×Ed25519 + v0/ALT, per-order nullifier) $arrow.b$ `withdraw_escrow`
        $arrow.r$ *Energy-Token* `retire_energy_tokens`.
        #box(text(fill: rgb("#1f7a53"))[$E_"settle" = E_"burn"$])],
      arr,
      node(inv)[*Governance* $arrow.r.long$ *Registry* · `issue_erc` (CPI
        `mark_erc_claimed`) — cap-withheld surplus $arrow.r$ REC (1 tok/MWh).
        #box(text(fill: rgb("#1f7a53"))[$E_"REC"$])],
      arr,
      node(orc)[*Auditor* (independent) — RPC re-read of chain state re-derives
        every quantity; enforces $E_"mint" = E_"settle" = E_"burn"$ and
        $E_"mint" + E_"REC" <= E_"gen"$],
    )
  ],
  caption: [End-to-end dataflow. Energy metered off-chain is admitted by the
  oracle, tokenised as GRID, traded and burned on delivery, and its cap-withheld
  remainder certified as RECs — each downstream quantity arithmetically bounded
  by oracle-accepted generation, then re-verified by an independent auditor.],
) <fig-dataflow>

*3.3 Pricing and settlement.* Price formation is bounded before any matching:
every limit price must satisfy $p_min <= p <= p_max$ at admission, on-chain
matches cross at the seller's limit $p^* = p_s$, and an off-chain-matched trade
re-enforces the bounds *both counterparties signed*, $p_s <= p^* <= p_b$, so no
party settles worse than the limit it authorised. All monetary arithmetic is
exact-integer with floored division on two fixed-point scales: energy $q$ in
atomic units (kilowatt-hours scaled by $10^9$) and price $p^*$ in $10^6$ minor
units of the baht-pegged settlement currency; the gross value divides their
$10^15$-scaled product by the energy scale $10^9$ — omitting this divisor would
overpay the seller $10^9$-fold. A match of quantity $q$ at price $p^*$ yields the
gross value $V$, a market fee $F_m$ ($phi_m$ basis points; $phi_m = 25$ by
default), a *flat-rate* wheeling charge $C_w$ ($w_r$ per kilowatt-hour), and a
line-loss charge $C_ell$ ($ell$ basis points):

$ V &= floor(frac(q p^*, 10^9)), &quad F_m &= floor(frac(V phi_m, 10^4)), \
  C_w &= floor(frac(q w_r, 10^9)), &quad C_ell &= floor(frac(V ell, 10^4)) $ <eq-settle>

Wheeling is per kilowatt-hour, not a fraction of value, since delivery cost does
not scale with the agreed price; $w_r$ and $ell$ come from an on-chain tariff
schedule movable only by the network authorities. The seller takes the residual
under saturating subtraction, and the four transfers exhaust the buyer's outflow
exactly:

$ N_"seller" = (V - F_m - C_w - C_ell)^+, quad
  V = N_"seller" + F_m + C_w + C_ell $ <eq-net>

where $(dot)^+ = max(dot, 0)$. The conservation and compression identities the
system maintains are

$ E_"mint" = E_"settle" = E_"burn", quad E_"mint" + E_"REC" <= E_"gen", quad
  C = (D dot 86400) / T_"wall", $ <eq-conserve>

for a simulated horizon of $D$ days absorbed in $T_"wall"$ seconds. Replay safety
follows from a per-order nullifier recording cumulative fill, so a signed order
may fill partially but never over-fill or replay; certificate retirement burns
REC base units ($10^3$ per kilowatt-hour), preventing double-counting.

= 4. Verifying the Test Case

Verification rests on independence: no reported figure originates from the
program that produced it. After each run a separate auditor re-derives every
quantity — PDA counts, per-meter reading sums, registry settled and claimed
generation, token supplies, and currency conservation — from remote-procedure-call
reads of chain state, accepting the run only on an exact match (@fig-results
summarises the outcomes). All runs used a single-node validator (Solana 3.1.10)
on an Apple M2 host.

#figure(
  image("report-figs.svg", width: 100%),
  caption: [Scale-out results across the four fleets. *(a)* Confirmed telemetry
  throughput (bar = median, whisker = observed range across repeat runs). *(b)*
  Median compute-unit cost per lifecycle operation at 760 m — settlement
  dominates at $approx 106$k CU, about $9 times$ an order. *(c)* Settlement
  revenue: prosumers capture $97.7%$ of gross value, wheeling the $2.3%$
  residual. *(d)* Energy conservation — traded energy (minted = settled = burned)
  and the separately certified RECs, both scaling with fleet size.],
  placement: top,
  scope: "parent",
  supplement: [Fig.],
) <fig-results>

*4.1 Telemetry scales super-linearly above a small-fleet floor.* @tbl-tel
reports confirmed oracle throughput. Across the three larger fleets each
doubling more than doubles throughput: readings land in disjoint per-meter PDAs,
so larger fleets expose more independent transaction chains that amortise the
single gateway fee-payer. The smallest 80-meter fleet sits *below* this trend at
176.8 readings per second — under 160 meters, too few concurrent meter chains
exist to saturate the fee-payer, so throughput is chain-starved rather than
oracle-bound (the 80-meter run also shared its host, unlike the idle larger-fleet
runs). Delivery loss is zero at every scale; all rejections are the anomaly gate
operating correctly (fee-paid, on-ledger), and the 380-meter split reproduced
bit-identically across runs. The per-reading compute cost stays scale-invariant
at approximately 13–15 thousand compute units (CU) — 15.0k at 80 meters, squarely
in range.

#restab(
  (auto, auto, auto, auto, auto),
  (left, right, right, right, right),
  table.header[*Fleet*][*Confirmed*][*Rejected*][*Read/s*][*Tx/s*],
  (
    [80 m / 12 p], [53,267], [493], [176.8], [17.9],
    [160 m / 24 p], [106,931], [589], [230.1], [23.3],
    [380 m / 57 p], [254,007], [1,353], [722.9], [73.3],
    [760 m / 114 p], [508,152], [2,568], [1,015.8], [102.9],
  ),
  [Telemetry throughput. Zero delivery loss at all scales; 380 m from the idle
  re-run (§4.3).],
) <tbl-tel>

*4.2 Energy conservation closes exactly.* @tbl-cons shows the token accounting.
On uncontended runs the identity $E_"mint" = E_"settle" = E_"burn"$ (@eq-conserve)
holds to the atomic watt-hour: every minted GRID token settles against a real
Ed25519-signed counterparty match and is burned on delivery, with the
cap-withheld remainder certified as RECs. Settlement compute cost is
approximately 106 thousand CU per match — an order of magnitude above the
approximately 11 thousand CU of an order — reflecting the two inline signature
verifications.

#restab(
  (auto, auto, auto, auto, auto, auto),
  (left, right, right, right, right, center),
  table.header[*Fleet*][*Mint*][*Settle*][*Burn*][*REC*][*Audit*],
  (
    [80 m], [699.8], [699.8], [699.8], [1,349.0], [14/14],
    [160 m], [1,321.5], [1,321.5], [1,321.5], [2,610.2], [14/14],
    [380 m], [3,178.3], [3,178.3], [3,178.3], [6,804.2], [12/14],
    [760 m], [6,381.2], [6,381.2], [6,381.2], [14,205.7], [13/14],
  ),
  [Energy conservation (kWh), idle runs. Audit shortfalls at 380 m and 760 m are
  trading-layer order drops (§4.4), not settlement — the energy identity itself
  closes in every clean run.],
) <tbl-cons>

*4.3 Settlement is the bottleneck, and it is contention-driven.* The 380-meter
case first ran under host contention and broke conservation: 57 settlement
transactions reached the confirm-timeout, stranding 570 kWh of minted GRID as
un-burned supply ($E_"mint" = 3178.3 != 2608.3 = E_"burn"$). The auditor
flagged the divergence precisely — on-chain GRID supply after burns of
570,323 Wh against 323 Wh expected — from chain reads alone. Re-run on an
idle host, *all 57 failures vanished*: the layer settled 345 of 345 matches
and the registry's settled generation equalled GRID minted to the watt-hour.
@tbl-380 contrasts the two runs. Settlement serialises on a global
$"treasury\_state"$ and fee-collector write-lock (approximately 0.6
transactions per second) irrespective of shard; this lock has no slack under
contention, which is the mechanism behind the timeouts.

#restab(
  (auto, auto, auto),
  (left, right, right),
  table.header[*380 m metric*][*Contended*][*Idle*],
  (
    [Settlements failed], [57], [#ok 0],
    [Lifecycle wall (s)], [2,059], [134],
    [Trading wall (s)], [2,358], [$approx 9$],
    [Telemetry (read/s)], [438.9], [722.9],
    [Conservation], [#no], [#ok],
  ),
  [Contended versus idle host, 380 m. Removing contention eliminates every
  settlement failure; the break was not a protocol defect.],
) <tbl-380>

*4.4 A distinct trading-layer residual.* Removing contention fixed settlement
entirely but exposed a second, smaller and independent limit. Even idle, the
trading layer dropped 5 of 2,609 order submissions (0.2%) — a burst-contention
artifact of the $"zone\_market"$ write-lock that serialises shard submits —
leaving 30 kWh (0.9% of traded energy) of minted GRID unmatched and therefore
unburned. The strict token-supply audit correctly flags this residual
(GRID supply 30,323 Wh against 323 Wh expected). It is a trading-layer, not
settlement-layer, limitation; the 760-meter case shows the same effect at
16 of 5,219 orders (0.3%).

*4.5 Wall-clock and compression.* A simulated week (604,800 s) is absorbed in
minutes: 971× at 80 m (623 s), 993× at 160 m (609 s), 789× at 380 m idle
(767 s), and 510× at 760 m (1,186 s). The 80-meter figure trails the 160-meter
one despite the smaller fleet because its chain-starved telemetry (§4.1) lengthens
the replay phase, not because of settlement. Above that floor, compression falls
as the fixed settlement ceiling comes to dominate lifecycle time, yet the larger
760-meter fleet still completes quickly on an idle host — confirming that the
contended 380-meter figure reflected host load, not fleet size.

*4.6 Prosumer revenue and network charges.* These scaling runs *fix* the
settlement price rather than discover it: every match executes at 4.00
settlement-currency units per kilowatt-hour, within the signed bounds
$[3.90, 4.50]$ the on-chain settlement enforces. Dynamic price discovery through
the continuous double auction is exercised only for order-entry throughput
(§4.1) and is out of scope here. Settled *value* therefore scales linearly with
settled *energy* (@tbl-rev). The buyer's gross outflow is split by @eq-net into
the prosumer's net proceeds and network charges. The test tariff sets a market
fee of 25 basis points, a line-loss rate of 5 basis points, and a flat wheeling
rate of 0.10 per kilowatt-hour; but because charges are floored to integer minor
units and the per-match gross value is small (about 37 units), the fee and loss
round *down to zero* at this granularity, leaving only the per-kilowatt-hour
wheeling charge — larger, and surviving the floor — collected. Prosumers
consequently capture a near-constant $97.6$–$97.7%$ of gross value, with a
$approx 2.3%$ wheeling residual, and per-prosumer revenue is stable ($227$, $215$,
$217$, and $218$ units over the week at 80, 160, 380, and 760 meters; the smallest
fleet's dozen prosumers each settle marginally more energy, hence a slightly
higher figure) — scaling the community neither dilutes nor concentrates individual
returns. Renewable-energy certificates (1.3, 2.6, 6.8, and 14.2 MWh certified) are
a *separate, non-monetised* value stream:
the cap-withheld surplus retained as an environmental claim rather than sold, and
excluded from the revenue figures.

#restab(
  (auto, auto, auto, auto, auto, auto),
  (left, right, right, right, right, right),
  table.header[*Fleet*][*Settled (kWh)*][*Gross*][*Prosumer net*][*Wheeling*][*Capture*],
  (
    [80 m / 12 p], [699.8], [2,794], [2,728], [66], [97.6%],
    [160 m / 24 p], [1,321.5], [5,275], [5,153], [122], [97.7%],
    [380 m / 57 p], [3,178.3], [12,686], [12,388], [298], [97.7%],
    [760 m / 114 p], [6,381.2], [25,476], [24,879], [597], [97.7%],
  ),
  [Settlement revenue by fleet (settlement-currency units). Fixed 4.00/kWh
  execution price; the tariff's 25 bps fee and 5 bps loss floor to zero per
  match, so gross = prosumer net + wheeling. RECs are certified, not sold, and
  excluded.],
) <tbl-rev>

*4.7 Price-model comparison: what discovery is worth after the wheeling
charge.* A separate on-chain experiment quantifies what the *choice of
settlement scheme* is worth to prosumers, evaluating three schemes on each
fleet's tradeable supply — the prosumers' capped surplus (394.9 kWh for the
80-meter week), aggregated into four price tranches so the whole book fits a
single `clear_auction` transaction, with the *same* reduced book driving all
three schemes: (1) a continuous double auction matching each fill at the
resting seller's ask (asks laddered 3.00–3.45); (2) a uniform-price auction clearing
the full volume at the single marginal price 3.45; and (3) the regulated
surplus buy-back rate of 2.20 per kilowatt-hour as baseline. Unlike §4.6, this
experiment applies a realistic peer-to-peer tariff — 25 basis-point fee, 5
basis-point loss, and a flat wheeling rate of *1.15 per kilowatt-hour* —
to the two market schemes only; the buy-back baseline is a utility feed-in
with no third-party delivery, so it bears no wheeling or market fee. Gross,
both market schemes dominate the baseline decisively: +57% (uniform) and +47%
(CDA) over buy-back. *Net of the tariff the ranking inverts around the
wheeling charge* (@tbl-price): the 1.15/kWh wheeling consumes 454.2 units —
a third of gross market revenue — leaving uniform-price clearing only *4%*
above the buy-back and pushing the discriminatory CDA *6% below* it, because
CDA pays each tranche its own (lower) ask rather than the marginal price.
Price discovery survives the network charge only when every seller receives
the clearing price; under this tariff a discriminatory auction is worse for
prosumers than not trading peer-to-peer at all. Every figure is
independently re-verified from chain state: the four `TradeRecord` accounts
(each fill at its seller's ask), the zone market's stored clearing price and
volume delta, and the recomputed baseline — seven checks per case, all exact.

The result is invariant in both community size and horizon (@tbl-price-scale).
Repeating the experiment at 160, 380, and 760 meters and again over 30-day
datasets — sixteen run-and-verify cases in all, 112 checks — reproduces the
per-kilowatt-hour economics exactly: the uniform auction clears at 3.45 (the
marginal tranche ask) at every scale, so its net rate is 2.290 everywhere by
construction, while the discriminatory CDA's volume-weighted rate wobbles only
with each fleet's surplus distribution (2.068–2.087). Because every charge is
per kilowatt-hour or proportional to value, fleet size and horizon scale
*volume*, never the rate — the break-even discovered price
$approx (2.20 + 1.15) slash 0.997 approx 3.36$ per kilowatt-hour separates the
two market schemes at any community size. Three full repetitions of the
four-fleet sweep are bit-identical, the deterministic counterpart of the
seeded telemetry reproducibility in §4.8.

#restab(
  (auto, auto, auto, auto, auto, auto),
  (left, right, right, right, right, right),
  table.header[*Scheme*][*Vol (kWh)*][*Gross*][*Net*][*Net /kWh*][*vs buy-back*],
  (
    [Uniform-price auction], [394.9], [1,362.5], [904.2], [2.290], [+4%],
    [Continuous double auction], [394.9], [1,278.6], [820.6], [2.078], [−6%],
    [Buy-back 2.20 (baseline)], [394.9], [868.8], [868.8], [2.200], [—],
  ),
  [Three settlement schemes on the identical 394.9 kWh order book
  (settlement-currency units). Market schemes pay the peer-to-peer tariff
  (25 bps fee, 5 bps loss, 1.15/kWh wheeling); the regulated feed-in baseline
  is tariff-exempt. Net = gross − fee − loss − wheeling.],
) <tbl-price>

#restab(
  (auto, auto, auto, auto, auto, auto),
  (left, right, right, right, right, right),
  table.header[*Fleet*][*7-d kWh*][*30-d kWh*][*Uniform net/kWh*][*CDA net/kWh*][*Buy-back*],
  (
    [80 m / 12 p], [394.9], [1,671.8], [2.290], [2.078 / 2.076], [2.200],
    [160 m / 24 p], [727.9], [3,114.2], [2.290], [2.087 / 2.084], [2.200],
    [380 m / 57 p], [1,765.6], [7,546.1], [2.290], [2.072 / 2.068], [2.200],
    [760 m / 114 p], [3,464.9], [14,873.4], [2.290], [2.082 / 2.078], [2.200],
  ),
  [Scale and horizon invariance of the three-scheme comparison (CDA shown as
  7-day / 30-day rate). Per-kilowatt-hour economics are identical at every
  fleet size and horizon; only settled volume scales. Each of the sixteen
  cases passes its seven on-chain checks.],
) <tbl-price-scale>

*4.8 Reproducibility.* All runs use commit `1895458` with Solana 3.1.10 and a
fixed generation seed (42); datasets, per-case artifacts, and audit logs are
retained under `test-results/`. Historical timestamps and the fixed seed make
each dataset reproducible, and the telemetry outcome (confirmed versus
anomaly-rejected reading counts) reproduces bit-identically across runs. To
separate signal from host noise, each scenario is executed $N = 3$ times and
throughput is reported as the median with observed range; compute-unit costs are
medians, scale-invariant per operation and robust to load. The full matrix is one
command — `CASES="160:24 380:57 760:114" DAYS=7 bash scripts/run-scale-sweep.sh`
— which per case exports the physics dataset, provisions a fresh validator,
deploys the five programs, runs the lifecycle, and audits against chain state.
The §4.7 price-model comparison is likewise one command
(`scripts/run-price-models-onchain.sh`), with its seven-check verifier
(`scripts/verify-price-models-onchain.ts`) re-run against the *persisted*
ledger after the run, so the checks read state the runner can no longer touch.

*4.9 Deriving each reported quantity.* Every headline number is a closed-form
function of stated inputs, so a reader can reproduce it by hand rather than trust
the harness. For $M$ meters, $D$ days at interval $Delta$ seconds, telemetry rate
$overline(r)$ over wall time $T_"tel"$, settled energy $q$ (kWh) at fixed price
$p^*$ with wheeling rate $w_r$, the mapping is

$ R &= M dot D dot 86400 / Delta, &quad overline(r) &= R_"ok" / T_"tel", \
  V &= sum_i floor(frac(q_i p^*, 10^9)) approx p^* q, &quad C_w &approx w_r q, \
  N_"seller" &= V - F_m - C_w - C_ell, &quad eta &= N_"seller" / V, \
  "REC"_"base" &= 10^3 dot E_"REC"^"kWh", &quad C &= D dot 86400 / T_"wall" $ <eq-verify>

each mapping to exactly one auditor check. *Worked example, 380 m (idle).*
Readings 380 × 7 × 96 = 255,360, matching @tbl-matrix; confirmed
255,360 − 1,353 = 254,007 after the deterministic anomaly count; rate
254,007 ÷ 351.4 = 722.9 per second (@tbl-tel). Revenue: gross 12,686 (from price
$p^* = 4.00$ over $q = 3178.3$ kWh — the per-match floor trims $p^* q = 12713$
by 27); wheeling 298 (from $w_r = 0.10$, floored from 317.8); with fee and loss
floored to zero, seller net 12,686 − 298 = 12,388 and capture 97.7% (@tbl-rev).
Certificate base units $10^3 times 6804.2$ = 6,804,214,000, matching the audited
REC supply. Compression (7 × 86,400) ÷ 766.5 = 789× (§4.5). Each equals its
independently audited on-chain value.

*4.10 Threats to validity.* Three limits bound the claims. (i) *Deployment* —
results are single-host and single-validator; a multi-node permissioned cluster
would shift the fee-payer and lock ceilings, so the throughput figures are a
floor for that topology, not a projection to production. (ii) *Host sensitivity*
— the 380-meter contention episode shows throughput is sensitive to host load;
figures are therefore gathered on a quiescent machine and reported with
repetition (§4.8). (iii) *Feeder sizing* — the physical layer models each meter's
generation and consumption realistically (photovoltaic and ZIP), but the shared
80-bus test feeder is deliberately oversubscribed at the upper fleet sizes (from
about two meters per bus at 160 m to roughly ten at 760 m). Consequently
bus-level quantities are stressed — at 380 m the solved network shows minimum
voltage near 0.72 pu and transformer loading of 192–209% — and are reported
as-is, not as validated distribution operation. This does not affect the
per-meter energy time-series that drives the on-chain lifecycle, but it means the
grid-physics outputs characterise an intentionally undersized feeder.

= 5. Future Work

The measured limits map directly to the next iteration. *Widen the settlement
ceiling.* Settlement's ~0.6-transactions-per-second global write-lock on
$"treasury\_state"$ and the fee collectors is the dominant bottleneck (§4.3);
fee-payer pooling and sharding the collector accounts would let disjoint matches
settle in parallel, as telemetry already does. *Harden order entry.* The sub-1%
$"zone\_market"$ order-drop under burst load (§4.4) calls for submit-retry with
back-pressure so no signed order is silently lost. *Enforce the network-charge
cap.* The settlement model bounds charges by construction, but a 20% cap on the
combined network charge is defined yet not wired into the off-chain-match path;
enabling it would make the bound hold on chain, not only by convention.
*Dynamic price discovery at fleet scale.* The scaling runs fix the execution
price (§4.6); §4.7 evaluates discovered prices on an aggregated tranche book.
Exercising the continuous double auction for settlement per order, at fleet
scale — rather than on the reduced book a single `clear_auction` transaction
admits — is the natural next study, as is sharding the auction book itself.
*Multi-node and compliant feeder.* Repeating the matrix on a multi-node
permissioned cluster would lift the single-fee-payer and single-validator
ceilings, and right-sizing the distribution feeder would bring the grid-physics
outputs within IEEE operating bounds (§4.10). Finally, aggregating sub-unit fees
would recover the fee and loss revenue that per-match flooring currently discards.

= 6. Conclusion

Across a 4.75× range in community size, the GridTokenX settlement layer sustains
super-linearly scaling telemetry, conserves traded energy value to the atomic
watt-hour, and remains fully auditable from chain state. Its dominant scaling
limit is a contention-sensitive global settlement lock, beneath which a
sub-1% trading-layer order-drop resides. Both are localised and addressable, and
neither compromises the conservation guarantee on a quiescent host. The
physics-grounded harness and per-fleet auditor introduced here provide a
repeatable basis for evaluating the next architectural iteration.

#bibliography("report-refs.bib", title: [References], style: "ieee")
