[toolchain]

[features]
resolution = false
skip-lint = false

[programs.localnet]
blockbench = "HPnJW7bUvHuajENb8YjV1GQbQxUYWH9CP6M8BCzg7EjW"
energy_token = "DBZzN5EZmxDapvnKANmJDymbeYoz2oSmQRUhREGacKDp"
governance = "3W6fUDWtT2F6Hq7ys3mvp3aHHVKCLHysBonyGAF2FPPR"
oracle = "3wqSZd23WyNc7C7FnJKiU6PWwTM5GyFBLxpANe5MTj8r"
registry = "Z4dUwVBUYMYbGkRCNzEyZBwK22LRuEyii6Ci1pW6iLf"
tpc_benchmark = "374pa4eZxzF6q1niiRAJojhCKPn2mFhPjnWPbkJ3yEoN"
trading = "yonsbZqm47vgomYFek9a7yJxcgyYTn3f2MLScEA9Wif"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx mocha -r tsx 'tests/**/*.ts' --timeout 1000000"
init-zone-config = "npx tsx scripts/init-zone-config.ts"
