[toolchain]
anchor_version = "0.32.1"

[features]
resolution = false
skip-lint = false

[programs.localnet]
energy_token = "ExZKhghptUk675rjxgHPjJZjczgWWRRwzUTQnqjPTLno"
governance = "DksRNiZsEZ3zN8n8ZWfukFqi3z74e5865oZ8wFk38p4X"
oracle = "Ad5crRxCcvKFAShAMYtRAD9XKak1cwH1FCE6TrpUA9i2"
registry = "DVoD5K5YRuXXF54a3b6r282jRD8RmtVHGfpw55DHFVDe"
trading = "3iFReh5tvdWkLt7eJcvGKsST7wcwZsSHk3z3xCfUwHLw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
init-governance = "npx ts-node scripts/init-governance.ts"
init-poa = "npx ts-node scripts/init-poa.ts"
init-sharding = "npx ts-node scripts/initialize-sharding.ts"
setup-alts = "npx ts-node scripts/setup-alts.ts"
init-shards = "npx tsx scripts/init-shards.ts"
init-registry = "npx tsx scripts/init-registry.ts"
init-market = "npx ts-node scripts/init-market.ts"
init-oracle = "npx ts-node scripts/init-oracle.ts"
init-zone-market = "npx ts-node scripts/init-zone-market.ts"
mint-tokens = "npx ts-node scripts/mint-tokens.ts"
test-registry = "anchor test tests/registry_sharding.ts"
test-oracle = "anchor test tests/oracle.ts"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = false
