[toolchain]
anchor_version = "0.30.1"

[features]
resolution = false
skip-lint = false

[programs.devnet]
blockbench = "9sz5rrCnWTLqPeQVuyJgyQ1hqLGXrT94GLfVVoWUKpxz"
energy_token = "5DJCWKo5cXt3PXRsrpH1xixra4wXWbNzxZ1p4FHqSxvi"
governance = "8bNpJqZoqqUWKu55VWhR8LWS66BX7NPpwgYBAKhBzu2L"
oracle = "EkcPD2YEXhpo1J73UX9EJNnjV2uuFS8KXMVLx9ybqnhU"
registry = "CXXRVpEwyd2ch7eo425mtaBfr2Yi1825Nm6yik2NEWqR"
tpc_benchmark = "Gn99qZgnpwNXsQaBB7zvyycnRJmMGaQ4UaG5PpvBsmEu"
trading = "8S2e2p4ghqMJuzTz5AkAKSka7jqsjgBH7eWDcCHzXPND"

[programs.localnet]
blockbench = "B7Detx5TMRQNzVCgdd9Rp5YnN9cAtC7KeMBrzdZZsd4E"
energy_token = "5yksg9BHH5RFWpSsLHgRKaX8YAGLwBCu4FQKtpY9bS7U"
governance = "4xXr6TM6YP6SiTeBcfBXC5dZep5PMhBCUN8uG4VUmQJk"
oracle = "296LK1ueWCNbDEoiRv1xw547MjcBdr1CaJVFXNf8NpAg"
registry = "E1k1C1oyRye4dmZcBKJvFKeEarqJBbyUVP7t6odVgo1X"
tpc_benchmark = "DN3XToyEqdvLxXchQZufQj5eXZrxE1yfxsDVDPUrXemD"
trading = "2mYzcKsqTEH1LdNszBMJDAo63SRjDUyk2BXMjHiwFZwt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/Developments/gridtokenx-platform-infa/gridtokenx-anchor/scripts/poa-cluster/genesis/faucet-keypair.json"

[scripts]
benchmark-tpcc = "npx ts-node tests/performance/benchmarks/tpc-c-anchor.ts"
init-governance = "npx ts-node scripts/init-governance.ts"
init-tpcc-schema = "npx ts-node scripts/bootstrap.ts"
relay = "npx ts-node scripts/solana-relay.ts"
test-all = "npx tsx scripts/run-all-tests.ts"
test-confidential-bidding = "anchor test tests/confidential_bidding.ts -- --features localnet"
verify-bridge = "npx tsx scripts/verify_bridge.ts"
verify-carbon = "npx tsx scripts/verify_carbon_credits.ts"
verify-dao = "npx ts-node scripts/verify-dao.ts"
verify-p2p = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/verify_p2p_settlement_collection.ts"
verify-premium = "npx tsx scripts/verify_premium_trading.ts"

[test]
startup_wait = 60000
shutdown_wait = 5000
upgradeable = false
