//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use solana_pubkey::{pubkey, Pubkey};


  /// `governance` program ID.
  pub const GOVERNANCE_ID: Pubkey = pubkey!("4DY97YYBt4bxvG7xaSmWy3MhYhmA6HoMajBHVqhySvXe");

