//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshSerialize;
use borsh::BorshDeserialize;

pub const CREATE_SELL_ORDER_DISCRIMINATOR: [u8; 8] = [53, 52, 255, 44, 191, 74, 171, 225];

/// Accounts.
#[derive(Debug)]
pub struct CreateSellOrder {
      
              
          pub market: solana_pubkey::Pubkey,
          
              
          pub order: solana_pubkey::Pubkey,
                /// Optional: ERC certificate for prosumers
/// When provided, validates the seller has certified renewable energy

    
              
          pub erc_certificate: Option<solana_pubkey::Pubkey>,
          
              
          pub authority: solana_pubkey::Pubkey,
          
              
          pub system_program: solana_pubkey::Pubkey,
      }

impl CreateSellOrder {
  pub fn instruction(&self, args: CreateSellOrderInstructionArgs) -> solana_instruction::Instruction {
    self.instruction_with_remaining_accounts(args, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::vec_init_then_push)]
  pub fn instruction_with_remaining_accounts(&self, args: CreateSellOrderInstructionArgs, remaining_accounts: &[solana_instruction::AccountMeta]) -> solana_instruction::Instruction {
    let mut accounts = Vec::with_capacity(5+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new(
            self.market,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.order,
            false
          ));
                                                      if let Some(erc_certificate) = self.erc_certificate {
              accounts.push(solana_instruction::AccountMeta::new_readonly(
                erc_certificate,
                false,
              ));
            } else {
              accounts.push(solana_instruction::AccountMeta::new_readonly(
                crate::TRADING_ID,
                false,
              ));
            }
                                                    accounts.push(solana_instruction::AccountMeta::new(
            self.authority,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.system_program,
            false
          ));
                      accounts.extend_from_slice(remaining_accounts);
    let mut data = CreateSellOrderInstructionData::new().try_to_vec().unwrap();
          let mut args = args.try_to_vec().unwrap();
      data.append(&mut args);
    
    solana_instruction::Instruction {
      program_id: crate::TRADING_ID,
      accounts,
      data,
    }
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct CreateSellOrderInstructionData {
            discriminator: [u8; 8],
                  }

impl CreateSellOrderInstructionData {
  pub fn new() -> Self {
    Self {
                        discriminator: [53, 52, 255, 44, 191, 74, 171, 225],
                                              }
  }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
    borsh::to_vec(self)
  }
  }

impl Default for CreateSellOrderInstructionData {
  fn default() -> Self {
    Self::new()
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct CreateSellOrderInstructionArgs {
                  pub energy_amount: u64,
                pub price_per_kwh: u64,
      }

impl CreateSellOrderInstructionArgs {
  pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
    borsh::to_vec(self)
  }
}


/// Instruction builder for `CreateSellOrder`.
///
/// ### Accounts:
///
                ///   0. `[writable]` market
                ///   1. `[writable]` order
                ///   2. `[optional]` erc_certificate
                      ///   3. `[writable, signer]` authority
                ///   4. `[optional]` system_program (default to `11111111111111111111111111111111`)
#[derive(Clone, Debug, Default)]
pub struct CreateSellOrderBuilder {
            market: Option<solana_pubkey::Pubkey>,
                order: Option<solana_pubkey::Pubkey>,
                erc_certificate: Option<solana_pubkey::Pubkey>,
                authority: Option<solana_pubkey::Pubkey>,
                system_program: Option<solana_pubkey::Pubkey>,
                        energy_amount: Option<u64>,
                price_per_kwh: Option<u64>,
        __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl CreateSellOrderBuilder {
  pub fn new() -> Self {
    Self::default()
  }
            #[inline(always)]
    pub fn market(&mut self, market: solana_pubkey::Pubkey) -> &mut Self {
                        self.market = Some(market);
                    self
    }
            #[inline(always)]
    pub fn order(&mut self, order: solana_pubkey::Pubkey) -> &mut Self {
                        self.order = Some(order);
                    self
    }
            /// `[optional account]`
/// Optional: ERC certificate for prosumers
/// When provided, validates the seller has certified renewable energy
#[inline(always)]
    pub fn erc_certificate(&mut self, erc_certificate: Option<solana_pubkey::Pubkey>) -> &mut Self {
                        self.erc_certificate = erc_certificate;
                    self
    }
            #[inline(always)]
    pub fn authority(&mut self, authority: solana_pubkey::Pubkey) -> &mut Self {
                        self.authority = Some(authority);
                    self
    }
            /// `[optional account, default to '11111111111111111111111111111111']`
#[inline(always)]
    pub fn system_program(&mut self, system_program: solana_pubkey::Pubkey) -> &mut Self {
                        self.system_program = Some(system_program);
                    self
    }
                    #[inline(always)]
      pub fn energy_amount(&mut self, energy_amount: u64) -> &mut Self {
        self.energy_amount = Some(energy_amount);
        self
      }
                #[inline(always)]
      pub fn price_per_kwh(&mut self, price_per_kwh: u64) -> &mut Self {
        self.price_per_kwh = Some(price_per_kwh);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
    self.__remaining_accounts.push(account);
    self
  }
  /// Add additional accounts to the instruction.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[solana_instruction::AccountMeta]) -> &mut Self {
    self.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[allow(clippy::clone_on_copy)]
  pub fn instruction(&self) -> solana_instruction::Instruction {
    let accounts = CreateSellOrder {
                              market: self.market.expect("market is not set"),
                                        order: self.order.expect("order is not set"),
                                        erc_certificate: self.erc_certificate,
                                        authority: self.authority.expect("authority is not set"),
                                        system_program: self.system_program.unwrap_or(solana_pubkey::pubkey!("11111111111111111111111111111111")),
                      };
          let args = CreateSellOrderInstructionArgs {
                                                              energy_amount: self.energy_amount.clone().expect("energy_amount is not set"),
                                                                  price_per_kwh: self.price_per_kwh.clone().expect("price_per_kwh is not set"),
                                    };
    
    accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
  }
}

  /// `create_sell_order` CPI accounts.
  pub struct CreateSellOrderCpiAccounts<'a, 'b> {
          
                    
              pub market: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub order: &'b solana_account_info::AccountInfo<'a>,
                        /// Optional: ERC certificate for prosumers
/// When provided, validates the seller has certified renewable energy

      
                    
              pub erc_certificate: Option<&'b solana_account_info::AccountInfo<'a>>,
                
                    
              pub authority: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub system_program: &'b solana_account_info::AccountInfo<'a>,
            }

/// `create_sell_order` CPI instruction.
pub struct CreateSellOrderCpi<'a, 'b> {
  /// The program to invoke.
  pub __program: &'b solana_account_info::AccountInfo<'a>,
      
              
          pub market: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub order: &'b solana_account_info::AccountInfo<'a>,
                /// Optional: ERC certificate for prosumers
/// When provided, validates the seller has certified renewable energy

    
              
          pub erc_certificate: Option<&'b solana_account_info::AccountInfo<'a>>,
          
              
          pub authority: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub system_program: &'b solana_account_info::AccountInfo<'a>,
            /// The arguments for the instruction.
    pub __args: CreateSellOrderInstructionArgs,
  }

impl<'a, 'b> CreateSellOrderCpi<'a, 'b> {
  pub fn new(
    program: &'b solana_account_info::AccountInfo<'a>,
          accounts: CreateSellOrderCpiAccounts<'a, 'b>,
              args: CreateSellOrderInstructionArgs,
      ) -> Self {
    Self {
      __program: program,
              market: accounts.market,
              order: accounts.order,
              erc_certificate: accounts.erc_certificate,
              authority: accounts.authority,
              system_program: accounts.system_program,
                    __args: args,
          }
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], &[])
  }
  #[inline(always)]
  pub fn invoke_with_remaining_accounts(&self, remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
  }
  #[inline(always)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed_with_remaining_accounts(
    &self,
    signers_seeds: &[&[&[u8]]],
    remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]
  ) -> solana_program_error::ProgramResult {
    let mut accounts = Vec::with_capacity(5+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new(
            *self.market.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.order.key,
            false
          ));
                                          if let Some(erc_certificate) = self.erc_certificate {
            accounts.push(solana_instruction::AccountMeta::new_readonly(
              *erc_certificate.key,
              false,
            ));
          } else {
            accounts.push(solana_instruction::AccountMeta::new_readonly(
              crate::TRADING_ID,
              false,
            ));
          }
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.authority.key,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.system_program.key,
            false
          ));
                      remaining_accounts.iter().for_each(|remaining_account| {
      accounts.push(solana_instruction::AccountMeta {
          pubkey: *remaining_account.0.key,
          is_signer: remaining_account.1,
          is_writable: remaining_account.2,
      })
    });
    let mut data = CreateSellOrderInstructionData::new().try_to_vec().unwrap();
          let mut args = self.__args.try_to_vec().unwrap();
      data.append(&mut args);
    
    let instruction = solana_instruction::Instruction {
      program_id: crate::TRADING_ID,
      accounts,
      data,
    };
    let mut account_infos = Vec::with_capacity(6 + remaining_accounts.len());
    account_infos.push(self.__program.clone());
                  account_infos.push(self.market.clone());
                        account_infos.push(self.order.clone());
                        if let Some(erc_certificate) = self.erc_certificate {
          account_infos.push(erc_certificate.clone());
        }
                        account_infos.push(self.authority.clone());
                        account_infos.push(self.system_program.clone());
              remaining_accounts.iter().for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

    if signers_seeds.is_empty() {
      solana_cpi::invoke(&instruction, &account_infos)
    } else {
      solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
    }
  }
}

/// Instruction builder for `CreateSellOrder` via CPI.
///
/// ### Accounts:
///
                ///   0. `[writable]` market
                ///   1. `[writable]` order
                ///   2. `[optional]` erc_certificate
                      ///   3. `[writable, signer]` authority
          ///   4. `[]` system_program
#[derive(Clone, Debug)]
pub struct CreateSellOrderCpiBuilder<'a, 'b> {
  instruction: Box<CreateSellOrderCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> CreateSellOrderCpiBuilder<'a, 'b> {
  pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
    let instruction = Box::new(CreateSellOrderCpiBuilderInstruction {
      __program: program,
              market: None,
              order: None,
              erc_certificate: None,
              authority: None,
              system_program: None,
                                            energy_amount: None,
                                price_per_kwh: None,
                    __remaining_accounts: Vec::new(),
    });
    Self { instruction }
  }
      #[inline(always)]
    pub fn market(&mut self, market: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.market = Some(market);
                    self
    }
      #[inline(always)]
    pub fn order(&mut self, order: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.order = Some(order);
                    self
    }
      /// `[optional account]`
/// Optional: ERC certificate for prosumers
/// When provided, validates the seller has certified renewable energy
#[inline(always)]
    pub fn erc_certificate(&mut self, erc_certificate: Option<&'b solana_account_info::AccountInfo<'a>>) -> &mut Self {
                        self.instruction.erc_certificate = erc_certificate;
                    self
    }
      #[inline(always)]
    pub fn authority(&mut self, authority: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.authority = Some(authority);
                    self
    }
      #[inline(always)]
    pub fn system_program(&mut self, system_program: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.system_program = Some(system_program);
                    self
    }
                    #[inline(always)]
      pub fn energy_amount(&mut self, energy_amount: u64) -> &mut Self {
        self.instruction.energy_amount = Some(energy_amount);
        self
      }
                #[inline(always)]
      pub fn price_per_kwh(&mut self, price_per_kwh: u64) -> &mut Self {
        self.instruction.price_per_kwh = Some(price_per_kwh);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: &'b solana_account_info::AccountInfo<'a>, is_writable: bool, is_signer: bool) -> &mut Self {
    self.instruction.__remaining_accounts.push((account, is_writable, is_signer));
    self
  }
  /// Add additional accounts to the instruction.
  ///
  /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
  /// and a `bool` indicating whether the account is a signer or not.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> &mut Self {
    self.instruction.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed(&[])
  }
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
          let args = CreateSellOrderInstructionArgs {
                                                              energy_amount: self.instruction.energy_amount.clone().expect("energy_amount is not set"),
                                                                  price_per_kwh: self.instruction.price_per_kwh.clone().expect("price_per_kwh is not set"),
                                    };
        let instruction = CreateSellOrderCpi {
        __program: self.instruction.__program,
                  
          market: self.instruction.market.expect("market is not set"),
                  
          order: self.instruction.order.expect("order is not set"),
                  
          erc_certificate: self.instruction.erc_certificate,
                  
          authority: self.instruction.authority.expect("authority is not set"),
                  
          system_program: self.instruction.system_program.expect("system_program is not set"),
                          __args: args,
            };
    instruction.invoke_signed_with_remaining_accounts(signers_seeds, &self.instruction.__remaining_accounts)
  }
}

#[derive(Clone, Debug)]
struct CreateSellOrderCpiBuilderInstruction<'a, 'b> {
  __program: &'b solana_account_info::AccountInfo<'a>,
            market: Option<&'b solana_account_info::AccountInfo<'a>>,
                order: Option<&'b solana_account_info::AccountInfo<'a>>,
                erc_certificate: Option<&'b solana_account_info::AccountInfo<'a>>,
                authority: Option<&'b solana_account_info::AccountInfo<'a>>,
                system_program: Option<&'b solana_account_info::AccountInfo<'a>>,
                        energy_amount: Option<u64>,
                price_per_kwh: Option<u64>,
        /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
  __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}

