//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshSerialize;
use borsh::BorshDeserialize;

pub const MATCH_ORDERS_DISCRIMINATOR: [u8; 8] = [17, 1, 201, 93, 7, 51, 251, 134];

/// Accounts.
#[derive(Debug)]
pub struct MatchOrders {
      
              
          pub market: solana_pubkey::Pubkey,
          
              
          pub buy_order: solana_pubkey::Pubkey,
          
              
          pub sell_order: solana_pubkey::Pubkey,
          
              
          pub trade_record: solana_pubkey::Pubkey,
          
              
          pub authority: solana_pubkey::Pubkey,
          
              
          pub system_program: solana_pubkey::Pubkey,
      }

impl MatchOrders {
  pub fn instruction(&self, args: MatchOrdersInstructionArgs) -> solana_instruction::Instruction {
    self.instruction_with_remaining_accounts(args, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::vec_init_then_push)]
  pub fn instruction_with_remaining_accounts(&self, args: MatchOrdersInstructionArgs, remaining_accounts: &[solana_instruction::AccountMeta]) -> solana_instruction::Instruction {
    let mut accounts = Vec::with_capacity(6+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new(
            self.market,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.buy_order,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.sell_order,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.trade_record,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.authority,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.system_program,
            false
          ));
                      accounts.extend_from_slice(remaining_accounts);
    let mut data = MatchOrdersInstructionData::new().try_to_vec().unwrap();
          let mut args = args.try_to_vec().unwrap();
      data.append(&mut args);
    
    solana_instruction::Instruction {
      program_id: crate::TRADING_ID,
      accounts,
      data,
    }
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct MatchOrdersInstructionData {
            discriminator: [u8; 8],
            }

impl MatchOrdersInstructionData {
  pub fn new() -> Self {
    Self {
                        discriminator: [17, 1, 201, 93, 7, 51, 251, 134],
                                }
  }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
    borsh::to_vec(self)
  }
  }

impl Default for MatchOrdersInstructionData {
  fn default() -> Self {
    Self::new()
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct MatchOrdersInstructionArgs {
                  pub match_amount: u64,
      }

impl MatchOrdersInstructionArgs {
  pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
    borsh::to_vec(self)
  }
}


/// Instruction builder for `MatchOrders`.
///
/// ### Accounts:
///
                ///   0. `[writable]` market
                ///   1. `[writable]` buy_order
                ///   2. `[writable]` sell_order
                ///   3. `[writable]` trade_record
                      ///   4. `[writable, signer]` authority
                ///   5. `[optional]` system_program (default to `11111111111111111111111111111111`)
#[derive(Clone, Debug, Default)]
pub struct MatchOrdersBuilder {
            market: Option<solana_pubkey::Pubkey>,
                buy_order: Option<solana_pubkey::Pubkey>,
                sell_order: Option<solana_pubkey::Pubkey>,
                trade_record: Option<solana_pubkey::Pubkey>,
                authority: Option<solana_pubkey::Pubkey>,
                system_program: Option<solana_pubkey::Pubkey>,
                        match_amount: Option<u64>,
        __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl MatchOrdersBuilder {
  pub fn new() -> Self {
    Self::default()
  }
            #[inline(always)]
    pub fn market(&mut self, market: solana_pubkey::Pubkey) -> &mut Self {
                        self.market = Some(market);
                    self
    }
            #[inline(always)]
    pub fn buy_order(&mut self, buy_order: solana_pubkey::Pubkey) -> &mut Self {
                        self.buy_order = Some(buy_order);
                    self
    }
            #[inline(always)]
    pub fn sell_order(&mut self, sell_order: solana_pubkey::Pubkey) -> &mut Self {
                        self.sell_order = Some(sell_order);
                    self
    }
            #[inline(always)]
    pub fn trade_record(&mut self, trade_record: solana_pubkey::Pubkey) -> &mut Self {
                        self.trade_record = Some(trade_record);
                    self
    }
            #[inline(always)]
    pub fn authority(&mut self, authority: solana_pubkey::Pubkey) -> &mut Self {
                        self.authority = Some(authority);
                    self
    }
            /// `[optional account, default to '11111111111111111111111111111111']`
#[inline(always)]
    pub fn system_program(&mut self, system_program: solana_pubkey::Pubkey) -> &mut Self {
                        self.system_program = Some(system_program);
                    self
    }
                    #[inline(always)]
      pub fn match_amount(&mut self, match_amount: u64) -> &mut Self {
        self.match_amount = Some(match_amount);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
    self.__remaining_accounts.push(account);
    self
  }
  /// Add additional accounts to the instruction.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[solana_instruction::AccountMeta]) -> &mut Self {
    self.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[allow(clippy::clone_on_copy)]
  pub fn instruction(&self) -> solana_instruction::Instruction {
    let accounts = MatchOrders {
                              market: self.market.expect("market is not set"),
                                        buy_order: self.buy_order.expect("buy_order is not set"),
                                        sell_order: self.sell_order.expect("sell_order is not set"),
                                        trade_record: self.trade_record.expect("trade_record is not set"),
                                        authority: self.authority.expect("authority is not set"),
                                        system_program: self.system_program.unwrap_or(solana_pubkey::pubkey!("11111111111111111111111111111111")),
                      };
          let args = MatchOrdersInstructionArgs {
                                                              match_amount: self.match_amount.clone().expect("match_amount is not set"),
                                    };
    
    accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
  }
}

  /// `match_orders` CPI accounts.
  pub struct MatchOrdersCpiAccounts<'a, 'b> {
          
                    
              pub market: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub buy_order: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub sell_order: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub trade_record: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub authority: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub system_program: &'b solana_account_info::AccountInfo<'a>,
            }

/// `match_orders` CPI instruction.
pub struct MatchOrdersCpi<'a, 'b> {
  /// The program to invoke.
  pub __program: &'b solana_account_info::AccountInfo<'a>,
      
              
          pub market: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub buy_order: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub sell_order: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub trade_record: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub authority: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub system_program: &'b solana_account_info::AccountInfo<'a>,
            /// The arguments for the instruction.
    pub __args: MatchOrdersInstructionArgs,
  }

impl<'a, 'b> MatchOrdersCpi<'a, 'b> {
  pub fn new(
    program: &'b solana_account_info::AccountInfo<'a>,
          accounts: MatchOrdersCpiAccounts<'a, 'b>,
              args: MatchOrdersInstructionArgs,
      ) -> Self {
    Self {
      __program: program,
              market: accounts.market,
              buy_order: accounts.buy_order,
              sell_order: accounts.sell_order,
              trade_record: accounts.trade_record,
              authority: accounts.authority,
              system_program: accounts.system_program,
                    __args: args,
          }
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], &[])
  }
  #[inline(always)]
  pub fn invoke_with_remaining_accounts(&self, remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
  }
  #[inline(always)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed_with_remaining_accounts(
    &self,
    signers_seeds: &[&[&[u8]]],
    remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]
  ) -> solana_program_error::ProgramResult {
    let mut accounts = Vec::with_capacity(6+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new(
            *self.market.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.buy_order.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.sell_order.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.trade_record.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.authority.key,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.system_program.key,
            false
          ));
                      remaining_accounts.iter().for_each(|remaining_account| {
      accounts.push(solana_instruction::AccountMeta {
          pubkey: *remaining_account.0.key,
          is_signer: remaining_account.1,
          is_writable: remaining_account.2,
      })
    });
    let mut data = MatchOrdersInstructionData::new().try_to_vec().unwrap();
          let mut args = self.__args.try_to_vec().unwrap();
      data.append(&mut args);
    
    let instruction = solana_instruction::Instruction {
      program_id: crate::TRADING_ID,
      accounts,
      data,
    };
    let mut account_infos = Vec::with_capacity(7 + remaining_accounts.len());
    account_infos.push(self.__program.clone());
                  account_infos.push(self.market.clone());
                        account_infos.push(self.buy_order.clone());
                        account_infos.push(self.sell_order.clone());
                        account_infos.push(self.trade_record.clone());
                        account_infos.push(self.authority.clone());
                        account_infos.push(self.system_program.clone());
              remaining_accounts.iter().for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

    if signers_seeds.is_empty() {
      solana_cpi::invoke(&instruction, &account_infos)
    } else {
      solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
    }
  }
}

/// Instruction builder for `MatchOrders` via CPI.
///
/// ### Accounts:
///
                ///   0. `[writable]` market
                ///   1. `[writable]` buy_order
                ///   2. `[writable]` sell_order
                ///   3. `[writable]` trade_record
                      ///   4. `[writable, signer]` authority
          ///   5. `[]` system_program
#[derive(Clone, Debug)]
pub struct MatchOrdersCpiBuilder<'a, 'b> {
  instruction: Box<MatchOrdersCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> MatchOrdersCpiBuilder<'a, 'b> {
  pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
    let instruction = Box::new(MatchOrdersCpiBuilderInstruction {
      __program: program,
              market: None,
              buy_order: None,
              sell_order: None,
              trade_record: None,
              authority: None,
              system_program: None,
                                            match_amount: None,
                    __remaining_accounts: Vec::new(),
    });
    Self { instruction }
  }
      #[inline(always)]
    pub fn market(&mut self, market: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.market = Some(market);
                    self
    }
      #[inline(always)]
    pub fn buy_order(&mut self, buy_order: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.buy_order = Some(buy_order);
                    self
    }
      #[inline(always)]
    pub fn sell_order(&mut self, sell_order: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.sell_order = Some(sell_order);
                    self
    }
      #[inline(always)]
    pub fn trade_record(&mut self, trade_record: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.trade_record = Some(trade_record);
                    self
    }
      #[inline(always)]
    pub fn authority(&mut self, authority: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.authority = Some(authority);
                    self
    }
      #[inline(always)]
    pub fn system_program(&mut self, system_program: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.system_program = Some(system_program);
                    self
    }
                    #[inline(always)]
      pub fn match_amount(&mut self, match_amount: u64) -> &mut Self {
        self.instruction.match_amount = Some(match_amount);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: &'b solana_account_info::AccountInfo<'a>, is_writable: bool, is_signer: bool) -> &mut Self {
    self.instruction.__remaining_accounts.push((account, is_writable, is_signer));
    self
  }
  /// Add additional accounts to the instruction.
  ///
  /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
  /// and a `bool` indicating whether the account is a signer or not.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> &mut Self {
    self.instruction.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed(&[])
  }
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
          let args = MatchOrdersInstructionArgs {
                                                              match_amount: self.instruction.match_amount.clone().expect("match_amount is not set"),
                                    };
        let instruction = MatchOrdersCpi {
        __program: self.instruction.__program,
                  
          market: self.instruction.market.expect("market is not set"),
                  
          buy_order: self.instruction.buy_order.expect("buy_order is not set"),
                  
          sell_order: self.instruction.sell_order.expect("sell_order is not set"),
                  
          trade_record: self.instruction.trade_record.expect("trade_record is not set"),
                  
          authority: self.instruction.authority.expect("authority is not set"),
                  
          system_program: self.instruction.system_program.expect("system_program is not set"),
                          __args: args,
            };
    instruction.invoke_signed_with_remaining_accounts(signers_seeds, &self.instruction.__remaining_accounts)
  }
}

#[derive(Clone, Debug)]
struct MatchOrdersCpiBuilderInstruction<'a, 'b> {
  __program: &'b solana_account_info::AccountInfo<'a>,
            market: Option<&'b solana_account_info::AccountInfo<'a>>,
                buy_order: Option<&'b solana_account_info::AccountInfo<'a>>,
                sell_order: Option<&'b solana_account_info::AccountInfo<'a>>,
                trade_record: Option<&'b solana_account_info::AccountInfo<'a>>,
                authority: Option<&'b solana_account_info::AccountInfo<'a>>,
                system_program: Option<&'b solana_account_info::AccountInfo<'a>>,
                        match_amount: Option<u64>,
        /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
  __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}

