//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshSerialize;
use borsh::BorshDeserialize;

pub const UPDATE_MARKET_PARAMS_DISCRIMINATOR: [u8; 8] = [70, 117, 202, 191, 205, 174, 92, 82];

/// Accounts.
#[derive(Debug)]
pub struct UpdateMarketParams {
      
              
          pub market: solana_pubkey::Pubkey,
          
              
          pub authority: solana_pubkey::Pubkey,
      }

impl UpdateMarketParams {
  pub fn instruction(&self, args: UpdateMarketParamsInstructionArgs) -> solana_instruction::Instruction {
    self.instruction_with_remaining_accounts(args, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::vec_init_then_push)]
  pub fn instruction_with_remaining_accounts(&self, args: UpdateMarketParamsInstructionArgs, remaining_accounts: &[solana_instruction::AccountMeta]) -> solana_instruction::Instruction {
    let mut accounts = Vec::with_capacity(2+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new(
            self.market,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.authority,
            true
          ));
                      accounts.extend_from_slice(remaining_accounts);
    let mut data = UpdateMarketParamsInstructionData::new().try_to_vec().unwrap();
          let mut args = args.try_to_vec().unwrap();
      data.append(&mut args);
    
    solana_instruction::Instruction {
      program_id: crate::TRADING_ID,
      accounts,
      data,
    }
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct UpdateMarketParamsInstructionData {
            discriminator: [u8; 8],
                  }

impl UpdateMarketParamsInstructionData {
  pub fn new() -> Self {
    Self {
                        discriminator: [70, 117, 202, 191, 205, 174, 92, 82],
                                              }
  }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
    borsh::to_vec(self)
  }
  }

impl Default for UpdateMarketParamsInstructionData {
  fn default() -> Self {
    Self::new()
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct UpdateMarketParamsInstructionArgs {
                  pub market_fee_bps: u16,
                pub clearing_enabled: bool,
      }

impl UpdateMarketParamsInstructionArgs {
  pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
    borsh::to_vec(self)
  }
}


/// Instruction builder for `UpdateMarketParams`.
///
/// ### Accounts:
///
                ///   0. `[writable]` market
                ///   1. `[signer]` authority
#[derive(Clone, Debug, Default)]
pub struct UpdateMarketParamsBuilder {
            market: Option<solana_pubkey::Pubkey>,
                authority: Option<solana_pubkey::Pubkey>,
                        market_fee_bps: Option<u16>,
                clearing_enabled: Option<bool>,
        __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl UpdateMarketParamsBuilder {
  pub fn new() -> Self {
    Self::default()
  }
            #[inline(always)]
    pub fn market(&mut self, market: solana_pubkey::Pubkey) -> &mut Self {
                        self.market = Some(market);
                    self
    }
            #[inline(always)]
    pub fn authority(&mut self, authority: solana_pubkey::Pubkey) -> &mut Self {
                        self.authority = Some(authority);
                    self
    }
                    #[inline(always)]
      pub fn market_fee_bps(&mut self, market_fee_bps: u16) -> &mut Self {
        self.market_fee_bps = Some(market_fee_bps);
        self
      }
                #[inline(always)]
      pub fn clearing_enabled(&mut self, clearing_enabled: bool) -> &mut Self {
        self.clearing_enabled = Some(clearing_enabled);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
    self.__remaining_accounts.push(account);
    self
  }
  /// Add additional accounts to the instruction.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[solana_instruction::AccountMeta]) -> &mut Self {
    self.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[allow(clippy::clone_on_copy)]
  pub fn instruction(&self) -> solana_instruction::Instruction {
    let accounts = UpdateMarketParams {
                              market: self.market.expect("market is not set"),
                                        authority: self.authority.expect("authority is not set"),
                      };
          let args = UpdateMarketParamsInstructionArgs {
                                                              market_fee_bps: self.market_fee_bps.clone().expect("market_fee_bps is not set"),
                                                                  clearing_enabled: self.clearing_enabled.clone().expect("clearing_enabled is not set"),
                                    };
    
    accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
  }
}

  /// `update_market_params` CPI accounts.
  pub struct UpdateMarketParamsCpiAccounts<'a, 'b> {
          
                    
              pub market: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub authority: &'b solana_account_info::AccountInfo<'a>,
            }

/// `update_market_params` CPI instruction.
pub struct UpdateMarketParamsCpi<'a, 'b> {
  /// The program to invoke.
  pub __program: &'b solana_account_info::AccountInfo<'a>,
      
              
          pub market: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub authority: &'b solana_account_info::AccountInfo<'a>,
            /// The arguments for the instruction.
    pub __args: UpdateMarketParamsInstructionArgs,
  }

impl<'a, 'b> UpdateMarketParamsCpi<'a, 'b> {
  pub fn new(
    program: &'b solana_account_info::AccountInfo<'a>,
          accounts: UpdateMarketParamsCpiAccounts<'a, 'b>,
              args: UpdateMarketParamsInstructionArgs,
      ) -> Self {
    Self {
      __program: program,
              market: accounts.market,
              authority: accounts.authority,
                    __args: args,
          }
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], &[])
  }
  #[inline(always)]
  pub fn invoke_with_remaining_accounts(&self, remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
  }
  #[inline(always)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed_with_remaining_accounts(
    &self,
    signers_seeds: &[&[&[u8]]],
    remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]
  ) -> solana_program_error::ProgramResult {
    let mut accounts = Vec::with_capacity(2+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new(
            *self.market.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.authority.key,
            true
          ));
                      remaining_accounts.iter().for_each(|remaining_account| {
      accounts.push(solana_instruction::AccountMeta {
          pubkey: *remaining_account.0.key,
          is_signer: remaining_account.1,
          is_writable: remaining_account.2,
      })
    });
    let mut data = UpdateMarketParamsInstructionData::new().try_to_vec().unwrap();
          let mut args = self.__args.try_to_vec().unwrap();
      data.append(&mut args);
    
    let instruction = solana_instruction::Instruction {
      program_id: crate::TRADING_ID,
      accounts,
      data,
    };
    let mut account_infos = Vec::with_capacity(3 + remaining_accounts.len());
    account_infos.push(self.__program.clone());
                  account_infos.push(self.market.clone());
                        account_infos.push(self.authority.clone());
              remaining_accounts.iter().for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

    if signers_seeds.is_empty() {
      solana_cpi::invoke(&instruction, &account_infos)
    } else {
      solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
    }
  }
}

/// Instruction builder for `UpdateMarketParams` via CPI.
///
/// ### Accounts:
///
                ///   0. `[writable]` market
                ///   1. `[signer]` authority
#[derive(Clone, Debug)]
pub struct UpdateMarketParamsCpiBuilder<'a, 'b> {
  instruction: Box<UpdateMarketParamsCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> UpdateMarketParamsCpiBuilder<'a, 'b> {
  pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
    let instruction = Box::new(UpdateMarketParamsCpiBuilderInstruction {
      __program: program,
              market: None,
              authority: None,
                                            market_fee_bps: None,
                                clearing_enabled: None,
                    __remaining_accounts: Vec::new(),
    });
    Self { instruction }
  }
      #[inline(always)]
    pub fn market(&mut self, market: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.market = Some(market);
                    self
    }
      #[inline(always)]
    pub fn authority(&mut self, authority: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.authority = Some(authority);
                    self
    }
                    #[inline(always)]
      pub fn market_fee_bps(&mut self, market_fee_bps: u16) -> &mut Self {
        self.instruction.market_fee_bps = Some(market_fee_bps);
        self
      }
                #[inline(always)]
      pub fn clearing_enabled(&mut self, clearing_enabled: bool) -> &mut Self {
        self.instruction.clearing_enabled = Some(clearing_enabled);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: &'b solana_account_info::AccountInfo<'a>, is_writable: bool, is_signer: bool) -> &mut Self {
    self.instruction.__remaining_accounts.push((account, is_writable, is_signer));
    self
  }
  /// Add additional accounts to the instruction.
  ///
  /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
  /// and a `bool` indicating whether the account is a signer or not.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> &mut Self {
    self.instruction.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed(&[])
  }
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
          let args = UpdateMarketParamsInstructionArgs {
                                                              market_fee_bps: self.instruction.market_fee_bps.clone().expect("market_fee_bps is not set"),
                                                                  clearing_enabled: self.instruction.clearing_enabled.clone().expect("clearing_enabled is not set"),
                                    };
        let instruction = UpdateMarketParamsCpi {
        __program: self.instruction.__program,
                  
          market: self.instruction.market.expect("market is not set"),
                  
          authority: self.instruction.authority.expect("authority is not set"),
                          __args: args,
            };
    instruction.invoke_signed_with_remaining_accounts(signers_seeds, &self.instruction.__remaining_accounts)
  }
}

#[derive(Clone, Debug)]
struct UpdateMarketParamsCpiBuilderInstruction<'a, 'b> {
  __program: &'b solana_account_info::AccountInfo<'a>,
            market: Option<&'b solana_account_info::AccountInfo<'a>>,
                authority: Option<&'b solana_account_info::AccountInfo<'a>>,
                        market_fee_bps: Option<u16>,
                clearing_enabled: Option<bool>,
        /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
  __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}

