//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

  pub(crate) mod r#buy_order_created;
  pub(crate) mod r#erc_status;
  pub(crate) mod r#market_initialized;
  pub(crate) mod r#market_params_updated;
  pub(crate) mod r#order_cancelled;
  pub(crate) mod r#order_matched;
  pub(crate) mod r#order_status;
  pub(crate) mod r#order_type;
  pub(crate) mod r#sell_order_created;

  pub use self::r#buy_order_created::*;
  pub use self::r#erc_status::*;
  pub use self::r#market_initialized::*;
  pub use self::r#market_params_updated::*;
  pub use self::r#order_cancelled::*;
  pub use self::r#order_matched::*;
  pub use self::r#order_status::*;
  pub use self::r#order_type::*;
  pub use self::r#sell_order_created::*;

