[fuzz.metrics]
enabled = true


[[fuzz.programs]]
address = "8S2e2p4ghqMJuzTz5AkAKSka7jqsjgBH7eWDcCHzXPND"
program = "../target/deploy/trading.so"

[[fuzz.programs]]
address = "8bNpJqZoqqUWKu55VWhR8LWS66BX7NPpwgYBAKhBzu2L"
program = "../target/deploy/governance.so"
 