/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBooleanDecoder,
  getBooleanEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/kit';
import { TRADING_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const UPDATE_MARKET_PARAMS_DISCRIMINATOR = new Uint8Array([
  70, 117, 202, 191, 205, 174, 92, 82,
]);

export function getUpdateMarketParamsDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    UPDATE_MARKET_PARAMS_DISCRIMINATOR
  );
}

export type UpdateMarketParamsInstruction<
  TProgram extends string = typeof TRADING_PROGRAM_ADDRESS,
  TAccountMarket extends string | AccountMeta<string> = string,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountMarket extends string
        ? WritableAccount<TAccountMarket>
        : TAccountMarket,
      TAccountAuthority extends string
        ? ReadonlySignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      ...TRemainingAccounts,
    ]
  >;

export type UpdateMarketParamsInstructionData = {
  discriminator: ReadonlyUint8Array;
  marketFeeBps: number;
  clearingEnabled: boolean;
};

export type UpdateMarketParamsInstructionDataArgs = {
  marketFeeBps: number;
  clearingEnabled: boolean;
};

export function getUpdateMarketParamsInstructionDataEncoder(): FixedSizeEncoder<UpdateMarketParamsInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['marketFeeBps', getU16Encoder()],
      ['clearingEnabled', getBooleanEncoder()],
    ]),
    (value) => ({ ...value, discriminator: UPDATE_MARKET_PARAMS_DISCRIMINATOR })
  );
}

export function getUpdateMarketParamsInstructionDataDecoder(): FixedSizeDecoder<UpdateMarketParamsInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['marketFeeBps', getU16Decoder()],
    ['clearingEnabled', getBooleanDecoder()],
  ]);
}

export function getUpdateMarketParamsInstructionDataCodec(): FixedSizeCodec<
  UpdateMarketParamsInstructionDataArgs,
  UpdateMarketParamsInstructionData
> {
  return combineCodec(
    getUpdateMarketParamsInstructionDataEncoder(),
    getUpdateMarketParamsInstructionDataDecoder()
  );
}

export type UpdateMarketParamsInput<
  TAccountMarket extends string = string,
  TAccountAuthority extends string = string,
> = {
  market: Address<TAccountMarket>;
  authority: TransactionSigner<TAccountAuthority>;
  marketFeeBps: UpdateMarketParamsInstructionDataArgs['marketFeeBps'];
  clearingEnabled: UpdateMarketParamsInstructionDataArgs['clearingEnabled'];
};

export function getUpdateMarketParamsInstruction<
  TAccountMarket extends string,
  TAccountAuthority extends string,
  TProgramAddress extends Address = typeof TRADING_PROGRAM_ADDRESS,
>(
  input: UpdateMarketParamsInput<TAccountMarket, TAccountAuthority>,
  config?: { programAddress?: TProgramAddress }
): UpdateMarketParamsInstruction<
  TProgramAddress,
  TAccountMarket,
  TAccountAuthority
> {
  // Program address.
  const programAddress = config?.programAddress ?? TRADING_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    market: { value: input.market ?? null, isWritable: true },
    authority: { value: input.authority ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.market),
      getAccountMeta(accounts.authority),
    ],
    data: getUpdateMarketParamsInstructionDataEncoder().encode(
      args as UpdateMarketParamsInstructionDataArgs
    ),
    programAddress,
  } as UpdateMarketParamsInstruction<
    TProgramAddress,
    TAccountMarket,
    TAccountAuthority
  >);
}

export type ParsedUpdateMarketParamsInstruction<
  TProgram extends string = typeof TRADING_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    market: TAccountMetas[0];
    authority: TAccountMetas[1];
  };
  data: UpdateMarketParamsInstructionData;
};

export function parseUpdateMarketParamsInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedUpdateMarketParamsInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: { market: getNextAccount(), authority: getNextAccount() },
    data: getUpdateMarketParamsInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
