/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from '@solana/kit';

export const TRADE_RECORD_DISCRIMINATOR = new Uint8Array([
  150, 248, 182, 169, 229, 100, 24, 37,
]);

export function getTradeRecordDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    TRADE_RECORD_DISCRIMINATOR
  );
}

export type TradeRecord = {
  discriminator: ReadonlyUint8Array;
  sellOrder: Address;
  buyOrder: Address;
  seller: Address;
  buyer: Address;
  amount: bigint;
  pricePerKwh: bigint;
  totalValue: bigint;
  feeAmount: bigint;
  executedAt: bigint;
};

export type TradeRecordArgs = {
  sellOrder: Address;
  buyOrder: Address;
  seller: Address;
  buyer: Address;
  amount: number | bigint;
  pricePerKwh: number | bigint;
  totalValue: number | bigint;
  feeAmount: number | bigint;
  executedAt: number | bigint;
};

/** Gets the encoder for {@link TradeRecordArgs} account data. */
export function getTradeRecordEncoder(): FixedSizeEncoder<TradeRecordArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['sellOrder', getAddressEncoder()],
      ['buyOrder', getAddressEncoder()],
      ['seller', getAddressEncoder()],
      ['buyer', getAddressEncoder()],
      ['amount', getU64Encoder()],
      ['pricePerKwh', getU64Encoder()],
      ['totalValue', getU64Encoder()],
      ['feeAmount', getU64Encoder()],
      ['executedAt', getI64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: TRADE_RECORD_DISCRIMINATOR })
  );
}

/** Gets the decoder for {@link TradeRecord} account data. */
export function getTradeRecordDecoder(): FixedSizeDecoder<TradeRecord> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['sellOrder', getAddressDecoder()],
    ['buyOrder', getAddressDecoder()],
    ['seller', getAddressDecoder()],
    ['buyer', getAddressDecoder()],
    ['amount', getU64Decoder()],
    ['pricePerKwh', getU64Decoder()],
    ['totalValue', getU64Decoder()],
    ['feeAmount', getU64Decoder()],
    ['executedAt', getI64Decoder()],
  ]);
}

/** Gets the codec for {@link TradeRecord} account data. */
export function getTradeRecordCodec(): FixedSizeCodec<
  TradeRecordArgs,
  TradeRecord
> {
  return combineCodec(getTradeRecordEncoder(), getTradeRecordDecoder());
}

export function decodeTradeRecord<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>
): Account<TradeRecord, TAddress>;
export function decodeTradeRecord<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>
): MaybeAccount<TradeRecord, TAddress>;
export function decodeTradeRecord<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>
): Account<TradeRecord, TAddress> | MaybeAccount<TradeRecord, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getTradeRecordDecoder()
  );
}

export async function fetchTradeRecord<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<Account<TradeRecord, TAddress>> {
  const maybeAccount = await fetchMaybeTradeRecord(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeTradeRecord<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<MaybeAccount<TradeRecord, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeTradeRecord(maybeAccount);
}

export async function fetchAllTradeRecord(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<Account<TradeRecord>[]> {
  const maybeAccounts = await fetchAllMaybeTradeRecord(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeTradeRecord(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<MaybeAccount<TradeRecord>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeTradeRecord(maybeAccount));
}

export function getTradeRecordSize(): number {
  return 176;
}
