//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use num_derive::FromPrimitive;
use thiserror::Error;

#[derive(Clone, Debug, Eq, Error, FromPrimitive, PartialEq)]
pub enum GovernanceError {
    /// 6000 - Unauthorized authority
    #[error("Unauthorized authority")]
    UnauthorizedAuthority = 0x1770,
    /// 6001 - System is already paused
    #[error("System is already paused")]
    AlreadyPaused = 0x1771,
    /// 6002 - System is not paused
    #[error("System is not paused")]
    NotPaused = 0x1772,
    /// 6003 - System is currently paused
    #[error("System is currently paused")]
    SystemPaused = 0x1773,
    /// 6004 - System is in maintenance mode
    #[error("System is in maintenance mode")]
    MaintenanceMode = 0x1774,
    /// 6005 - ERC validation is disabled
    #[error("ERC validation is disabled")]
    ErcValidationDisabled = 0x1775,
    /// 6006 - Invalid ERC status
    #[error("Invalid ERC status")]
    InvalidErcStatus = 0x1776,
    /// 6007 - ERC already validated
    #[error("ERC already validated")]
    AlreadyValidated = 0x1777,
    /// 6008 - Energy amount below minimum required
    #[error("Energy amount below minimum required")]
    BelowMinimumEnergy = 0x1778,
    /// 6009 - Energy amount exceeds maximum allowed
    #[error("Energy amount exceeds maximum allowed")]
    ExceedsMaximumEnergy = 0x1779,
    /// 6010 - Certificate ID too long
    #[error("Certificate ID too long")]
    CertificateIdTooLong = 0x177A,
    /// 6011 - Renewable source name too long
    #[error("Renewable source name too long")]
    SourceNameTooLong = 0x177B,
    /// 6012 - ERC certificate has expired
    #[error("ERC certificate has expired")]
    ErcExpired = 0x177C,
    /// 6013 - Invalid minimum energy amount
    #[error("Invalid minimum energy amount")]
    InvalidMinimumEnergy = 0x177D,
    /// 6014 - Invalid maximum energy amount
    #[error("Invalid maximum energy amount")]
    InvalidMaximumEnergy = 0x177E,
    /// 6015 - Invalid validity period
    #[error("Invalid validity period")]
    InvalidValidityPeriod = 0x177F,
    /// 6016 - Contact information too long
    #[error("Contact information too long")]
    ContactInfoTooLong = 0x1780,
    /// 6017 - Invalid oracle confidence score (must be 0-100)
    #[error("Invalid oracle confidence score (must be 0-100)")]
    InvalidOracleConfidence = 0x1781,
    /// 6018 - Oracle validation required but not configured
    #[error("Oracle validation required but not configured")]
    OracleValidationRequired = 0x1782,
    /// 6019 - Certificate transfers not allowed
    #[error("Certificate transfers not allowed")]
    TransfersNotAllowed = 0x1783,
    /// 6020 - Insufficient unclaimed generation for ERC issuance
    #[error("Insufficient unclaimed generation for ERC issuance")]
    InsufficientUnclaimedGeneration = 0x1784,
}

impl From<GovernanceError> for solana_program_error::ProgramError {
    fn from(e: GovernanceError) -> Self {
        solana_program_error::ProgramError::Custom(e as u32)
    }
}

