/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export type ApiGatewayUpdated = {
  authority: Address;
  oldGateway: Address;
  newGateway: Address;
  timestamp: bigint;
};

export type ApiGatewayUpdatedArgs = {
  authority: Address;
  oldGateway: Address;
  newGateway: Address;
  timestamp: number | bigint;
};

export function getApiGatewayUpdatedEncoder(): FixedSizeEncoder<ApiGatewayUpdatedArgs> {
  return getStructEncoder([
    ['authority', getAddressEncoder()],
    ['oldGateway', getAddressEncoder()],
    ['newGateway', getAddressEncoder()],
    ['timestamp', getI64Encoder()],
  ]);
}

export function getApiGatewayUpdatedDecoder(): FixedSizeDecoder<ApiGatewayUpdated> {
  return getStructDecoder([
    ['authority', getAddressDecoder()],
    ['oldGateway', getAddressDecoder()],
    ['newGateway', getAddressDecoder()],
    ['timestamp', getI64Decoder()],
  ]);
}

export function getApiGatewayUpdatedCodec(): FixedSizeCodec<
  ApiGatewayUpdatedArgs,
  ApiGatewayUpdated
> {
  return combineCodec(
    getApiGatewayUpdatedEncoder(),
    getApiGatewayUpdatedDecoder()
  );
}
