/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU64Decoder,
  getU64Encoder,
  getUtf8Decoder,
  getUtf8Encoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';

export type MeterReadingSubmitted = {
  meterId: string;
  energyProduced: bigint;
  energyConsumed: bigint;
  timestamp: bigint;
  submitter: Address;
};

export type MeterReadingSubmittedArgs = {
  meterId: string;
  energyProduced: number | bigint;
  energyConsumed: number | bigint;
  timestamp: number | bigint;
  submitter: Address;
};

export function getMeterReadingSubmittedEncoder(): Encoder<MeterReadingSubmittedArgs> {
  return getStructEncoder([
    ['meterId', addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
    ['energyProduced', getU64Encoder()],
    ['energyConsumed', getU64Encoder()],
    ['timestamp', getI64Encoder()],
    ['submitter', getAddressEncoder()],
  ]);
}

export function getMeterReadingSubmittedDecoder(): Decoder<MeterReadingSubmitted> {
  return getStructDecoder([
    ['meterId', addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
    ['energyProduced', getU64Decoder()],
    ['energyConsumed', getU64Decoder()],
    ['timestamp', getI64Decoder()],
    ['submitter', getAddressDecoder()],
  ]);
}

export function getMeterReadingSubmittedCodec(): Codec<
  MeterReadingSubmittedArgs,
  MeterReadingSubmitted
> {
  return combineCodec(
    getMeterReadingSubmittedEncoder(),
    getMeterReadingSubmittedDecoder()
  );
}
