//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshSerialize;
use borsh::BorshDeserialize;

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct GovernanceStats {
pub total_ercs_issued: u64,
pub total_ercs_validated: u64,
pub total_ercs_revoked: u64,
pub total_energy_certified: u64,
pub erc_validation_enabled: bool,
pub emergency_paused: bool,
pub maintenance_mode: bool,
pub min_energy_amount: u64,
pub max_erc_amount: u64,
pub erc_validity_period: i64,
pub require_oracle_validation: bool,
pub allow_certificate_transfers: bool,
pub delegation_enabled: bool,
pub created_at: i64,
pub last_updated: i64,
pub last_erc_issued_at: Option<i64>,
}


