//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

  pub(crate) mod r#authority_info_updated;
  pub(crate) mod r#emergency_pause_activated;
  pub(crate) mod r#emergency_pause_deactivated;
  pub(crate) mod r#erc_issued;
  pub(crate) mod r#erc_limits_updated;
  pub(crate) mod r#erc_status;
  pub(crate) mod r#erc_validated_for_trading;
  pub(crate) mod r#governance_config_updated;
  pub(crate) mod r#governance_stats;
  pub(crate) mod r#maintenance_mode_updated;
  pub(crate) mod r#po_a_initialized;

  pub use self::r#authority_info_updated::*;
  pub use self::r#emergency_pause_activated::*;
  pub use self::r#emergency_pause_deactivated::*;
  pub use self::r#erc_issued::*;
  pub use self::r#erc_limits_updated::*;
  pub use self::r#erc_status::*;
  pub use self::r#erc_validated_for_trading::*;
  pub use self::r#governance_config_updated::*;
  pub use self::r#governance_stats::*;
  pub use self::r#maintenance_mode_updated::*;
  pub use self::r#po_a_initialized::*;

