//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use solana_pubkey::{pubkey, Pubkey};


  /// `energy_token` program ID.
  pub const ENERGY_TOKEN_ID: Pubkey = pubkey!("94G1r674LmRDmLN2UPjDFD8Eh7zT8JaSaxv9v68GyEur");

