//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use num_derive::FromPrimitive;
use thiserror::Error;

#[derive(Clone, Debug, Eq, Error, FromPrimitive, PartialEq)]
pub enum OracleError {
    /// 6000 - Unauthorized authority
    #[error("Unauthorized authority")]
    UnauthorizedAuthority = 0x1770,
    /// 6001 - Unauthorized API Gateway
    #[error("Unauthorized API Gateway")]
    UnauthorizedGateway = 0x1771,
    /// 6002 - Oracle is inactive
    #[error("Oracle is inactive")]
    OracleInactive = 0x1772,
    /// 6003 - Invalid meter reading
    #[error("Invalid meter reading")]
    InvalidMeterReading = 0x1773,
    /// 6004 - Market clearing in progress
    #[error("Market clearing in progress")]
    MarketClearingInProgress = 0x1774,
}

impl From<OracleError> for solana_program_error::ProgramError {
    fn from(e: OracleError) -> Self {
        solana_program_error::ProgramError::Custom(e as u32)
    }
}

