/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  isProgramError,
  type Address,
  type SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM,
  type SolanaError,
} from '@solana/kit';
import { GOVERNANCE_PROGRAM_ADDRESS } from '../programs';

/** UnauthorizedAuthority: Unauthorized authority */
export const GOVERNANCE_ERROR__UNAUTHORIZED_AUTHORITY = 0x1770; // 6000
/** AlreadyPaused: System is already paused */
export const GOVERNANCE_ERROR__ALREADY_PAUSED = 0x1771; // 6001
/** NotPaused: System is not paused */
export const GOVERNANCE_ERROR__NOT_PAUSED = 0x1772; // 6002
/** SystemPaused: System is currently paused */
export const GOVERNANCE_ERROR__SYSTEM_PAUSED = 0x1773; // 6003
/** MaintenanceMode: System is in maintenance mode */
export const GOVERNANCE_ERROR__MAINTENANCE_MODE = 0x1774; // 6004
/** ErcValidationDisabled: ERC validation is disabled */
export const GOVERNANCE_ERROR__ERC_VALIDATION_DISABLED = 0x1775; // 6005
/** InvalidErcStatus: Invalid ERC status */
export const GOVERNANCE_ERROR__INVALID_ERC_STATUS = 0x1776; // 6006
/** AlreadyValidated: ERC already validated */
export const GOVERNANCE_ERROR__ALREADY_VALIDATED = 0x1777; // 6007
/** BelowMinimumEnergy: Energy amount below minimum required */
export const GOVERNANCE_ERROR__BELOW_MINIMUM_ENERGY = 0x1778; // 6008
/** ExceedsMaximumEnergy: Energy amount exceeds maximum allowed */
export const GOVERNANCE_ERROR__EXCEEDS_MAXIMUM_ENERGY = 0x1779; // 6009
/** CertificateIdTooLong: Certificate ID too long */
export const GOVERNANCE_ERROR__CERTIFICATE_ID_TOO_LONG = 0x177a; // 6010
/** SourceNameTooLong: Renewable source name too long */
export const GOVERNANCE_ERROR__SOURCE_NAME_TOO_LONG = 0x177b; // 6011
/** ErcExpired: ERC certificate has expired */
export const GOVERNANCE_ERROR__ERC_EXPIRED = 0x177c; // 6012
/** InvalidMinimumEnergy: Invalid minimum energy amount */
export const GOVERNANCE_ERROR__INVALID_MINIMUM_ENERGY = 0x177d; // 6013
/** InvalidMaximumEnergy: Invalid maximum energy amount */
export const GOVERNANCE_ERROR__INVALID_MAXIMUM_ENERGY = 0x177e; // 6014
/** InvalidValidityPeriod: Invalid validity period */
export const GOVERNANCE_ERROR__INVALID_VALIDITY_PERIOD = 0x177f; // 6015
/** ContactInfoTooLong: Contact information too long */
export const GOVERNANCE_ERROR__CONTACT_INFO_TOO_LONG = 0x1780; // 6016
/** InvalidOracleConfidence: Invalid oracle confidence score (must be 0-100) */
export const GOVERNANCE_ERROR__INVALID_ORACLE_CONFIDENCE = 0x1781; // 6017
/** OracleValidationRequired: Oracle validation required but not configured */
export const GOVERNANCE_ERROR__ORACLE_VALIDATION_REQUIRED = 0x1782; // 6018
/** TransfersNotAllowed: Certificate transfers not allowed */
export const GOVERNANCE_ERROR__TRANSFERS_NOT_ALLOWED = 0x1783; // 6019
/** InsufficientUnclaimedGeneration: Insufficient unclaimed generation for ERC issuance */
export const GOVERNANCE_ERROR__INSUFFICIENT_UNCLAIMED_GENERATION = 0x1784; // 6020

export type GovernanceError =
  | typeof GOVERNANCE_ERROR__ALREADY_PAUSED
  | typeof GOVERNANCE_ERROR__ALREADY_VALIDATED
  | typeof GOVERNANCE_ERROR__BELOW_MINIMUM_ENERGY
  | typeof GOVERNANCE_ERROR__CERTIFICATE_ID_TOO_LONG
  | typeof GOVERNANCE_ERROR__CONTACT_INFO_TOO_LONG
  | typeof GOVERNANCE_ERROR__ERC_EXPIRED
  | typeof GOVERNANCE_ERROR__ERC_VALIDATION_DISABLED
  | typeof GOVERNANCE_ERROR__EXCEEDS_MAXIMUM_ENERGY
  | typeof GOVERNANCE_ERROR__INSUFFICIENT_UNCLAIMED_GENERATION
  | typeof GOVERNANCE_ERROR__INVALID_ERC_STATUS
  | typeof GOVERNANCE_ERROR__INVALID_MAXIMUM_ENERGY
  | typeof GOVERNANCE_ERROR__INVALID_MINIMUM_ENERGY
  | typeof GOVERNANCE_ERROR__INVALID_ORACLE_CONFIDENCE
  | typeof GOVERNANCE_ERROR__INVALID_VALIDITY_PERIOD
  | typeof GOVERNANCE_ERROR__MAINTENANCE_MODE
  | typeof GOVERNANCE_ERROR__NOT_PAUSED
  | typeof GOVERNANCE_ERROR__ORACLE_VALIDATION_REQUIRED
  | typeof GOVERNANCE_ERROR__SOURCE_NAME_TOO_LONG
  | typeof GOVERNANCE_ERROR__SYSTEM_PAUSED
  | typeof GOVERNANCE_ERROR__TRANSFERS_NOT_ALLOWED
  | typeof GOVERNANCE_ERROR__UNAUTHORIZED_AUTHORITY;

let governanceErrorMessages: Record<GovernanceError, string> | undefined;
if (process.env.NODE_ENV !== 'production') {
  governanceErrorMessages = {
    [GOVERNANCE_ERROR__ALREADY_PAUSED]: `System is already paused`,
    [GOVERNANCE_ERROR__ALREADY_VALIDATED]: `ERC already validated`,
    [GOVERNANCE_ERROR__BELOW_MINIMUM_ENERGY]: `Energy amount below minimum required`,
    [GOVERNANCE_ERROR__CERTIFICATE_ID_TOO_LONG]: `Certificate ID too long`,
    [GOVERNANCE_ERROR__CONTACT_INFO_TOO_LONG]: `Contact information too long`,
    [GOVERNANCE_ERROR__ERC_EXPIRED]: `ERC certificate has expired`,
    [GOVERNANCE_ERROR__ERC_VALIDATION_DISABLED]: `ERC validation is disabled`,
    [GOVERNANCE_ERROR__EXCEEDS_MAXIMUM_ENERGY]: `Energy amount exceeds maximum allowed`,
    [GOVERNANCE_ERROR__INSUFFICIENT_UNCLAIMED_GENERATION]: `Insufficient unclaimed generation for ERC issuance`,
    [GOVERNANCE_ERROR__INVALID_ERC_STATUS]: `Invalid ERC status`,
    [GOVERNANCE_ERROR__INVALID_MAXIMUM_ENERGY]: `Invalid maximum energy amount`,
    [GOVERNANCE_ERROR__INVALID_MINIMUM_ENERGY]: `Invalid minimum energy amount`,
    [GOVERNANCE_ERROR__INVALID_ORACLE_CONFIDENCE]: `Invalid oracle confidence score (must be 0-100)`,
    [GOVERNANCE_ERROR__INVALID_VALIDITY_PERIOD]: `Invalid validity period`,
    [GOVERNANCE_ERROR__MAINTENANCE_MODE]: `System is in maintenance mode`,
    [GOVERNANCE_ERROR__NOT_PAUSED]: `System is not paused`,
    [GOVERNANCE_ERROR__ORACLE_VALIDATION_REQUIRED]: `Oracle validation required but not configured`,
    [GOVERNANCE_ERROR__SOURCE_NAME_TOO_LONG]: `Renewable source name too long`,
    [GOVERNANCE_ERROR__SYSTEM_PAUSED]: `System is currently paused`,
    [GOVERNANCE_ERROR__TRANSFERS_NOT_ALLOWED]: `Certificate transfers not allowed`,
    [GOVERNANCE_ERROR__UNAUTHORIZED_AUTHORITY]: `Unauthorized authority`,
  };
}

export function getGovernanceErrorMessage(code: GovernanceError): string {
  if (process.env.NODE_ENV !== 'production') {
    return (governanceErrorMessages as Record<GovernanceError, string>)[code];
  }

  return 'Error message not available in production bundles.';
}

export function isGovernanceError<TProgramErrorCode extends GovernanceError>(
  error: unknown,
  transactionMessage: {
    instructions: Record<number, { programAddress: Address }>;
  },
  code?: TProgramErrorCode
): error is SolanaError<typeof SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM> &
  Readonly<{ context: Readonly<{ code: TProgramErrorCode }> }> {
  return isProgramError<TProgramErrorCode>(
    error,
    transactionMessage,
    GOVERNANCE_PROGRAM_ADDRESS,
    code
  );
}
