/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/kit';
import { GOVERNANCE_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const UPDATE_ERC_LIMITS_DISCRIMINATOR = new Uint8Array([
  235, 208, 197, 149, 62, 109, 254, 110,
]);

export function getUpdateErcLimitsDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    UPDATE_ERC_LIMITS_DISCRIMINATOR
  );
}

export type UpdateErcLimitsInstruction<
  TProgram extends string = typeof GOVERNANCE_PROGRAM_ADDRESS,
  TAccountPoaConfig extends string | AccountMeta<string> = string,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountPoaConfig extends string
        ? WritableAccount<TAccountPoaConfig>
        : TAccountPoaConfig,
      TAccountAuthority extends string
        ? ReadonlySignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      ...TRemainingAccounts,
    ]
  >;

export type UpdateErcLimitsInstructionData = {
  discriminator: ReadonlyUint8Array;
  minEnergyAmount: bigint;
  maxErcAmount: bigint;
  ercValidityPeriod: bigint;
};

export type UpdateErcLimitsInstructionDataArgs = {
  minEnergyAmount: number | bigint;
  maxErcAmount: number | bigint;
  ercValidityPeriod: number | bigint;
};

export function getUpdateErcLimitsInstructionDataEncoder(): FixedSizeEncoder<UpdateErcLimitsInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['minEnergyAmount', getU64Encoder()],
      ['maxErcAmount', getU64Encoder()],
      ['ercValidityPeriod', getI64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: UPDATE_ERC_LIMITS_DISCRIMINATOR })
  );
}

export function getUpdateErcLimitsInstructionDataDecoder(): FixedSizeDecoder<UpdateErcLimitsInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['minEnergyAmount', getU64Decoder()],
    ['maxErcAmount', getU64Decoder()],
    ['ercValidityPeriod', getI64Decoder()],
  ]);
}

export function getUpdateErcLimitsInstructionDataCodec(): FixedSizeCodec<
  UpdateErcLimitsInstructionDataArgs,
  UpdateErcLimitsInstructionData
> {
  return combineCodec(
    getUpdateErcLimitsInstructionDataEncoder(),
    getUpdateErcLimitsInstructionDataDecoder()
  );
}

export type UpdateErcLimitsAsyncInput<
  TAccountPoaConfig extends string = string,
  TAccountAuthority extends string = string,
> = {
  poaConfig?: Address<TAccountPoaConfig>;
  authority: TransactionSigner<TAccountAuthority>;
  minEnergyAmount: UpdateErcLimitsInstructionDataArgs['minEnergyAmount'];
  maxErcAmount: UpdateErcLimitsInstructionDataArgs['maxErcAmount'];
  ercValidityPeriod: UpdateErcLimitsInstructionDataArgs['ercValidityPeriod'];
};

export async function getUpdateErcLimitsInstructionAsync<
  TAccountPoaConfig extends string,
  TAccountAuthority extends string,
  TProgramAddress extends Address = typeof GOVERNANCE_PROGRAM_ADDRESS,
>(
  input: UpdateErcLimitsAsyncInput<TAccountPoaConfig, TAccountAuthority>,
  config?: { programAddress?: TProgramAddress }
): Promise<
  UpdateErcLimitsInstruction<
    TProgramAddress,
    TAccountPoaConfig,
    TAccountAuthority
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? GOVERNANCE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    poaConfig: { value: input.poaConfig ?? null, isWritable: true },
    authority: { value: input.authority ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.poaConfig.value) {
    accounts.poaConfig.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([112, 111, 97, 95, 99, 111, 110, 102, 105, 103])
        ),
      ],
    });
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.poaConfig),
      getAccountMeta(accounts.authority),
    ],
    data: getUpdateErcLimitsInstructionDataEncoder().encode(
      args as UpdateErcLimitsInstructionDataArgs
    ),
    programAddress,
  } as UpdateErcLimitsInstruction<
    TProgramAddress,
    TAccountPoaConfig,
    TAccountAuthority
  >);
}

export type UpdateErcLimitsInput<
  TAccountPoaConfig extends string = string,
  TAccountAuthority extends string = string,
> = {
  poaConfig: Address<TAccountPoaConfig>;
  authority: TransactionSigner<TAccountAuthority>;
  minEnergyAmount: UpdateErcLimitsInstructionDataArgs['minEnergyAmount'];
  maxErcAmount: UpdateErcLimitsInstructionDataArgs['maxErcAmount'];
  ercValidityPeriod: UpdateErcLimitsInstructionDataArgs['ercValidityPeriod'];
};

export function getUpdateErcLimitsInstruction<
  TAccountPoaConfig extends string,
  TAccountAuthority extends string,
  TProgramAddress extends Address = typeof GOVERNANCE_PROGRAM_ADDRESS,
>(
  input: UpdateErcLimitsInput<TAccountPoaConfig, TAccountAuthority>,
  config?: { programAddress?: TProgramAddress }
): UpdateErcLimitsInstruction<
  TProgramAddress,
  TAccountPoaConfig,
  TAccountAuthority
> {
  // Program address.
  const programAddress = config?.programAddress ?? GOVERNANCE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    poaConfig: { value: input.poaConfig ?? null, isWritable: true },
    authority: { value: input.authority ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.poaConfig),
      getAccountMeta(accounts.authority),
    ],
    data: getUpdateErcLimitsInstructionDataEncoder().encode(
      args as UpdateErcLimitsInstructionDataArgs
    ),
    programAddress,
  } as UpdateErcLimitsInstruction<
    TProgramAddress,
    TAccountPoaConfig,
    TAccountAuthority
  >);
}

export type ParsedUpdateErcLimitsInstruction<
  TProgram extends string = typeof GOVERNANCE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    poaConfig: TAccountMetas[0];
    authority: TAccountMetas[1];
  };
  data: UpdateErcLimitsInstructionData;
};

export function parseUpdateErcLimitsInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedUpdateErcLimitsInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: { poaConfig: getNextAccount(), authority: getNextAccount() },
    data: getUpdateErcLimitsInstructionDataDecoder().decode(instruction.data),
  };
}
