//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use solana_pubkey::{pubkey, Pubkey};


  /// `registry` program ID.
  pub const REGISTRY_ID: Pubkey = pubkey!("2XPQmFYMdXjP7ffoBB3mXeCdboSFg5Yeb6QmTSGbW8a7");

