/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBooleanDecoder,
  getBooleanEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/kit';
import { ORACLE_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const UPDATE_ORACLE_STATUS_DISCRIMINATOR = new Uint8Array([
  17, 18, 199, 125, 53, 122, 91, 63,
]);

export function getUpdateOracleStatusDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    UPDATE_ORACLE_STATUS_DISCRIMINATOR
  );
}

export type UpdateOracleStatusInstruction<
  TProgram extends string = typeof ORACLE_PROGRAM_ADDRESS,
  TAccountOracleData extends string | AccountMeta<string> = string,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountOracleData extends string
        ? WritableAccount<TAccountOracleData>
        : TAccountOracleData,
      TAccountAuthority extends string
        ? ReadonlySignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      ...TRemainingAccounts,
    ]
  >;

export type UpdateOracleStatusInstructionData = {
  discriminator: ReadonlyUint8Array;
  active: boolean;
};

export type UpdateOracleStatusInstructionDataArgs = { active: boolean };

export function getUpdateOracleStatusInstructionDataEncoder(): FixedSizeEncoder<UpdateOracleStatusInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['active', getBooleanEncoder()],
    ]),
    (value) => ({ ...value, discriminator: UPDATE_ORACLE_STATUS_DISCRIMINATOR })
  );
}

export function getUpdateOracleStatusInstructionDataDecoder(): FixedSizeDecoder<UpdateOracleStatusInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['active', getBooleanDecoder()],
  ]);
}

export function getUpdateOracleStatusInstructionDataCodec(): FixedSizeCodec<
  UpdateOracleStatusInstructionDataArgs,
  UpdateOracleStatusInstructionData
> {
  return combineCodec(
    getUpdateOracleStatusInstructionDataEncoder(),
    getUpdateOracleStatusInstructionDataDecoder()
  );
}

export type UpdateOracleStatusInput<
  TAccountOracleData extends string = string,
  TAccountAuthority extends string = string,
> = {
  oracleData: Address<TAccountOracleData>;
  authority: TransactionSigner<TAccountAuthority>;
  active: UpdateOracleStatusInstructionDataArgs['active'];
};

export function getUpdateOracleStatusInstruction<
  TAccountOracleData extends string,
  TAccountAuthority extends string,
  TProgramAddress extends Address = typeof ORACLE_PROGRAM_ADDRESS,
>(
  input: UpdateOracleStatusInput<TAccountOracleData, TAccountAuthority>,
  config?: { programAddress?: TProgramAddress }
): UpdateOracleStatusInstruction<
  TProgramAddress,
  TAccountOracleData,
  TAccountAuthority
> {
  // Program address.
  const programAddress = config?.programAddress ?? ORACLE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    oracleData: { value: input.oracleData ?? null, isWritable: true },
    authority: { value: input.authority ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.oracleData),
      getAccountMeta(accounts.authority),
    ],
    data: getUpdateOracleStatusInstructionDataEncoder().encode(
      args as UpdateOracleStatusInstructionDataArgs
    ),
    programAddress,
  } as UpdateOracleStatusInstruction<
    TProgramAddress,
    TAccountOracleData,
    TAccountAuthority
  >);
}

export type ParsedUpdateOracleStatusInstruction<
  TProgram extends string = typeof ORACLE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    oracleData: TAccountMetas[0];
    authority: TAccountMetas[1];
  };
  data: UpdateOracleStatusInstructionData;
};

export function parseUpdateOracleStatusInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedUpdateOracleStatusInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: { oracleData: getNextAccount(), authority: getNextAccount() },
    data: getUpdateOracleStatusInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
