AWSTemplateFormatVersion: '2010-09-09'
Description: >
  GridTokenX Solana Blockchain - Standalone EC2 Instance
  FOR RESEARCH USE ONLY - Master's Degree Paper Testing
  Instance: r7a.16xlarge (64 vCPU, 512GB RAM, NVMe storage)
  Private network - No public IP
  NOT FOR PRODUCTION USE

Parameters:
  ProjectName:
    Type: String
    Default: gridtokenx
    Description: Project name for resource naming

  Environment:
    Type: String
    Default: research
    AllowedValues: [research, staging, production]
    Description: Deployment environment

  VpcCidr:
    Type: String
    Default: 10.0.0.0/16
    Description: CIDR block for VPC

  InstanceType:
    Type: String
    Default: r7a.16xlarge
    AllowedValues:
      - r7a.16xlarge   # AMD EPYC, 64 vCPU, 512GB RAM
      - r7i.16xlarge   # Intel Sapphire Rapids, 64 vCPU, 512GB RAM  
      - i4i.16xlarge   # Intel, 64 vCPU, 512GB RAM, 4x3.75TB NVMe
    Description: EC2 instance type for Solana validator

  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: EC2 Key Pair for SSH access

  AmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64
    Description: Amazon Linux 2023 AMI

Resources:
  # ============================================
  # VPC and Networking
  # ============================================
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-vpc

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-igw

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  # Public subnet for NAT Gateway
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-public-subnet

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-public-rt

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnetAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable

  # NAT Gateway
  NatGatewayEIP:
    Type: AWS::EC2::EIP
    DependsOn: AttachGateway
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-nat-eip

  NatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatGatewayEIP.AllocationId
      SubnetId: !Ref PublicSubnet
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-nat-gw

  # Private Subnet
  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.10.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-private-subnet

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-private-rt

  PrivateRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGateway

  PrivateSubnetAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet
      RouteTableId: !Ref PrivateRouteTable

  # ============================================
  # Security Group
  # ============================================
  SolanaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${ProjectName}-solana-sg
      GroupDescription: Security group for Solana validator (private)
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref VpcCidr
          Description: SSH from VPC
        - IpProtocol: tcp
          FromPort: 8899
          ToPort: 8899
          CidrIp: !Ref VpcCidr
          Description: Solana RPC
        - IpProtocol: tcp
          FromPort: 8900
          ToPort: 8900
          CidrIp: !Ref VpcCidr
          Description: Solana PubSub
        - IpProtocol: tcp
          FromPort: 9900
          ToPort: 9900
          CidrIp: !Ref VpcCidr
          Description: Solana Faucet
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-solana-sg

  # ============================================
  # IAM Role
  # ============================================
  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ProjectName}-ec2-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub ${ProjectName}-ec2-profile
      Roles:
        - !Ref EC2Role

  # ============================================
  # EC2 Instance
  # ============================================
  SolanaInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref AmiId
      KeyName: !Ref KeyPairName
      IamInstanceProfile: !Ref EC2InstanceProfile
      SubnetId: !Ref PrivateSubnet
      SecurityGroupIds:
        - !Ref SolanaSecurityGroup
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 500
            VolumeType: gp3
            Iops: 16000
            Throughput: 1000
            Encrypted: true
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -ex
          
          # Install dependencies
          dnf install -y nvme-cli xfsprogs curl
          
          # Mount NVMe instance store volumes
          mkdir -p /data/accounts /data/ledger /data/snapshots
          
          NVME_DEVICES=$(nvme list | grep "Instance Storage" | awk '{print $1}' || true)
          MOUNT_INDEX=0
          MOUNT_PATHS=("/data/accounts" "/data/ledger" "/data/snapshots")
          
          for DEVICE in $NVME_DEVICES; do
            if [ $MOUNT_INDEX -lt 3 ]; then
              MOUNT_PATH="${!MOUNT_PATHS[$MOUNT_INDEX]}"
              mkfs.xfs $DEVICE || true
              mount $DEVICE $MOUNT_PATH
              echo "$DEVICE $MOUNT_PATH xfs defaults,nofail 0 2" >> /etc/fstab
              MOUNT_INDEX=$((MOUNT_INDEX + 1))
            fi
          done
          
          # Kernel optimizations for Solana
          cat >> /etc/sysctl.conf << EOF
          vm.max_map_count=1000000
          net.core.rmem_default=134217728
          net.core.rmem_max=134217728
          net.core.wmem_default=134217728
          net.core.wmem_max=134217728
          EOF
          sysctl -p
          
          # Install Solana CLI
          sh -c "$(curl -sSfL https://release.anza.xyz/stable/install)"
          export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
          
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-solana-validator
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

Outputs:
  VPCId:
    Description: VPC ID
    Value: !Ref VPC

  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref SolanaInstance

  PrivateIp:
    Description: Private IP Address
    Value: !GetAtt SolanaInstance.PrivateIp

  SecurityGroupId:
    Description: Security Group ID
    Value: !Ref SolanaSecurityGroup

  SSMConnectCommand:
    Description: Connect via SSM Session Manager
    Value: !Sub aws ssm start-session --target ${SolanaInstance}
