//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshSerialize;
use borsh::BorshDeserialize;

pub const SUBMIT_METER_READING_DISCRIMINATOR: [u8; 8] = [181, 247, 196, 139, 78, 88, 192, 206];

/// Accounts.
#[derive(Debug)]
pub struct SubmitMeterReading {
      
              
          pub oracle_data: solana_pubkey::Pubkey,
          
              
          pub authority: solana_pubkey::Pubkey,
      }

impl SubmitMeterReading {
  pub fn instruction(&self, args: SubmitMeterReadingInstructionArgs) -> solana_instruction::Instruction {
    self.instruction_with_remaining_accounts(args, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::vec_init_then_push)]
  pub fn instruction_with_remaining_accounts(&self, args: SubmitMeterReadingInstructionArgs, remaining_accounts: &[solana_instruction::AccountMeta]) -> solana_instruction::Instruction {
    let mut accounts = Vec::with_capacity(2+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new(
            self.oracle_data,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.authority,
            true
          ));
                      accounts.extend_from_slice(remaining_accounts);
    let mut data = SubmitMeterReadingInstructionData::new().try_to_vec().unwrap();
          let mut args = args.try_to_vec().unwrap();
      data.append(&mut args);
    
    solana_instruction::Instruction {
      program_id: crate::ORACLE_ID,
      accounts,
      data,
    }
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct SubmitMeterReadingInstructionData {
            discriminator: [u8; 8],
                              }

impl SubmitMeterReadingInstructionData {
  pub fn new() -> Self {
    Self {
                        discriminator: [181, 247, 196, 139, 78, 88, 192, 206],
                                                                          }
  }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
    borsh::to_vec(self)
  }
  }

impl Default for SubmitMeterReadingInstructionData {
  fn default() -> Self {
    Self::new()
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct SubmitMeterReadingInstructionArgs {
                  pub meter_id: String,
                pub energy_produced: u64,
                pub energy_consumed: u64,
                pub reading_timestamp: i64,
      }

impl SubmitMeterReadingInstructionArgs {
  pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
    borsh::to_vec(self)
  }
}


/// Instruction builder for `SubmitMeterReading`.
///
/// ### Accounts:
///
                ///   0. `[writable]` oracle_data
                ///   1. `[signer]` authority
#[derive(Clone, Debug, Default)]
pub struct SubmitMeterReadingBuilder {
            oracle_data: Option<solana_pubkey::Pubkey>,
                authority: Option<solana_pubkey::Pubkey>,
                        meter_id: Option<String>,
                energy_produced: Option<u64>,
                energy_consumed: Option<u64>,
                reading_timestamp: Option<i64>,
        __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl SubmitMeterReadingBuilder {
  pub fn new() -> Self {
    Self::default()
  }
            #[inline(always)]
    pub fn oracle_data(&mut self, oracle_data: solana_pubkey::Pubkey) -> &mut Self {
                        self.oracle_data = Some(oracle_data);
                    self
    }
            #[inline(always)]
    pub fn authority(&mut self, authority: solana_pubkey::Pubkey) -> &mut Self {
                        self.authority = Some(authority);
                    self
    }
                    #[inline(always)]
      pub fn meter_id(&mut self, meter_id: String) -> &mut Self {
        self.meter_id = Some(meter_id);
        self
      }
                #[inline(always)]
      pub fn energy_produced(&mut self, energy_produced: u64) -> &mut Self {
        self.energy_produced = Some(energy_produced);
        self
      }
                #[inline(always)]
      pub fn energy_consumed(&mut self, energy_consumed: u64) -> &mut Self {
        self.energy_consumed = Some(energy_consumed);
        self
      }
                #[inline(always)]
      pub fn reading_timestamp(&mut self, reading_timestamp: i64) -> &mut Self {
        self.reading_timestamp = Some(reading_timestamp);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
    self.__remaining_accounts.push(account);
    self
  }
  /// Add additional accounts to the instruction.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[solana_instruction::AccountMeta]) -> &mut Self {
    self.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[allow(clippy::clone_on_copy)]
  pub fn instruction(&self) -> solana_instruction::Instruction {
    let accounts = SubmitMeterReading {
                              oracle_data: self.oracle_data.expect("oracle_data is not set"),
                                        authority: self.authority.expect("authority is not set"),
                      };
          let args = SubmitMeterReadingInstructionArgs {
                                                              meter_id: self.meter_id.clone().expect("meter_id is not set"),
                                                                  energy_produced: self.energy_produced.clone().expect("energy_produced is not set"),
                                                                  energy_consumed: self.energy_consumed.clone().expect("energy_consumed is not set"),
                                                                  reading_timestamp: self.reading_timestamp.clone().expect("reading_timestamp is not set"),
                                    };
    
    accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
  }
}

  /// `submit_meter_reading` CPI accounts.
  pub struct SubmitMeterReadingCpiAccounts<'a, 'b> {
          
                    
              pub oracle_data: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub authority: &'b solana_account_info::AccountInfo<'a>,
            }

/// `submit_meter_reading` CPI instruction.
pub struct SubmitMeterReadingCpi<'a, 'b> {
  /// The program to invoke.
  pub __program: &'b solana_account_info::AccountInfo<'a>,
      
              
          pub oracle_data: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub authority: &'b solana_account_info::AccountInfo<'a>,
            /// The arguments for the instruction.
    pub __args: SubmitMeterReadingInstructionArgs,
  }

impl<'a, 'b> SubmitMeterReadingCpi<'a, 'b> {
  pub fn new(
    program: &'b solana_account_info::AccountInfo<'a>,
          accounts: SubmitMeterReadingCpiAccounts<'a, 'b>,
              args: SubmitMeterReadingInstructionArgs,
      ) -> Self {
    Self {
      __program: program,
              oracle_data: accounts.oracle_data,
              authority: accounts.authority,
                    __args: args,
          }
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], &[])
  }
  #[inline(always)]
  pub fn invoke_with_remaining_accounts(&self, remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
  }
  #[inline(always)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed_with_remaining_accounts(
    &self,
    signers_seeds: &[&[&[u8]]],
    remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]
  ) -> solana_program_error::ProgramResult {
    let mut accounts = Vec::with_capacity(2+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new(
            *self.oracle_data.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.authority.key,
            true
          ));
                      remaining_accounts.iter().for_each(|remaining_account| {
      accounts.push(solana_instruction::AccountMeta {
          pubkey: *remaining_account.0.key,
          is_signer: remaining_account.1,
          is_writable: remaining_account.2,
      })
    });
    let mut data = SubmitMeterReadingInstructionData::new().try_to_vec().unwrap();
          let mut args = self.__args.try_to_vec().unwrap();
      data.append(&mut args);
    
    let instruction = solana_instruction::Instruction {
      program_id: crate::ORACLE_ID,
      accounts,
      data,
    };
    let mut account_infos = Vec::with_capacity(3 + remaining_accounts.len());
    account_infos.push(self.__program.clone());
                  account_infos.push(self.oracle_data.clone());
                        account_infos.push(self.authority.clone());
              remaining_accounts.iter().for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

    if signers_seeds.is_empty() {
      solana_cpi::invoke(&instruction, &account_infos)
    } else {
      solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
    }
  }
}

/// Instruction builder for `SubmitMeterReading` via CPI.
///
/// ### Accounts:
///
                ///   0. `[writable]` oracle_data
                ///   1. `[signer]` authority
#[derive(Clone, Debug)]
pub struct SubmitMeterReadingCpiBuilder<'a, 'b> {
  instruction: Box<SubmitMeterReadingCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> SubmitMeterReadingCpiBuilder<'a, 'b> {
  pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
    let instruction = Box::new(SubmitMeterReadingCpiBuilderInstruction {
      __program: program,
              oracle_data: None,
              authority: None,
                                            meter_id: None,
                                energy_produced: None,
                                energy_consumed: None,
                                reading_timestamp: None,
                    __remaining_accounts: Vec::new(),
    });
    Self { instruction }
  }
      #[inline(always)]
    pub fn oracle_data(&mut self, oracle_data: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.oracle_data = Some(oracle_data);
                    self
    }
      #[inline(always)]
    pub fn authority(&mut self, authority: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.authority = Some(authority);
                    self
    }
                    #[inline(always)]
      pub fn meter_id(&mut self, meter_id: String) -> &mut Self {
        self.instruction.meter_id = Some(meter_id);
        self
      }
                #[inline(always)]
      pub fn energy_produced(&mut self, energy_produced: u64) -> &mut Self {
        self.instruction.energy_produced = Some(energy_produced);
        self
      }
                #[inline(always)]
      pub fn energy_consumed(&mut self, energy_consumed: u64) -> &mut Self {
        self.instruction.energy_consumed = Some(energy_consumed);
        self
      }
                #[inline(always)]
      pub fn reading_timestamp(&mut self, reading_timestamp: i64) -> &mut Self {
        self.instruction.reading_timestamp = Some(reading_timestamp);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: &'b solana_account_info::AccountInfo<'a>, is_writable: bool, is_signer: bool) -> &mut Self {
    self.instruction.__remaining_accounts.push((account, is_writable, is_signer));
    self
  }
  /// Add additional accounts to the instruction.
  ///
  /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
  /// and a `bool` indicating whether the account is a signer or not.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> &mut Self {
    self.instruction.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed(&[])
  }
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
          let args = SubmitMeterReadingInstructionArgs {
                                                              meter_id: self.instruction.meter_id.clone().expect("meter_id is not set"),
                                                                  energy_produced: self.instruction.energy_produced.clone().expect("energy_produced is not set"),
                                                                  energy_consumed: self.instruction.energy_consumed.clone().expect("energy_consumed is not set"),
                                                                  reading_timestamp: self.instruction.reading_timestamp.clone().expect("reading_timestamp is not set"),
                                    };
        let instruction = SubmitMeterReadingCpi {
        __program: self.instruction.__program,
                  
          oracle_data: self.instruction.oracle_data.expect("oracle_data is not set"),
                  
          authority: self.instruction.authority.expect("authority is not set"),
                          __args: args,
            };
    instruction.invoke_signed_with_remaining_accounts(signers_seeds, &self.instruction.__remaining_accounts)
  }
}

#[derive(Clone, Debug)]
struct SubmitMeterReadingCpiBuilderInstruction<'a, 'b> {
  __program: &'b solana_account_info::AccountInfo<'a>,
            oracle_data: Option<&'b solana_account_info::AccountInfo<'a>>,
                authority: Option<&'b solana_account_info::AccountInfo<'a>>,
                        meter_id: Option<String>,
                energy_produced: Option<u64>,
                energy_consumed: Option<u64>,
                reading_timestamp: Option<i64>,
        /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
  __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}

