//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use solana_pubkey::Pubkey;
use borsh::BorshSerialize;
use borsh::BorshDeserialize;

pub const UPDATE_API_GATEWAY_DISCRIMINATOR: [u8; 8] = [66, 69, 252, 242, 127, 168, 42, 112];

/// Accounts.
#[derive(Debug)]
pub struct UpdateApiGateway {
      
              
          pub oracle_data: solana_pubkey::Pubkey,
          
              
          pub authority: solana_pubkey::Pubkey,
      }

impl UpdateApiGateway {
  pub fn instruction(&self, args: UpdateApiGatewayInstructionArgs) -> solana_instruction::Instruction {
    self.instruction_with_remaining_accounts(args, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::vec_init_then_push)]
  pub fn instruction_with_remaining_accounts(&self, args: UpdateApiGatewayInstructionArgs, remaining_accounts: &[solana_instruction::AccountMeta]) -> solana_instruction::Instruction {
    let mut accounts = Vec::with_capacity(2+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new(
            self.oracle_data,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.authority,
            true
          ));
                      accounts.extend_from_slice(remaining_accounts);
    let mut data = UpdateApiGatewayInstructionData::new().try_to_vec().unwrap();
          let mut args = args.try_to_vec().unwrap();
      data.append(&mut args);
    
    solana_instruction::Instruction {
      program_id: crate::ORACLE_ID,
      accounts,
      data,
    }
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct UpdateApiGatewayInstructionData {
            discriminator: [u8; 8],
            }

impl UpdateApiGatewayInstructionData {
  pub fn new() -> Self {
    Self {
                        discriminator: [66, 69, 252, 242, 127, 168, 42, 112],
                                }
  }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
    borsh::to_vec(self)
  }
  }

impl Default for UpdateApiGatewayInstructionData {
  fn default() -> Self {
    Self::new()
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct UpdateApiGatewayInstructionArgs {
                  pub new_api_gateway: Pubkey,
      }

impl UpdateApiGatewayInstructionArgs {
  pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
    borsh::to_vec(self)
  }
}


/// Instruction builder for `UpdateApiGateway`.
///
/// ### Accounts:
///
                ///   0. `[writable]` oracle_data
                ///   1. `[signer]` authority
#[derive(Clone, Debug, Default)]
pub struct UpdateApiGatewayBuilder {
            oracle_data: Option<solana_pubkey::Pubkey>,
                authority: Option<solana_pubkey::Pubkey>,
                        new_api_gateway: Option<Pubkey>,
        __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl UpdateApiGatewayBuilder {
  pub fn new() -> Self {
    Self::default()
  }
            #[inline(always)]
    pub fn oracle_data(&mut self, oracle_data: solana_pubkey::Pubkey) -> &mut Self {
                        self.oracle_data = Some(oracle_data);
                    self
    }
            #[inline(always)]
    pub fn authority(&mut self, authority: solana_pubkey::Pubkey) -> &mut Self {
                        self.authority = Some(authority);
                    self
    }
                    #[inline(always)]
      pub fn new_api_gateway(&mut self, new_api_gateway: Pubkey) -> &mut Self {
        self.new_api_gateway = Some(new_api_gateway);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
    self.__remaining_accounts.push(account);
    self
  }
  /// Add additional accounts to the instruction.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[solana_instruction::AccountMeta]) -> &mut Self {
    self.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[allow(clippy::clone_on_copy)]
  pub fn instruction(&self) -> solana_instruction::Instruction {
    let accounts = UpdateApiGateway {
                              oracle_data: self.oracle_data.expect("oracle_data is not set"),
                                        authority: self.authority.expect("authority is not set"),
                      };
          let args = UpdateApiGatewayInstructionArgs {
                                                              new_api_gateway: self.new_api_gateway.clone().expect("new_api_gateway is not set"),
                                    };
    
    accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
  }
}

  /// `update_api_gateway` CPI accounts.
  pub struct UpdateApiGatewayCpiAccounts<'a, 'b> {
          
                    
              pub oracle_data: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub authority: &'b solana_account_info::AccountInfo<'a>,
            }

/// `update_api_gateway` CPI instruction.
pub struct UpdateApiGatewayCpi<'a, 'b> {
  /// The program to invoke.
  pub __program: &'b solana_account_info::AccountInfo<'a>,
      
              
          pub oracle_data: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub authority: &'b solana_account_info::AccountInfo<'a>,
            /// The arguments for the instruction.
    pub __args: UpdateApiGatewayInstructionArgs,
  }

impl<'a, 'b> UpdateApiGatewayCpi<'a, 'b> {
  pub fn new(
    program: &'b solana_account_info::AccountInfo<'a>,
          accounts: UpdateApiGatewayCpiAccounts<'a, 'b>,
              args: UpdateApiGatewayInstructionArgs,
      ) -> Self {
    Self {
      __program: program,
              oracle_data: accounts.oracle_data,
              authority: accounts.authority,
                    __args: args,
          }
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], &[])
  }
  #[inline(always)]
  pub fn invoke_with_remaining_accounts(&self, remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
  }
  #[inline(always)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed_with_remaining_accounts(
    &self,
    signers_seeds: &[&[&[u8]]],
    remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]
  ) -> solana_program_error::ProgramResult {
    let mut accounts = Vec::with_capacity(2+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new(
            *self.oracle_data.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.authority.key,
            true
          ));
                      remaining_accounts.iter().for_each(|remaining_account| {
      accounts.push(solana_instruction::AccountMeta {
          pubkey: *remaining_account.0.key,
          is_signer: remaining_account.1,
          is_writable: remaining_account.2,
      })
    });
    let mut data = UpdateApiGatewayInstructionData::new().try_to_vec().unwrap();
          let mut args = self.__args.try_to_vec().unwrap();
      data.append(&mut args);
    
    let instruction = solana_instruction::Instruction {
      program_id: crate::ORACLE_ID,
      accounts,
      data,
    };
    let mut account_infos = Vec::with_capacity(3 + remaining_accounts.len());
    account_infos.push(self.__program.clone());
                  account_infos.push(self.oracle_data.clone());
                        account_infos.push(self.authority.clone());
              remaining_accounts.iter().for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

    if signers_seeds.is_empty() {
      solana_cpi::invoke(&instruction, &account_infos)
    } else {
      solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
    }
  }
}

/// Instruction builder for `UpdateApiGateway` via CPI.
///
/// ### Accounts:
///
                ///   0. `[writable]` oracle_data
                ///   1. `[signer]` authority
#[derive(Clone, Debug)]
pub struct UpdateApiGatewayCpiBuilder<'a, 'b> {
  instruction: Box<UpdateApiGatewayCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> UpdateApiGatewayCpiBuilder<'a, 'b> {
  pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
    let instruction = Box::new(UpdateApiGatewayCpiBuilderInstruction {
      __program: program,
              oracle_data: None,
              authority: None,
                                            new_api_gateway: None,
                    __remaining_accounts: Vec::new(),
    });
    Self { instruction }
  }
      #[inline(always)]
    pub fn oracle_data(&mut self, oracle_data: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.oracle_data = Some(oracle_data);
                    self
    }
      #[inline(always)]
    pub fn authority(&mut self, authority: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.authority = Some(authority);
                    self
    }
                    #[inline(always)]
      pub fn new_api_gateway(&mut self, new_api_gateway: Pubkey) -> &mut Self {
        self.instruction.new_api_gateway = Some(new_api_gateway);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: &'b solana_account_info::AccountInfo<'a>, is_writable: bool, is_signer: bool) -> &mut Self {
    self.instruction.__remaining_accounts.push((account, is_writable, is_signer));
    self
  }
  /// Add additional accounts to the instruction.
  ///
  /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
  /// and a `bool` indicating whether the account is a signer or not.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> &mut Self {
    self.instruction.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed(&[])
  }
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
          let args = UpdateApiGatewayInstructionArgs {
                                                              new_api_gateway: self.instruction.new_api_gateway.clone().expect("new_api_gateway is not set"),
                                    };
        let instruction = UpdateApiGatewayCpi {
        __program: self.instruction.__program,
                  
          oracle_data: self.instruction.oracle_data.expect("oracle_data is not set"),
                  
          authority: self.instruction.authority.expect("authority is not set"),
                          __args: args,
            };
    instruction.invoke_signed_with_remaining_accounts(signers_seeds, &self.instruction.__remaining_accounts)
  }
}

#[derive(Clone, Debug)]
struct UpdateApiGatewayCpiBuilderInstruction<'a, 'b> {
  __program: &'b solana_account_info::AccountInfo<'a>,
            oracle_data: Option<&'b solana_account_info::AccountInfo<'a>>,
                authority: Option<&'b solana_account_info::AccountInfo<'a>>,
                        new_api_gateway: Option<Pubkey>,
        /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
  __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}

