//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use num_derive::FromPrimitive;
use thiserror::Error;

#[derive(Clone, Debug, Eq, Error, FromPrimitive, PartialEq)]
pub enum RegistryError {
    /// 6000 - Unauthorized user
    #[error("Unauthorized user")]
    UnauthorizedUser = 0x1770,
    /// 6001 - Unauthorized authority
    #[error("Unauthorized authority")]
    UnauthorizedAuthority = 0x1771,
    /// 6002 - Invalid user status
    #[error("Invalid user status")]
    InvalidUserStatus = 0x1772,
    /// 6003 - Invalid meter status
    #[error("Invalid meter status")]
    InvalidMeterStatus = 0x1773,
    /// 6004 - User not found
    #[error("User not found")]
    UserNotFound = 0x1774,
    /// 6005 - Meter not found
    #[error("Meter not found")]
    MeterNotFound = 0x1775,
    /// 6006 - No unsettled balance to tokenize
    #[error("No unsettled balance to tokenize")]
    NoUnsettledBalance = 0x1776,
}

impl From<RegistryError> for solana_program_error::ProgramError {
    fn from(e: RegistryError) -> Self {
        solana_program_error::ProgramError::Custom(e as u32)
    }
}

