/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
} from '@solana/kit';
import { REGISTRY_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const IS_VALID_METER_DISCRIMINATOR = new Uint8Array([
  151, 114, 52, 252, 238, 233, 81, 91,
]);

export function getIsValidMeterDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    IS_VALID_METER_DISCRIMINATOR
  );
}

export type IsValidMeterInstruction<
  TProgram extends string = typeof REGISTRY_PROGRAM_ADDRESS,
  TAccountMeterAccount extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountMeterAccount extends string
        ? ReadonlyAccount<TAccountMeterAccount>
        : TAccountMeterAccount,
      ...TRemainingAccounts,
    ]
  >;

export type IsValidMeterInstructionData = { discriminator: ReadonlyUint8Array };

export type IsValidMeterInstructionDataArgs = {};

export function getIsValidMeterInstructionDataEncoder(): FixedSizeEncoder<IsValidMeterInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: IS_VALID_METER_DISCRIMINATOR })
  );
}

export function getIsValidMeterInstructionDataDecoder(): FixedSizeDecoder<IsValidMeterInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getIsValidMeterInstructionDataCodec(): FixedSizeCodec<
  IsValidMeterInstructionDataArgs,
  IsValidMeterInstructionData
> {
  return combineCodec(
    getIsValidMeterInstructionDataEncoder(),
    getIsValidMeterInstructionDataDecoder()
  );
}

export type IsValidMeterInput<TAccountMeterAccount extends string = string> = {
  meterAccount: Address<TAccountMeterAccount>;
};

export function getIsValidMeterInstruction<
  TAccountMeterAccount extends string,
  TProgramAddress extends Address = typeof REGISTRY_PROGRAM_ADDRESS,
>(
  input: IsValidMeterInput<TAccountMeterAccount>,
  config?: { programAddress?: TProgramAddress }
): IsValidMeterInstruction<TProgramAddress, TAccountMeterAccount> {
  // Program address.
  const programAddress = config?.programAddress ?? REGISTRY_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    meterAccount: { value: input.meterAccount ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [getAccountMeta(accounts.meterAccount)],
    data: getIsValidMeterInstructionDataEncoder().encode({}),
    programAddress,
  } as IsValidMeterInstruction<TProgramAddress, TAccountMeterAccount>);
}

export type ParsedIsValidMeterInstruction<
  TProgram extends string = typeof REGISTRY_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    meterAccount: TAccountMetas[0];
  };
  data: IsValidMeterInstructionData;
};

export function parseIsValidMeterInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedIsValidMeterInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 1) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: { meterAccount: getNextAccount() },
    data: getIsValidMeterInstructionDataDecoder().decode(instruction.data),
  };
}
