/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getUtf8Decoder,
  getUtf8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { REGISTRY_PROGRAM_ADDRESS } from '../programs';
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from '../shared';
import {
  getUserTypeDecoder,
  getUserTypeEncoder,
  type UserType,
  type UserTypeArgs,
} from '../types';

export const REGISTER_USER_DISCRIMINATOR = new Uint8Array([
  2, 241, 150, 223, 99, 214, 116, 97,
]);

export function getRegisterUserDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    REGISTER_USER_DISCRIMINATOR
  );
}

export type RegisterUserInstruction<
  TProgram extends string = typeof REGISTRY_PROGRAM_ADDRESS,
  TAccountRegistry extends string | AccountMeta<string> = string,
  TAccountUserAccount extends string | AccountMeta<string> = string,
  TAccountUserAuthority extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | AccountMeta<string> = '11111111111111111111111111111111',
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountRegistry extends string
        ? WritableAccount<TAccountRegistry>
        : TAccountRegistry,
      TAccountUserAccount extends string
        ? WritableAccount<TAccountUserAccount>
        : TAccountUserAccount,
      TAccountUserAuthority extends string
        ? WritableSignerAccount<TAccountUserAuthority> &
            AccountSignerMeta<TAccountUserAuthority>
        : TAccountUserAuthority,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type RegisterUserInstructionData = {
  discriminator: ReadonlyUint8Array;
  userType: UserType;
  location: string;
};

export type RegisterUserInstructionDataArgs = {
  userType: UserTypeArgs;
  location: string;
};

export function getRegisterUserInstructionDataEncoder(): Encoder<RegisterUserInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['userType', getUserTypeEncoder()],
      ['location', addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
    ]),
    (value) => ({ ...value, discriminator: REGISTER_USER_DISCRIMINATOR })
  );
}

export function getRegisterUserInstructionDataDecoder(): Decoder<RegisterUserInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['userType', getUserTypeDecoder()],
    ['location', addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
  ]);
}

export function getRegisterUserInstructionDataCodec(): Codec<
  RegisterUserInstructionDataArgs,
  RegisterUserInstructionData
> {
  return combineCodec(
    getRegisterUserInstructionDataEncoder(),
    getRegisterUserInstructionDataDecoder()
  );
}

export type RegisterUserAsyncInput<
  TAccountRegistry extends string = string,
  TAccountUserAccount extends string = string,
  TAccountUserAuthority extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  registry: Address<TAccountRegistry>;
  userAccount?: Address<TAccountUserAccount>;
  userAuthority: TransactionSigner<TAccountUserAuthority>;
  systemProgram?: Address<TAccountSystemProgram>;
  userType: RegisterUserInstructionDataArgs['userType'];
  location: RegisterUserInstructionDataArgs['location'];
};

export async function getRegisterUserInstructionAsync<
  TAccountRegistry extends string,
  TAccountUserAccount extends string,
  TAccountUserAuthority extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof REGISTRY_PROGRAM_ADDRESS,
>(
  input: RegisterUserAsyncInput<
    TAccountRegistry,
    TAccountUserAccount,
    TAccountUserAuthority,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  RegisterUserInstruction<
    TProgramAddress,
    TAccountRegistry,
    TAccountUserAccount,
    TAccountUserAuthority,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? REGISTRY_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    registry: { value: input.registry ?? null, isWritable: true },
    userAccount: { value: input.userAccount ?? null, isWritable: true },
    userAuthority: { value: input.userAuthority ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.userAccount.value) {
    accounts.userAccount.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(new Uint8Array([117, 115, 101, 114])),
        getAddressEncoder().encode(expectAddress(accounts.userAuthority.value)),
      ],
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.registry),
      getAccountMeta(accounts.userAccount),
      getAccountMeta(accounts.userAuthority),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getRegisterUserInstructionDataEncoder().encode(
      args as RegisterUserInstructionDataArgs
    ),
    programAddress,
  } as RegisterUserInstruction<
    TProgramAddress,
    TAccountRegistry,
    TAccountUserAccount,
    TAccountUserAuthority,
    TAccountSystemProgram
  >);
}

export type RegisterUserInput<
  TAccountRegistry extends string = string,
  TAccountUserAccount extends string = string,
  TAccountUserAuthority extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  registry: Address<TAccountRegistry>;
  userAccount: Address<TAccountUserAccount>;
  userAuthority: TransactionSigner<TAccountUserAuthority>;
  systemProgram?: Address<TAccountSystemProgram>;
  userType: RegisterUserInstructionDataArgs['userType'];
  location: RegisterUserInstructionDataArgs['location'];
};

export function getRegisterUserInstruction<
  TAccountRegistry extends string,
  TAccountUserAccount extends string,
  TAccountUserAuthority extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof REGISTRY_PROGRAM_ADDRESS,
>(
  input: RegisterUserInput<
    TAccountRegistry,
    TAccountUserAccount,
    TAccountUserAuthority,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): RegisterUserInstruction<
  TProgramAddress,
  TAccountRegistry,
  TAccountUserAccount,
  TAccountUserAuthority,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? REGISTRY_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    registry: { value: input.registry ?? null, isWritable: true },
    userAccount: { value: input.userAccount ?? null, isWritable: true },
    userAuthority: { value: input.userAuthority ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.registry),
      getAccountMeta(accounts.userAccount),
      getAccountMeta(accounts.userAuthority),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getRegisterUserInstructionDataEncoder().encode(
      args as RegisterUserInstructionDataArgs
    ),
    programAddress,
  } as RegisterUserInstruction<
    TProgramAddress,
    TAccountRegistry,
    TAccountUserAccount,
    TAccountUserAuthority,
    TAccountSystemProgram
  >);
}

export type ParsedRegisterUserInstruction<
  TProgram extends string = typeof REGISTRY_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    registry: TAccountMetas[0];
    userAccount: TAccountMetas[1];
    userAuthority: TAccountMetas[2];
    systemProgram: TAccountMetas[3];
  };
  data: RegisterUserInstructionData;
};

export function parseRegisterUserInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedRegisterUserInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      registry: getNextAccount(),
      userAccount: getNextAccount(),
      userAuthority: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getRegisterUserInstructionDataDecoder().decode(instruction.data),
  };
}
