/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getUtf8Decoder,
  getUtf8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { REGISTRY_PROGRAM_ADDRESS } from '../programs';
import {
  expectSome,
  getAccountMetaFactory,
  type ResolvedAccount,
} from '../shared';
import {
  getMeterTypeDecoder,
  getMeterTypeEncoder,
  type MeterType,
  type MeterTypeArgs,
} from '../types';

export const REGISTER_METER_DISCRIMINATOR = new Uint8Array([
  49, 106, 87, 72, 138, 214, 224, 125,
]);

export function getRegisterMeterDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    REGISTER_METER_DISCRIMINATOR
  );
}

export type RegisterMeterInstruction<
  TProgram extends string = typeof REGISTRY_PROGRAM_ADDRESS,
  TAccountRegistry extends string | AccountMeta<string> = string,
  TAccountUserAccount extends string | AccountMeta<string> = string,
  TAccountMeterAccount extends string | AccountMeta<string> = string,
  TAccountUserAuthority extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | AccountMeta<string> = '11111111111111111111111111111111',
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountRegistry extends string
        ? WritableAccount<TAccountRegistry>
        : TAccountRegistry,
      TAccountUserAccount extends string
        ? WritableAccount<TAccountUserAccount>
        : TAccountUserAccount,
      TAccountMeterAccount extends string
        ? WritableAccount<TAccountMeterAccount>
        : TAccountMeterAccount,
      TAccountUserAuthority extends string
        ? WritableSignerAccount<TAccountUserAuthority> &
            AccountSignerMeta<TAccountUserAuthority>
        : TAccountUserAuthority,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type RegisterMeterInstructionData = {
  discriminator: ReadonlyUint8Array;
  meterId: string;
  meterType: MeterType;
};

export type RegisterMeterInstructionDataArgs = {
  meterId: string;
  meterType: MeterTypeArgs;
};

export function getRegisterMeterInstructionDataEncoder(): Encoder<RegisterMeterInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['meterId', addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
      ['meterType', getMeterTypeEncoder()],
    ]),
    (value) => ({ ...value, discriminator: REGISTER_METER_DISCRIMINATOR })
  );
}

export function getRegisterMeterInstructionDataDecoder(): Decoder<RegisterMeterInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['meterId', addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
    ['meterType', getMeterTypeDecoder()],
  ]);
}

export function getRegisterMeterInstructionDataCodec(): Codec<
  RegisterMeterInstructionDataArgs,
  RegisterMeterInstructionData
> {
  return combineCodec(
    getRegisterMeterInstructionDataEncoder(),
    getRegisterMeterInstructionDataDecoder()
  );
}

export type RegisterMeterAsyncInput<
  TAccountRegistry extends string = string,
  TAccountUserAccount extends string = string,
  TAccountMeterAccount extends string = string,
  TAccountUserAuthority extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  registry: Address<TAccountRegistry>;
  userAccount: Address<TAccountUserAccount>;
  meterAccount?: Address<TAccountMeterAccount>;
  userAuthority: TransactionSigner<TAccountUserAuthority>;
  systemProgram?: Address<TAccountSystemProgram>;
  meterId: RegisterMeterInstructionDataArgs['meterId'];
  meterType: RegisterMeterInstructionDataArgs['meterType'];
};

export async function getRegisterMeterInstructionAsync<
  TAccountRegistry extends string,
  TAccountUserAccount extends string,
  TAccountMeterAccount extends string,
  TAccountUserAuthority extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof REGISTRY_PROGRAM_ADDRESS,
>(
  input: RegisterMeterAsyncInput<
    TAccountRegistry,
    TAccountUserAccount,
    TAccountMeterAccount,
    TAccountUserAuthority,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  RegisterMeterInstruction<
    TProgramAddress,
    TAccountRegistry,
    TAccountUserAccount,
    TAccountMeterAccount,
    TAccountUserAuthority,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? REGISTRY_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    registry: { value: input.registry ?? null, isWritable: true },
    userAccount: { value: input.userAccount ?? null, isWritable: true },
    meterAccount: { value: input.meterAccount ?? null, isWritable: true },
    userAuthority: { value: input.userAuthority ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.meterAccount.value) {
    accounts.meterAccount.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(new Uint8Array([109, 101, 116, 101, 114])),
        addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder()).encode(
          expectSome(args.meterId)
        ),
      ],
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.registry),
      getAccountMeta(accounts.userAccount),
      getAccountMeta(accounts.meterAccount),
      getAccountMeta(accounts.userAuthority),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getRegisterMeterInstructionDataEncoder().encode(
      args as RegisterMeterInstructionDataArgs
    ),
    programAddress,
  } as RegisterMeterInstruction<
    TProgramAddress,
    TAccountRegistry,
    TAccountUserAccount,
    TAccountMeterAccount,
    TAccountUserAuthority,
    TAccountSystemProgram
  >);
}

export type RegisterMeterInput<
  TAccountRegistry extends string = string,
  TAccountUserAccount extends string = string,
  TAccountMeterAccount extends string = string,
  TAccountUserAuthority extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  registry: Address<TAccountRegistry>;
  userAccount: Address<TAccountUserAccount>;
  meterAccount: Address<TAccountMeterAccount>;
  userAuthority: TransactionSigner<TAccountUserAuthority>;
  systemProgram?: Address<TAccountSystemProgram>;
  meterId: RegisterMeterInstructionDataArgs['meterId'];
  meterType: RegisterMeterInstructionDataArgs['meterType'];
};

export function getRegisterMeterInstruction<
  TAccountRegistry extends string,
  TAccountUserAccount extends string,
  TAccountMeterAccount extends string,
  TAccountUserAuthority extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof REGISTRY_PROGRAM_ADDRESS,
>(
  input: RegisterMeterInput<
    TAccountRegistry,
    TAccountUserAccount,
    TAccountMeterAccount,
    TAccountUserAuthority,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): RegisterMeterInstruction<
  TProgramAddress,
  TAccountRegistry,
  TAccountUserAccount,
  TAccountMeterAccount,
  TAccountUserAuthority,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? REGISTRY_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    registry: { value: input.registry ?? null, isWritable: true },
    userAccount: { value: input.userAccount ?? null, isWritable: true },
    meterAccount: { value: input.meterAccount ?? null, isWritable: true },
    userAuthority: { value: input.userAuthority ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.registry),
      getAccountMeta(accounts.userAccount),
      getAccountMeta(accounts.meterAccount),
      getAccountMeta(accounts.userAuthority),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getRegisterMeterInstructionDataEncoder().encode(
      args as RegisterMeterInstructionDataArgs
    ),
    programAddress,
  } as RegisterMeterInstruction<
    TProgramAddress,
    TAccountRegistry,
    TAccountUserAccount,
    TAccountMeterAccount,
    TAccountUserAuthority,
    TAccountSystemProgram
  >);
}

export type ParsedRegisterMeterInstruction<
  TProgram extends string = typeof REGISTRY_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    registry: TAccountMetas[0];
    userAccount: TAccountMetas[1];
    meterAccount: TAccountMetas[2];
    userAuthority: TAccountMetas[3];
    systemProgram: TAccountMetas[4];
  };
  data: RegisterMeterInstructionData;
};

export function parseRegisterMeterInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedRegisterMeterInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 5) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      registry: getNextAccount(),
      userAccount: getNextAccount(),
      meterAccount: getNextAccount(),
      userAuthority: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getRegisterMeterInstructionDataDecoder().decode(instruction.data),
  };
}
