/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/kit';
import { REGISTRY_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const SETTLE_METER_BALANCE_DISCRIMINATOR = new Uint8Array([
  178, 46, 241, 202, 53, 99, 79, 119,
]);

export function getSettleMeterBalanceDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    SETTLE_METER_BALANCE_DISCRIMINATOR
  );
}

export type SettleMeterBalanceInstruction<
  TProgram extends string = typeof REGISTRY_PROGRAM_ADDRESS,
  TAccountMeterAccount extends string | AccountMeta<string> = string,
  TAccountMeterOwner extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountMeterAccount extends string
        ? WritableAccount<TAccountMeterAccount>
        : TAccountMeterAccount,
      TAccountMeterOwner extends string
        ? ReadonlySignerAccount<TAccountMeterOwner> &
            AccountSignerMeta<TAccountMeterOwner>
        : TAccountMeterOwner,
      ...TRemainingAccounts,
    ]
  >;

export type SettleMeterBalanceInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type SettleMeterBalanceInstructionDataArgs = {};

export function getSettleMeterBalanceInstructionDataEncoder(): FixedSizeEncoder<SettleMeterBalanceInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: SETTLE_METER_BALANCE_DISCRIMINATOR })
  );
}

export function getSettleMeterBalanceInstructionDataDecoder(): FixedSizeDecoder<SettleMeterBalanceInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getSettleMeterBalanceInstructionDataCodec(): FixedSizeCodec<
  SettleMeterBalanceInstructionDataArgs,
  SettleMeterBalanceInstructionData
> {
  return combineCodec(
    getSettleMeterBalanceInstructionDataEncoder(),
    getSettleMeterBalanceInstructionDataDecoder()
  );
}

export type SettleMeterBalanceInput<
  TAccountMeterAccount extends string = string,
  TAccountMeterOwner extends string = string,
> = {
  meterAccount: Address<TAccountMeterAccount>;
  meterOwner: TransactionSigner<TAccountMeterOwner>;
};

export function getSettleMeterBalanceInstruction<
  TAccountMeterAccount extends string,
  TAccountMeterOwner extends string,
  TProgramAddress extends Address = typeof REGISTRY_PROGRAM_ADDRESS,
>(
  input: SettleMeterBalanceInput<TAccountMeterAccount, TAccountMeterOwner>,
  config?: { programAddress?: TProgramAddress }
): SettleMeterBalanceInstruction<
  TProgramAddress,
  TAccountMeterAccount,
  TAccountMeterOwner
> {
  // Program address.
  const programAddress = config?.programAddress ?? REGISTRY_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    meterAccount: { value: input.meterAccount ?? null, isWritable: true },
    meterOwner: { value: input.meterOwner ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.meterAccount),
      getAccountMeta(accounts.meterOwner),
    ],
    data: getSettleMeterBalanceInstructionDataEncoder().encode({}),
    programAddress,
  } as SettleMeterBalanceInstruction<
    TProgramAddress,
    TAccountMeterAccount,
    TAccountMeterOwner
  >);
}

export type ParsedSettleMeterBalanceInstruction<
  TProgram extends string = typeof REGISTRY_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    meterAccount: TAccountMetas[0];
    meterOwner: TAccountMetas[1];
  };
  data: SettleMeterBalanceInstructionData;
};

export function parseSettleMeterBalanceInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedSettleMeterBalanceInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: { meterAccount: getNextAccount(), meterOwner: getNextAccount() },
    data: getSettleMeterBalanceInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
