//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use solana_pubkey::{pubkey, Pubkey};


  /// `trading` program ID.
  pub const TRADING_ID: Pubkey = pubkey!("GZnqNTJsre6qB4pWCQRE9FiJU2GUeBtBDPp6s7zosctk");

