//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

  pub(crate) mod r#emergency_pause;
  pub(crate) mod r#emergency_unpause;
  pub(crate) mod r#get_governance_stats;
  pub(crate) mod r#initialize_poa;
  pub(crate) mod r#issue_erc;
  pub(crate) mod r#set_maintenance_mode;
  pub(crate) mod r#update_authority_info;
  pub(crate) mod r#update_erc_limits;
  pub(crate) mod r#update_governance_config;
  pub(crate) mod r#validate_erc_for_trading;

  pub use self::r#emergency_pause::*;
  pub use self::r#emergency_unpause::*;
  pub use self::r#get_governance_stats::*;
  pub use self::r#initialize_poa::*;
  pub use self::r#issue_erc::*;
  pub use self::r#set_maintenance_mode::*;
  pub use self::r#update_authority_info::*;
  pub use self::r#update_erc_limits::*;
  pub use self::r#update_governance_config::*;
  pub use self::r#validate_erc_for_trading::*;

