//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshSerialize;
use borsh::BorshDeserialize;

pub const UPDATE_ERC_LIMITS_DISCRIMINATOR: [u8; 8] = [235, 208, 197, 149, 62, 109, 254, 110];

/// Accounts.
#[derive(Debug)]
pub struct UpdateErcLimits {
      
              
          pub poa_config: solana_pubkey::Pubkey,
          
              
          pub authority: solana_pubkey::Pubkey,
      }

impl UpdateErcLimits {
  pub fn instruction(&self, args: UpdateErcLimitsInstructionArgs) -> solana_instruction::Instruction {
    self.instruction_with_remaining_accounts(args, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::vec_init_then_push)]
  pub fn instruction_with_remaining_accounts(&self, args: UpdateErcLimitsInstructionArgs, remaining_accounts: &[solana_instruction::AccountMeta]) -> solana_instruction::Instruction {
    let mut accounts = Vec::with_capacity(2+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new(
            self.poa_config,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.authority,
            true
          ));
                      accounts.extend_from_slice(remaining_accounts);
    let mut data = UpdateErcLimitsInstructionData::new().try_to_vec().unwrap();
          let mut args = args.try_to_vec().unwrap();
      data.append(&mut args);
    
    solana_instruction::Instruction {
      program_id: crate::GOVERNANCE_ID,
      accounts,
      data,
    }
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct UpdateErcLimitsInstructionData {
            discriminator: [u8; 8],
                        }

impl UpdateErcLimitsInstructionData {
  pub fn new() -> Self {
    Self {
                        discriminator: [235, 208, 197, 149, 62, 109, 254, 110],
                                                            }
  }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
    borsh::to_vec(self)
  }
  }

impl Default for UpdateErcLimitsInstructionData {
  fn default() -> Self {
    Self::new()
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct UpdateErcLimitsInstructionArgs {
                  pub min_energy_amount: u64,
                pub max_erc_amount: u64,
                pub erc_validity_period: i64,
      }

impl UpdateErcLimitsInstructionArgs {
  pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
    borsh::to_vec(self)
  }
}


/// Instruction builder for `UpdateErcLimits`.
///
/// ### Accounts:
///
                ///   0. `[writable]` poa_config
                ///   1. `[signer]` authority
#[derive(Clone, Debug, Default)]
pub struct UpdateErcLimitsBuilder {
            poa_config: Option<solana_pubkey::Pubkey>,
                authority: Option<solana_pubkey::Pubkey>,
                        min_energy_amount: Option<u64>,
                max_erc_amount: Option<u64>,
                erc_validity_period: Option<i64>,
        __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl UpdateErcLimitsBuilder {
  pub fn new() -> Self {
    Self::default()
  }
            #[inline(always)]
    pub fn poa_config(&mut self, poa_config: solana_pubkey::Pubkey) -> &mut Self {
                        self.poa_config = Some(poa_config);
                    self
    }
            #[inline(always)]
    pub fn authority(&mut self, authority: solana_pubkey::Pubkey) -> &mut Self {
                        self.authority = Some(authority);
                    self
    }
                    #[inline(always)]
      pub fn min_energy_amount(&mut self, min_energy_amount: u64) -> &mut Self {
        self.min_energy_amount = Some(min_energy_amount);
        self
      }
                #[inline(always)]
      pub fn max_erc_amount(&mut self, max_erc_amount: u64) -> &mut Self {
        self.max_erc_amount = Some(max_erc_amount);
        self
      }
                #[inline(always)]
      pub fn erc_validity_period(&mut self, erc_validity_period: i64) -> &mut Self {
        self.erc_validity_period = Some(erc_validity_period);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
    self.__remaining_accounts.push(account);
    self
  }
  /// Add additional accounts to the instruction.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[solana_instruction::AccountMeta]) -> &mut Self {
    self.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[allow(clippy::clone_on_copy)]
  pub fn instruction(&self) -> solana_instruction::Instruction {
    let accounts = UpdateErcLimits {
                              poa_config: self.poa_config.expect("poa_config is not set"),
                                        authority: self.authority.expect("authority is not set"),
                      };
          let args = UpdateErcLimitsInstructionArgs {
                                                              min_energy_amount: self.min_energy_amount.clone().expect("min_energy_amount is not set"),
                                                                  max_erc_amount: self.max_erc_amount.clone().expect("max_erc_amount is not set"),
                                                                  erc_validity_period: self.erc_validity_period.clone().expect("erc_validity_period is not set"),
                                    };
    
    accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
  }
}

  /// `update_erc_limits` CPI accounts.
  pub struct UpdateErcLimitsCpiAccounts<'a, 'b> {
          
                    
              pub poa_config: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub authority: &'b solana_account_info::AccountInfo<'a>,
            }

/// `update_erc_limits` CPI instruction.
pub struct UpdateErcLimitsCpi<'a, 'b> {
  /// The program to invoke.
  pub __program: &'b solana_account_info::AccountInfo<'a>,
      
              
          pub poa_config: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub authority: &'b solana_account_info::AccountInfo<'a>,
            /// The arguments for the instruction.
    pub __args: UpdateErcLimitsInstructionArgs,
  }

impl<'a, 'b> UpdateErcLimitsCpi<'a, 'b> {
  pub fn new(
    program: &'b solana_account_info::AccountInfo<'a>,
          accounts: UpdateErcLimitsCpiAccounts<'a, 'b>,
              args: UpdateErcLimitsInstructionArgs,
      ) -> Self {
    Self {
      __program: program,
              poa_config: accounts.poa_config,
              authority: accounts.authority,
                    __args: args,
          }
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], &[])
  }
  #[inline(always)]
  pub fn invoke_with_remaining_accounts(&self, remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
  }
  #[inline(always)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed_with_remaining_accounts(
    &self,
    signers_seeds: &[&[&[u8]]],
    remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]
  ) -> solana_program_error::ProgramResult {
    let mut accounts = Vec::with_capacity(2+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new(
            *self.poa_config.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.authority.key,
            true
          ));
                      remaining_accounts.iter().for_each(|remaining_account| {
      accounts.push(solana_instruction::AccountMeta {
          pubkey: *remaining_account.0.key,
          is_signer: remaining_account.1,
          is_writable: remaining_account.2,
      })
    });
    let mut data = UpdateErcLimitsInstructionData::new().try_to_vec().unwrap();
          let mut args = self.__args.try_to_vec().unwrap();
      data.append(&mut args);
    
    let instruction = solana_instruction::Instruction {
      program_id: crate::GOVERNANCE_ID,
      accounts,
      data,
    };
    let mut account_infos = Vec::with_capacity(3 + remaining_accounts.len());
    account_infos.push(self.__program.clone());
                  account_infos.push(self.poa_config.clone());
                        account_infos.push(self.authority.clone());
              remaining_accounts.iter().for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

    if signers_seeds.is_empty() {
      solana_cpi::invoke(&instruction, &account_infos)
    } else {
      solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
    }
  }
}

/// Instruction builder for `UpdateErcLimits` via CPI.
///
/// ### Accounts:
///
                ///   0. `[writable]` poa_config
                ///   1. `[signer]` authority
#[derive(Clone, Debug)]
pub struct UpdateErcLimitsCpiBuilder<'a, 'b> {
  instruction: Box<UpdateErcLimitsCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> UpdateErcLimitsCpiBuilder<'a, 'b> {
  pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
    let instruction = Box::new(UpdateErcLimitsCpiBuilderInstruction {
      __program: program,
              poa_config: None,
              authority: None,
                                            min_energy_amount: None,
                                max_erc_amount: None,
                                erc_validity_period: None,
                    __remaining_accounts: Vec::new(),
    });
    Self { instruction }
  }
      #[inline(always)]
    pub fn poa_config(&mut self, poa_config: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.poa_config = Some(poa_config);
                    self
    }
      #[inline(always)]
    pub fn authority(&mut self, authority: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.authority = Some(authority);
                    self
    }
                    #[inline(always)]
      pub fn min_energy_amount(&mut self, min_energy_amount: u64) -> &mut Self {
        self.instruction.min_energy_amount = Some(min_energy_amount);
        self
      }
                #[inline(always)]
      pub fn max_erc_amount(&mut self, max_erc_amount: u64) -> &mut Self {
        self.instruction.max_erc_amount = Some(max_erc_amount);
        self
      }
                #[inline(always)]
      pub fn erc_validity_period(&mut self, erc_validity_period: i64) -> &mut Self {
        self.instruction.erc_validity_period = Some(erc_validity_period);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: &'b solana_account_info::AccountInfo<'a>, is_writable: bool, is_signer: bool) -> &mut Self {
    self.instruction.__remaining_accounts.push((account, is_writable, is_signer));
    self
  }
  /// Add additional accounts to the instruction.
  ///
  /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
  /// and a `bool` indicating whether the account is a signer or not.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> &mut Self {
    self.instruction.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed(&[])
  }
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
          let args = UpdateErcLimitsInstructionArgs {
                                                              min_energy_amount: self.instruction.min_energy_amount.clone().expect("min_energy_amount is not set"),
                                                                  max_erc_amount: self.instruction.max_erc_amount.clone().expect("max_erc_amount is not set"),
                                                                  erc_validity_period: self.instruction.erc_validity_period.clone().expect("erc_validity_period is not set"),
                                    };
        let instruction = UpdateErcLimitsCpi {
        __program: self.instruction.__program,
                  
          poa_config: self.instruction.poa_config.expect("poa_config is not set"),
                  
          authority: self.instruction.authority.expect("authority is not set"),
                          __args: args,
            };
    instruction.invoke_signed_with_remaining_accounts(signers_seeds, &self.instruction.__remaining_accounts)
  }
}

#[derive(Clone, Debug)]
struct UpdateErcLimitsCpiBuilderInstruction<'a, 'b> {
  __program: &'b solana_account_info::AccountInfo<'a>,
            poa_config: Option<&'b solana_account_info::AccountInfo<'a>>,
                authority: Option<&'b solana_account_info::AccountInfo<'a>>,
                        min_energy_amount: Option<u64>,
                max_erc_amount: Option<u64>,
                erc_validity_period: Option<i64>,
        /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
  __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}

