//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshSerialize;
use borsh::BorshDeserialize;

pub const VALIDATE_ERC_FOR_TRADING_DISCRIMINATOR: [u8; 8] = [9, 215, 176, 63, 247, 150, 72, 139];

/// Accounts.
#[derive(Debug)]
pub struct ValidateErcForTrading {
      
              
          pub poa_config: solana_pubkey::Pubkey,
          
              
          pub erc_certificate: solana_pubkey::Pubkey,
          
              
          pub authority: solana_pubkey::Pubkey,
      }

impl ValidateErcForTrading {
  pub fn instruction(&self) -> solana_instruction::Instruction {
    self.instruction_with_remaining_accounts(&[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::vec_init_then_push)]
  pub fn instruction_with_remaining_accounts(&self, remaining_accounts: &[solana_instruction::AccountMeta]) -> solana_instruction::Instruction {
    let mut accounts = Vec::with_capacity(3+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.poa_config,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.erc_certificate,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.authority,
            true
          ));
                      accounts.extend_from_slice(remaining_accounts);
    let data = ValidateErcForTradingInstructionData::new().try_to_vec().unwrap();
    
    solana_instruction::Instruction {
      program_id: crate::GOVERNANCE_ID,
      accounts,
      data,
    }
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct ValidateErcForTradingInstructionData {
            discriminator: [u8; 8],
      }

impl ValidateErcForTradingInstructionData {
  pub fn new() -> Self {
    Self {
                        discriminator: [9, 215, 176, 63, 247, 150, 72, 139],
                  }
  }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
    borsh::to_vec(self)
  }
  }

impl Default for ValidateErcForTradingInstructionData {
  fn default() -> Self {
    Self::new()
  }
}



/// Instruction builder for `ValidateErcForTrading`.
///
/// ### Accounts:
///
          ///   0. `[]` poa_config
                ///   1. `[writable]` erc_certificate
                ///   2. `[signer]` authority
#[derive(Clone, Debug, Default)]
pub struct ValidateErcForTradingBuilder {
            poa_config: Option<solana_pubkey::Pubkey>,
                erc_certificate: Option<solana_pubkey::Pubkey>,
                authority: Option<solana_pubkey::Pubkey>,
                __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl ValidateErcForTradingBuilder {
  pub fn new() -> Self {
    Self::default()
  }
            #[inline(always)]
    pub fn poa_config(&mut self, poa_config: solana_pubkey::Pubkey) -> &mut Self {
                        self.poa_config = Some(poa_config);
                    self
    }
            #[inline(always)]
    pub fn erc_certificate(&mut self, erc_certificate: solana_pubkey::Pubkey) -> &mut Self {
                        self.erc_certificate = Some(erc_certificate);
                    self
    }
            #[inline(always)]
    pub fn authority(&mut self, authority: solana_pubkey::Pubkey) -> &mut Self {
                        self.authority = Some(authority);
                    self
    }
            /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
    self.__remaining_accounts.push(account);
    self
  }
  /// Add additional accounts to the instruction.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[solana_instruction::AccountMeta]) -> &mut Self {
    self.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[allow(clippy::clone_on_copy)]
  pub fn instruction(&self) -> solana_instruction::Instruction {
    let accounts = ValidateErcForTrading {
                              poa_config: self.poa_config.expect("poa_config is not set"),
                                        erc_certificate: self.erc_certificate.expect("erc_certificate is not set"),
                                        authority: self.authority.expect("authority is not set"),
                      };
    
    accounts.instruction_with_remaining_accounts(&self.__remaining_accounts)
  }
}

  /// `validate_erc_for_trading` CPI accounts.
  pub struct ValidateErcForTradingCpiAccounts<'a, 'b> {
          
                    
              pub poa_config: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub erc_certificate: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub authority: &'b solana_account_info::AccountInfo<'a>,
            }

/// `validate_erc_for_trading` CPI instruction.
pub struct ValidateErcForTradingCpi<'a, 'b> {
  /// The program to invoke.
  pub __program: &'b solana_account_info::AccountInfo<'a>,
      
              
          pub poa_config: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub erc_certificate: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub authority: &'b solana_account_info::AccountInfo<'a>,
        }

impl<'a, 'b> ValidateErcForTradingCpi<'a, 'b> {
  pub fn new(
    program: &'b solana_account_info::AccountInfo<'a>,
          accounts: ValidateErcForTradingCpiAccounts<'a, 'b>,
          ) -> Self {
    Self {
      __program: program,
              poa_config: accounts.poa_config,
              erc_certificate: accounts.erc_certificate,
              authority: accounts.authority,
                }
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], &[])
  }
  #[inline(always)]
  pub fn invoke_with_remaining_accounts(&self, remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
  }
  #[inline(always)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed_with_remaining_accounts(
    &self,
    signers_seeds: &[&[&[u8]]],
    remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]
  ) -> solana_program_error::ProgramResult {
    let mut accounts = Vec::with_capacity(3+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.poa_config.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.erc_certificate.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.authority.key,
            true
          ));
                      remaining_accounts.iter().for_each(|remaining_account| {
      accounts.push(solana_instruction::AccountMeta {
          pubkey: *remaining_account.0.key,
          is_signer: remaining_account.1,
          is_writable: remaining_account.2,
      })
    });
    let data = ValidateErcForTradingInstructionData::new().try_to_vec().unwrap();
    
    let instruction = solana_instruction::Instruction {
      program_id: crate::GOVERNANCE_ID,
      accounts,
      data,
    };
    let mut account_infos = Vec::with_capacity(4 + remaining_accounts.len());
    account_infos.push(self.__program.clone());
                  account_infos.push(self.poa_config.clone());
                        account_infos.push(self.erc_certificate.clone());
                        account_infos.push(self.authority.clone());
              remaining_accounts.iter().for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

    if signers_seeds.is_empty() {
      solana_cpi::invoke(&instruction, &account_infos)
    } else {
      solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
    }
  }
}

/// Instruction builder for `ValidateErcForTrading` via CPI.
///
/// ### Accounts:
///
          ///   0. `[]` poa_config
                ///   1. `[writable]` erc_certificate
                ///   2. `[signer]` authority
#[derive(Clone, Debug)]
pub struct ValidateErcForTradingCpiBuilder<'a, 'b> {
  instruction: Box<ValidateErcForTradingCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> ValidateErcForTradingCpiBuilder<'a, 'b> {
  pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
    let instruction = Box::new(ValidateErcForTradingCpiBuilderInstruction {
      __program: program,
              poa_config: None,
              erc_certificate: None,
              authority: None,
                                __remaining_accounts: Vec::new(),
    });
    Self { instruction }
  }
      #[inline(always)]
    pub fn poa_config(&mut self, poa_config: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.poa_config = Some(poa_config);
                    self
    }
      #[inline(always)]
    pub fn erc_certificate(&mut self, erc_certificate: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.erc_certificate = Some(erc_certificate);
                    self
    }
      #[inline(always)]
    pub fn authority(&mut self, authority: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.authority = Some(authority);
                    self
    }
            /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: &'b solana_account_info::AccountInfo<'a>, is_writable: bool, is_signer: bool) -> &mut Self {
    self.instruction.__remaining_accounts.push((account, is_writable, is_signer));
    self
  }
  /// Add additional accounts to the instruction.
  ///
  /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
  /// and a `bool` indicating whether the account is a signer or not.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> &mut Self {
    self.instruction.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed(&[])
  }
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        let instruction = ValidateErcForTradingCpi {
        __program: self.instruction.__program,
                  
          poa_config: self.instruction.poa_config.expect("poa_config is not set"),
                  
          erc_certificate: self.instruction.erc_certificate.expect("erc_certificate is not set"),
                  
          authority: self.instruction.authority.expect("authority is not set"),
                    };
    instruction.invoke_signed_with_remaining_accounts(signers_seeds, &self.instruction.__remaining_accounts)
  }
}

#[derive(Clone, Debug)]
struct ValidateErcForTradingCpiBuilderInstruction<'a, 'b> {
  __program: &'b solana_account_info::AccountInfo<'a>,
            poa_config: Option<&'b solana_account_info::AccountInfo<'a>>,
                erc_certificate: Option<&'b solana_account_info::AccountInfo<'a>>,
                authority: Option<&'b solana_account_info::AccountInfo<'a>>,
                /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
  __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}

