//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshSerialize;
use borsh::BorshDeserialize;

pub const GET_UNSETTLED_BALANCE_DISCRIMINATOR: [u8; 8] = [178, 120, 95, 9, 18, 81, 181, 83];

/// Accounts.
#[derive(Debug)]
pub struct GetUnsettledBalance {
      
              
          pub meter_account: solana_pubkey::Pubkey,
      }

impl GetUnsettledBalance {
  pub fn instruction(&self) -> solana_instruction::Instruction {
    self.instruction_with_remaining_accounts(&[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::vec_init_then_push)]
  pub fn instruction_with_remaining_accounts(&self, remaining_accounts: &[solana_instruction::AccountMeta]) -> solana_instruction::Instruction {
    let mut accounts = Vec::with_capacity(1+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.meter_account,
            false
          ));
                      accounts.extend_from_slice(remaining_accounts);
    let data = GetUnsettledBalanceInstructionData::new().try_to_vec().unwrap();
    
    solana_instruction::Instruction {
      program_id: crate::REGISTRY_ID,
      accounts,
      data,
    }
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct GetUnsettledBalanceInstructionData {
            discriminator: [u8; 8],
      }

impl GetUnsettledBalanceInstructionData {
  pub fn new() -> Self {
    Self {
                        discriminator: [178, 120, 95, 9, 18, 81, 181, 83],
                  }
  }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
    borsh::to_vec(self)
  }
  }

impl Default for GetUnsettledBalanceInstructionData {
  fn default() -> Self {
    Self::new()
  }
}



/// Instruction builder for `GetUnsettledBalance`.
///
/// ### Accounts:
///
          ///   0. `[]` meter_account
#[derive(Clone, Debug, Default)]
pub struct GetUnsettledBalanceBuilder {
            meter_account: Option<solana_pubkey::Pubkey>,
                __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl GetUnsettledBalanceBuilder {
  pub fn new() -> Self {
    Self::default()
  }
            #[inline(always)]
    pub fn meter_account(&mut self, meter_account: solana_pubkey::Pubkey) -> &mut Self {
                        self.meter_account = Some(meter_account);
                    self
    }
            /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
    self.__remaining_accounts.push(account);
    self
  }
  /// Add additional accounts to the instruction.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[solana_instruction::AccountMeta]) -> &mut Self {
    self.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[allow(clippy::clone_on_copy)]
  pub fn instruction(&self) -> solana_instruction::Instruction {
    let accounts = GetUnsettledBalance {
                              meter_account: self.meter_account.expect("meter_account is not set"),
                      };
    
    accounts.instruction_with_remaining_accounts(&self.__remaining_accounts)
  }
}

  /// `get_unsettled_balance` CPI accounts.
  pub struct GetUnsettledBalanceCpiAccounts<'a, 'b> {
          
                    
              pub meter_account: &'b solana_account_info::AccountInfo<'a>,
            }

/// `get_unsettled_balance` CPI instruction.
pub struct GetUnsettledBalanceCpi<'a, 'b> {
  /// The program to invoke.
  pub __program: &'b solana_account_info::AccountInfo<'a>,
      
              
          pub meter_account: &'b solana_account_info::AccountInfo<'a>,
        }

impl<'a, 'b> GetUnsettledBalanceCpi<'a, 'b> {
  pub fn new(
    program: &'b solana_account_info::AccountInfo<'a>,
          accounts: GetUnsettledBalanceCpiAccounts<'a, 'b>,
          ) -> Self {
    Self {
      __program: program,
              meter_account: accounts.meter_account,
                }
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], &[])
  }
  #[inline(always)]
  pub fn invoke_with_remaining_accounts(&self, remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
  }
  #[inline(always)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed_with_remaining_accounts(
    &self,
    signers_seeds: &[&[&[u8]]],
    remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]
  ) -> solana_program_error::ProgramResult {
    let mut accounts = Vec::with_capacity(1+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.meter_account.key,
            false
          ));
                      remaining_accounts.iter().for_each(|remaining_account| {
      accounts.push(solana_instruction::AccountMeta {
          pubkey: *remaining_account.0.key,
          is_signer: remaining_account.1,
          is_writable: remaining_account.2,
      })
    });
    let data = GetUnsettledBalanceInstructionData::new().try_to_vec().unwrap();
    
    let instruction = solana_instruction::Instruction {
      program_id: crate::REGISTRY_ID,
      accounts,
      data,
    };
    let mut account_infos = Vec::with_capacity(2 + remaining_accounts.len());
    account_infos.push(self.__program.clone());
                  account_infos.push(self.meter_account.clone());
              remaining_accounts.iter().for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

    if signers_seeds.is_empty() {
      solana_cpi::invoke(&instruction, &account_infos)
    } else {
      solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
    }
  }
}

/// Instruction builder for `GetUnsettledBalance` via CPI.
///
/// ### Accounts:
///
          ///   0. `[]` meter_account
#[derive(Clone, Debug)]
pub struct GetUnsettledBalanceCpiBuilder<'a, 'b> {
  instruction: Box<GetUnsettledBalanceCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> GetUnsettledBalanceCpiBuilder<'a, 'b> {
  pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
    let instruction = Box::new(GetUnsettledBalanceCpiBuilderInstruction {
      __program: program,
              meter_account: None,
                                __remaining_accounts: Vec::new(),
    });
    Self { instruction }
  }
      #[inline(always)]
    pub fn meter_account(&mut self, meter_account: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.meter_account = Some(meter_account);
                    self
    }
            /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: &'b solana_account_info::AccountInfo<'a>, is_writable: bool, is_signer: bool) -> &mut Self {
    self.instruction.__remaining_accounts.push((account, is_writable, is_signer));
    self
  }
  /// Add additional accounts to the instruction.
  ///
  /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
  /// and a `bool` indicating whether the account is a signer or not.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> &mut Self {
    self.instruction.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed(&[])
  }
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        let instruction = GetUnsettledBalanceCpi {
        __program: self.instruction.__program,
                  
          meter_account: self.instruction.meter_account.expect("meter_account is not set"),
                    };
    instruction.invoke_signed_with_remaining_accounts(signers_seeds, &self.instruction.__remaining_accounts)
  }
}

#[derive(Clone, Debug)]
struct GetUnsettledBalanceCpiBuilderInstruction<'a, 'b> {
  __program: &'b solana_account_info::AccountInfo<'a>,
            meter_account: Option<&'b solana_account_info::AccountInfo<'a>>,
                /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
  __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}

