//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use crate::generated::types::UserType;
use borsh::BorshSerialize;
use borsh::BorshDeserialize;

pub const REGISTER_USER_DISCRIMINATOR: [u8; 8] = [2, 241, 150, 223, 99, 214, 116, 97];

/// Accounts.
#[derive(Debug)]
pub struct RegisterUser {
      
              
          pub registry: solana_pubkey::Pubkey,
          
              
          pub user_account: solana_pubkey::Pubkey,
          
              
          pub user_authority: solana_pubkey::Pubkey,
          
              
          pub system_program: solana_pubkey::Pubkey,
      }

impl RegisterUser {
  pub fn instruction(&self, args: RegisterUserInstructionArgs) -> solana_instruction::Instruction {
    self.instruction_with_remaining_accounts(args, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::vec_init_then_push)]
  pub fn instruction_with_remaining_accounts(&self, args: RegisterUserInstructionArgs, remaining_accounts: &[solana_instruction::AccountMeta]) -> solana_instruction::Instruction {
    let mut accounts = Vec::with_capacity(4+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new(
            self.registry,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.user_account,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.user_authority,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.system_program,
            false
          ));
                      accounts.extend_from_slice(remaining_accounts);
    let mut data = RegisterUserInstructionData::new().try_to_vec().unwrap();
          let mut args = args.try_to_vec().unwrap();
      data.append(&mut args);
    
    solana_instruction::Instruction {
      program_id: crate::REGISTRY_ID,
      accounts,
      data,
    }
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct RegisterUserInstructionData {
            discriminator: [u8; 8],
                  }

impl RegisterUserInstructionData {
  pub fn new() -> Self {
    Self {
                        discriminator: [2, 241, 150, 223, 99, 214, 116, 97],
                                              }
  }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
    borsh::to_vec(self)
  }
  }

impl Default for RegisterUserInstructionData {
  fn default() -> Self {
    Self::new()
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct RegisterUserInstructionArgs {
                  pub user_type: UserType,
                pub location: String,
      }

impl RegisterUserInstructionArgs {
  pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
    borsh::to_vec(self)
  }
}


/// Instruction builder for `RegisterUser`.
///
/// ### Accounts:
///
                ///   0. `[writable]` registry
                ///   1. `[writable]` user_account
                      ///   2. `[writable, signer]` user_authority
                ///   3. `[optional]` system_program (default to `11111111111111111111111111111111`)
#[derive(Clone, Debug, Default)]
pub struct RegisterUserBuilder {
            registry: Option<solana_pubkey::Pubkey>,
                user_account: Option<solana_pubkey::Pubkey>,
                user_authority: Option<solana_pubkey::Pubkey>,
                system_program: Option<solana_pubkey::Pubkey>,
                        user_type: Option<UserType>,
                location: Option<String>,
        __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl RegisterUserBuilder {
  pub fn new() -> Self {
    Self::default()
  }
            #[inline(always)]
    pub fn registry(&mut self, registry: solana_pubkey::Pubkey) -> &mut Self {
                        self.registry = Some(registry);
                    self
    }
            #[inline(always)]
    pub fn user_account(&mut self, user_account: solana_pubkey::Pubkey) -> &mut Self {
                        self.user_account = Some(user_account);
                    self
    }
            #[inline(always)]
    pub fn user_authority(&mut self, user_authority: solana_pubkey::Pubkey) -> &mut Self {
                        self.user_authority = Some(user_authority);
                    self
    }
            /// `[optional account, default to '11111111111111111111111111111111']`
#[inline(always)]
    pub fn system_program(&mut self, system_program: solana_pubkey::Pubkey) -> &mut Self {
                        self.system_program = Some(system_program);
                    self
    }
                    #[inline(always)]
      pub fn user_type(&mut self, user_type: UserType) -> &mut Self {
        self.user_type = Some(user_type);
        self
      }
                #[inline(always)]
      pub fn location(&mut self, location: String) -> &mut Self {
        self.location = Some(location);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
    self.__remaining_accounts.push(account);
    self
  }
  /// Add additional accounts to the instruction.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[solana_instruction::AccountMeta]) -> &mut Self {
    self.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[allow(clippy::clone_on_copy)]
  pub fn instruction(&self) -> solana_instruction::Instruction {
    let accounts = RegisterUser {
                              registry: self.registry.expect("registry is not set"),
                                        user_account: self.user_account.expect("user_account is not set"),
                                        user_authority: self.user_authority.expect("user_authority is not set"),
                                        system_program: self.system_program.unwrap_or(solana_pubkey::pubkey!("11111111111111111111111111111111")),
                      };
          let args = RegisterUserInstructionArgs {
                                                              user_type: self.user_type.clone().expect("user_type is not set"),
                                                                  location: self.location.clone().expect("location is not set"),
                                    };
    
    accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
  }
}

  /// `register_user` CPI accounts.
  pub struct RegisterUserCpiAccounts<'a, 'b> {
          
                    
              pub registry: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub user_account: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub user_authority: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub system_program: &'b solana_account_info::AccountInfo<'a>,
            }

/// `register_user` CPI instruction.
pub struct RegisterUserCpi<'a, 'b> {
  /// The program to invoke.
  pub __program: &'b solana_account_info::AccountInfo<'a>,
      
              
          pub registry: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub user_account: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub user_authority: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub system_program: &'b solana_account_info::AccountInfo<'a>,
            /// The arguments for the instruction.
    pub __args: RegisterUserInstructionArgs,
  }

impl<'a, 'b> RegisterUserCpi<'a, 'b> {
  pub fn new(
    program: &'b solana_account_info::AccountInfo<'a>,
          accounts: RegisterUserCpiAccounts<'a, 'b>,
              args: RegisterUserInstructionArgs,
      ) -> Self {
    Self {
      __program: program,
              registry: accounts.registry,
              user_account: accounts.user_account,
              user_authority: accounts.user_authority,
              system_program: accounts.system_program,
                    __args: args,
          }
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], &[])
  }
  #[inline(always)]
  pub fn invoke_with_remaining_accounts(&self, remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
  }
  #[inline(always)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed_with_remaining_accounts(
    &self,
    signers_seeds: &[&[&[u8]]],
    remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]
  ) -> solana_program_error::ProgramResult {
    let mut accounts = Vec::with_capacity(4+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new(
            *self.registry.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.user_account.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.user_authority.key,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.system_program.key,
            false
          ));
                      remaining_accounts.iter().for_each(|remaining_account| {
      accounts.push(solana_instruction::AccountMeta {
          pubkey: *remaining_account.0.key,
          is_signer: remaining_account.1,
          is_writable: remaining_account.2,
      })
    });
    let mut data = RegisterUserInstructionData::new().try_to_vec().unwrap();
          let mut args = self.__args.try_to_vec().unwrap();
      data.append(&mut args);
    
    let instruction = solana_instruction::Instruction {
      program_id: crate::REGISTRY_ID,
      accounts,
      data,
    };
    let mut account_infos = Vec::with_capacity(5 + remaining_accounts.len());
    account_infos.push(self.__program.clone());
                  account_infos.push(self.registry.clone());
                        account_infos.push(self.user_account.clone());
                        account_infos.push(self.user_authority.clone());
                        account_infos.push(self.system_program.clone());
              remaining_accounts.iter().for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

    if signers_seeds.is_empty() {
      solana_cpi::invoke(&instruction, &account_infos)
    } else {
      solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
    }
  }
}

/// Instruction builder for `RegisterUser` via CPI.
///
/// ### Accounts:
///
                ///   0. `[writable]` registry
                ///   1. `[writable]` user_account
                      ///   2. `[writable, signer]` user_authority
          ///   3. `[]` system_program
#[derive(Clone, Debug)]
pub struct RegisterUserCpiBuilder<'a, 'b> {
  instruction: Box<RegisterUserCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> RegisterUserCpiBuilder<'a, 'b> {
  pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
    let instruction = Box::new(RegisterUserCpiBuilderInstruction {
      __program: program,
              registry: None,
              user_account: None,
              user_authority: None,
              system_program: None,
                                            user_type: None,
                                location: None,
                    __remaining_accounts: Vec::new(),
    });
    Self { instruction }
  }
      #[inline(always)]
    pub fn registry(&mut self, registry: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.registry = Some(registry);
                    self
    }
      #[inline(always)]
    pub fn user_account(&mut self, user_account: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.user_account = Some(user_account);
                    self
    }
      #[inline(always)]
    pub fn user_authority(&mut self, user_authority: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.user_authority = Some(user_authority);
                    self
    }
      #[inline(always)]
    pub fn system_program(&mut self, system_program: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.system_program = Some(system_program);
                    self
    }
                    #[inline(always)]
      pub fn user_type(&mut self, user_type: UserType) -> &mut Self {
        self.instruction.user_type = Some(user_type);
        self
      }
                #[inline(always)]
      pub fn location(&mut self, location: String) -> &mut Self {
        self.instruction.location = Some(location);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: &'b solana_account_info::AccountInfo<'a>, is_writable: bool, is_signer: bool) -> &mut Self {
    self.instruction.__remaining_accounts.push((account, is_writable, is_signer));
    self
  }
  /// Add additional accounts to the instruction.
  ///
  /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
  /// and a `bool` indicating whether the account is a signer or not.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> &mut Self {
    self.instruction.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed(&[])
  }
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
          let args = RegisterUserInstructionArgs {
                                                              user_type: self.instruction.user_type.clone().expect("user_type is not set"),
                                                                  location: self.instruction.location.clone().expect("location is not set"),
                                    };
        let instruction = RegisterUserCpi {
        __program: self.instruction.__program,
                  
          registry: self.instruction.registry.expect("registry is not set"),
                  
          user_account: self.instruction.user_account.expect("user_account is not set"),
                  
          user_authority: self.instruction.user_authority.expect("user_authority is not set"),
                  
          system_program: self.instruction.system_program.expect("system_program is not set"),
                          __args: args,
            };
    instruction.invoke_signed_with_remaining_accounts(signers_seeds, &self.instruction.__remaining_accounts)
  }
}

#[derive(Clone, Debug)]
struct RegisterUserCpiBuilderInstruction<'a, 'b> {
  __program: &'b solana_account_info::AccountInfo<'a>,
            registry: Option<&'b solana_account_info::AccountInfo<'a>>,
                user_account: Option<&'b solana_account_info::AccountInfo<'a>>,
                user_authority: Option<&'b solana_account_info::AccountInfo<'a>>,
                system_program: Option<&'b solana_account_info::AccountInfo<'a>>,
                        user_type: Option<UserType>,
                location: Option<String>,
        /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
  __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}

