//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use crate::generated::types::UserStatus;
use borsh::BorshSerialize;
use borsh::BorshDeserialize;

pub const UPDATE_USER_STATUS_DISCRIMINATOR: [u8; 8] = [4, 129, 231, 220, 216, 44, 151, 55];

/// Accounts.
#[derive(Debug)]
pub struct UpdateUserStatus {
      
              
          pub registry: solana_pubkey::Pubkey,
          
              
          pub user_account: solana_pubkey::Pubkey,
          
              
          pub authority: solana_pubkey::Pubkey,
      }

impl UpdateUserStatus {
  pub fn instruction(&self, args: UpdateUserStatusInstructionArgs) -> solana_instruction::Instruction {
    self.instruction_with_remaining_accounts(args, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::vec_init_then_push)]
  pub fn instruction_with_remaining_accounts(&self, args: UpdateUserStatusInstructionArgs, remaining_accounts: &[solana_instruction::AccountMeta]) -> solana_instruction::Instruction {
    let mut accounts = Vec::with_capacity(3+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.registry,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.user_account,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.authority,
            true
          ));
                      accounts.extend_from_slice(remaining_accounts);
    let mut data = UpdateUserStatusInstructionData::new().try_to_vec().unwrap();
          let mut args = args.try_to_vec().unwrap();
      data.append(&mut args);
    
    solana_instruction::Instruction {
      program_id: crate::REGISTRY_ID,
      accounts,
      data,
    }
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct UpdateUserStatusInstructionData {
            discriminator: [u8; 8],
            }

impl UpdateUserStatusInstructionData {
  pub fn new() -> Self {
    Self {
                        discriminator: [4, 129, 231, 220, 216, 44, 151, 55],
                                }
  }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
    borsh::to_vec(self)
  }
  }

impl Default for UpdateUserStatusInstructionData {
  fn default() -> Self {
    Self::new()
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct UpdateUserStatusInstructionArgs {
                  pub new_status: UserStatus,
      }

impl UpdateUserStatusInstructionArgs {
  pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
    borsh::to_vec(self)
  }
}


/// Instruction builder for `UpdateUserStatus`.
///
/// ### Accounts:
///
          ///   0. `[]` registry
                ///   1. `[writable]` user_account
                ///   2. `[signer]` authority
#[derive(Clone, Debug, Default)]
pub struct UpdateUserStatusBuilder {
            registry: Option<solana_pubkey::Pubkey>,
                user_account: Option<solana_pubkey::Pubkey>,
                authority: Option<solana_pubkey::Pubkey>,
                        new_status: Option<UserStatus>,
        __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl UpdateUserStatusBuilder {
  pub fn new() -> Self {
    Self::default()
  }
            #[inline(always)]
    pub fn registry(&mut self, registry: solana_pubkey::Pubkey) -> &mut Self {
                        self.registry = Some(registry);
                    self
    }
            #[inline(always)]
    pub fn user_account(&mut self, user_account: solana_pubkey::Pubkey) -> &mut Self {
                        self.user_account = Some(user_account);
                    self
    }
            #[inline(always)]
    pub fn authority(&mut self, authority: solana_pubkey::Pubkey) -> &mut Self {
                        self.authority = Some(authority);
                    self
    }
                    #[inline(always)]
      pub fn new_status(&mut self, new_status: UserStatus) -> &mut Self {
        self.new_status = Some(new_status);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
    self.__remaining_accounts.push(account);
    self
  }
  /// Add additional accounts to the instruction.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[solana_instruction::AccountMeta]) -> &mut Self {
    self.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[allow(clippy::clone_on_copy)]
  pub fn instruction(&self) -> solana_instruction::Instruction {
    let accounts = UpdateUserStatus {
                              registry: self.registry.expect("registry is not set"),
                                        user_account: self.user_account.expect("user_account is not set"),
                                        authority: self.authority.expect("authority is not set"),
                      };
          let args = UpdateUserStatusInstructionArgs {
                                                              new_status: self.new_status.clone().expect("new_status is not set"),
                                    };
    
    accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
  }
}

  /// `update_user_status` CPI accounts.
  pub struct UpdateUserStatusCpiAccounts<'a, 'b> {
          
                    
              pub registry: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub user_account: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub authority: &'b solana_account_info::AccountInfo<'a>,
            }

/// `update_user_status` CPI instruction.
pub struct UpdateUserStatusCpi<'a, 'b> {
  /// The program to invoke.
  pub __program: &'b solana_account_info::AccountInfo<'a>,
      
              
          pub registry: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub user_account: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub authority: &'b solana_account_info::AccountInfo<'a>,
            /// The arguments for the instruction.
    pub __args: UpdateUserStatusInstructionArgs,
  }

impl<'a, 'b> UpdateUserStatusCpi<'a, 'b> {
  pub fn new(
    program: &'b solana_account_info::AccountInfo<'a>,
          accounts: UpdateUserStatusCpiAccounts<'a, 'b>,
              args: UpdateUserStatusInstructionArgs,
      ) -> Self {
    Self {
      __program: program,
              registry: accounts.registry,
              user_account: accounts.user_account,
              authority: accounts.authority,
                    __args: args,
          }
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], &[])
  }
  #[inline(always)]
  pub fn invoke_with_remaining_accounts(&self, remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
  }
  #[inline(always)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed_with_remaining_accounts(
    &self,
    signers_seeds: &[&[&[u8]]],
    remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]
  ) -> solana_program_error::ProgramResult {
    let mut accounts = Vec::with_capacity(3+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.registry.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.user_account.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.authority.key,
            true
          ));
                      remaining_accounts.iter().for_each(|remaining_account| {
      accounts.push(solana_instruction::AccountMeta {
          pubkey: *remaining_account.0.key,
          is_signer: remaining_account.1,
          is_writable: remaining_account.2,
      })
    });
    let mut data = UpdateUserStatusInstructionData::new().try_to_vec().unwrap();
          let mut args = self.__args.try_to_vec().unwrap();
      data.append(&mut args);
    
    let instruction = solana_instruction::Instruction {
      program_id: crate::REGISTRY_ID,
      accounts,
      data,
    };
    let mut account_infos = Vec::with_capacity(4 + remaining_accounts.len());
    account_infos.push(self.__program.clone());
                  account_infos.push(self.registry.clone());
                        account_infos.push(self.user_account.clone());
                        account_infos.push(self.authority.clone());
              remaining_accounts.iter().for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

    if signers_seeds.is_empty() {
      solana_cpi::invoke(&instruction, &account_infos)
    } else {
      solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
    }
  }
}

/// Instruction builder for `UpdateUserStatus` via CPI.
///
/// ### Accounts:
///
          ///   0. `[]` registry
                ///   1. `[writable]` user_account
                ///   2. `[signer]` authority
#[derive(Clone, Debug)]
pub struct UpdateUserStatusCpiBuilder<'a, 'b> {
  instruction: Box<UpdateUserStatusCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> UpdateUserStatusCpiBuilder<'a, 'b> {
  pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
    let instruction = Box::new(UpdateUserStatusCpiBuilderInstruction {
      __program: program,
              registry: None,
              user_account: None,
              authority: None,
                                            new_status: None,
                    __remaining_accounts: Vec::new(),
    });
    Self { instruction }
  }
      #[inline(always)]
    pub fn registry(&mut self, registry: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.registry = Some(registry);
                    self
    }
      #[inline(always)]
    pub fn user_account(&mut self, user_account: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.user_account = Some(user_account);
                    self
    }
      #[inline(always)]
    pub fn authority(&mut self, authority: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.authority = Some(authority);
                    self
    }
                    #[inline(always)]
      pub fn new_status(&mut self, new_status: UserStatus) -> &mut Self {
        self.instruction.new_status = Some(new_status);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: &'b solana_account_info::AccountInfo<'a>, is_writable: bool, is_signer: bool) -> &mut Self {
    self.instruction.__remaining_accounts.push((account, is_writable, is_signer));
    self
  }
  /// Add additional accounts to the instruction.
  ///
  /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
  /// and a `bool` indicating whether the account is a signer or not.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> &mut Self {
    self.instruction.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed(&[])
  }
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
          let args = UpdateUserStatusInstructionArgs {
                                                              new_status: self.instruction.new_status.clone().expect("new_status is not set"),
                                    };
        let instruction = UpdateUserStatusCpi {
        __program: self.instruction.__program,
                  
          registry: self.instruction.registry.expect("registry is not set"),
                  
          user_account: self.instruction.user_account.expect("user_account is not set"),
                  
          authority: self.instruction.authority.expect("authority is not set"),
                          __args: args,
            };
    instruction.invoke_signed_with_remaining_accounts(signers_seeds, &self.instruction.__remaining_accounts)
  }
}

#[derive(Clone, Debug)]
struct UpdateUserStatusCpiBuilderInstruction<'a, 'b> {
  __program: &'b solana_account_info::AccountInfo<'a>,
            registry: Option<&'b solana_account_info::AccountInfo<'a>>,
                user_account: Option<&'b solana_account_info::AccountInfo<'a>>,
                authority: Option<&'b solana_account_info::AccountInfo<'a>>,
                        new_status: Option<UserStatus>,
        /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
  __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}

