//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshSerialize;
use borsh::BorshDeserialize;

pub const UPDATE_METER_READING_DISCRIMINATOR: [u8; 8] = [192, 220, 135, 23, 89, 22, 163, 130];

/// Accounts.
#[derive(Debug)]
pub struct UpdateMeterReading {
      
              
          pub meter_account: solana_pubkey::Pubkey,
          
              
          pub oracle_authority: solana_pubkey::Pubkey,
      }

impl UpdateMeterReading {
  pub fn instruction(&self, args: UpdateMeterReadingInstructionArgs) -> solana_instruction::Instruction {
    self.instruction_with_remaining_accounts(args, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::vec_init_then_push)]
  pub fn instruction_with_remaining_accounts(&self, args: UpdateMeterReadingInstructionArgs, remaining_accounts: &[solana_instruction::AccountMeta]) -> solana_instruction::Instruction {
    let mut accounts = Vec::with_capacity(2+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new(
            self.meter_account,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.oracle_authority,
            true
          ));
                      accounts.extend_from_slice(remaining_accounts);
    let mut data = UpdateMeterReadingInstructionData::new().try_to_vec().unwrap();
          let mut args = args.try_to_vec().unwrap();
      data.append(&mut args);
    
    solana_instruction::Instruction {
      program_id: crate::REGISTRY_ID,
      accounts,
      data,
    }
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct UpdateMeterReadingInstructionData {
            discriminator: [u8; 8],
                        }

impl UpdateMeterReadingInstructionData {
  pub fn new() -> Self {
    Self {
                        discriminator: [192, 220, 135, 23, 89, 22, 163, 130],
                                                            }
  }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
    borsh::to_vec(self)
  }
  }

impl Default for UpdateMeterReadingInstructionData {
  fn default() -> Self {
    Self::new()
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct UpdateMeterReadingInstructionArgs {
                  pub energy_generated: u64,
                pub energy_consumed: u64,
                pub reading_timestamp: i64,
      }

impl UpdateMeterReadingInstructionArgs {
  pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
    borsh::to_vec(self)
  }
}


/// Instruction builder for `UpdateMeterReading`.
///
/// ### Accounts:
///
                ///   0. `[writable]` meter_account
                ///   1. `[signer]` oracle_authority
#[derive(Clone, Debug, Default)]
pub struct UpdateMeterReadingBuilder {
            meter_account: Option<solana_pubkey::Pubkey>,
                oracle_authority: Option<solana_pubkey::Pubkey>,
                        energy_generated: Option<u64>,
                energy_consumed: Option<u64>,
                reading_timestamp: Option<i64>,
        __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl UpdateMeterReadingBuilder {
  pub fn new() -> Self {
    Self::default()
  }
            #[inline(always)]
    pub fn meter_account(&mut self, meter_account: solana_pubkey::Pubkey) -> &mut Self {
                        self.meter_account = Some(meter_account);
                    self
    }
            #[inline(always)]
    pub fn oracle_authority(&mut self, oracle_authority: solana_pubkey::Pubkey) -> &mut Self {
                        self.oracle_authority = Some(oracle_authority);
                    self
    }
                    #[inline(always)]
      pub fn energy_generated(&mut self, energy_generated: u64) -> &mut Self {
        self.energy_generated = Some(energy_generated);
        self
      }
                #[inline(always)]
      pub fn energy_consumed(&mut self, energy_consumed: u64) -> &mut Self {
        self.energy_consumed = Some(energy_consumed);
        self
      }
                #[inline(always)]
      pub fn reading_timestamp(&mut self, reading_timestamp: i64) -> &mut Self {
        self.reading_timestamp = Some(reading_timestamp);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
    self.__remaining_accounts.push(account);
    self
  }
  /// Add additional accounts to the instruction.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[solana_instruction::AccountMeta]) -> &mut Self {
    self.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[allow(clippy::clone_on_copy)]
  pub fn instruction(&self) -> solana_instruction::Instruction {
    let accounts = UpdateMeterReading {
                              meter_account: self.meter_account.expect("meter_account is not set"),
                                        oracle_authority: self.oracle_authority.expect("oracle_authority is not set"),
                      };
          let args = UpdateMeterReadingInstructionArgs {
                                                              energy_generated: self.energy_generated.clone().expect("energy_generated is not set"),
                                                                  energy_consumed: self.energy_consumed.clone().expect("energy_consumed is not set"),
                                                                  reading_timestamp: self.reading_timestamp.clone().expect("reading_timestamp is not set"),
                                    };
    
    accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
  }
}

  /// `update_meter_reading` CPI accounts.
  pub struct UpdateMeterReadingCpiAccounts<'a, 'b> {
          
                    
              pub meter_account: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub oracle_authority: &'b solana_account_info::AccountInfo<'a>,
            }

/// `update_meter_reading` CPI instruction.
pub struct UpdateMeterReadingCpi<'a, 'b> {
  /// The program to invoke.
  pub __program: &'b solana_account_info::AccountInfo<'a>,
      
              
          pub meter_account: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub oracle_authority: &'b solana_account_info::AccountInfo<'a>,
            /// The arguments for the instruction.
    pub __args: UpdateMeterReadingInstructionArgs,
  }

impl<'a, 'b> UpdateMeterReadingCpi<'a, 'b> {
  pub fn new(
    program: &'b solana_account_info::AccountInfo<'a>,
          accounts: UpdateMeterReadingCpiAccounts<'a, 'b>,
              args: UpdateMeterReadingInstructionArgs,
      ) -> Self {
    Self {
      __program: program,
              meter_account: accounts.meter_account,
              oracle_authority: accounts.oracle_authority,
                    __args: args,
          }
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], &[])
  }
  #[inline(always)]
  pub fn invoke_with_remaining_accounts(&self, remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
  }
  #[inline(always)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed_with_remaining_accounts(
    &self,
    signers_seeds: &[&[&[u8]]],
    remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]
  ) -> solana_program_error::ProgramResult {
    let mut accounts = Vec::with_capacity(2+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new(
            *self.meter_account.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.oracle_authority.key,
            true
          ));
                      remaining_accounts.iter().for_each(|remaining_account| {
      accounts.push(solana_instruction::AccountMeta {
          pubkey: *remaining_account.0.key,
          is_signer: remaining_account.1,
          is_writable: remaining_account.2,
      })
    });
    let mut data = UpdateMeterReadingInstructionData::new().try_to_vec().unwrap();
          let mut args = self.__args.try_to_vec().unwrap();
      data.append(&mut args);
    
    let instruction = solana_instruction::Instruction {
      program_id: crate::REGISTRY_ID,
      accounts,
      data,
    };
    let mut account_infos = Vec::with_capacity(3 + remaining_accounts.len());
    account_infos.push(self.__program.clone());
                  account_infos.push(self.meter_account.clone());
                        account_infos.push(self.oracle_authority.clone());
              remaining_accounts.iter().for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

    if signers_seeds.is_empty() {
      solana_cpi::invoke(&instruction, &account_infos)
    } else {
      solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
    }
  }
}

/// Instruction builder for `UpdateMeterReading` via CPI.
///
/// ### Accounts:
///
                ///   0. `[writable]` meter_account
                ///   1. `[signer]` oracle_authority
#[derive(Clone, Debug)]
pub struct UpdateMeterReadingCpiBuilder<'a, 'b> {
  instruction: Box<UpdateMeterReadingCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> UpdateMeterReadingCpiBuilder<'a, 'b> {
  pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
    let instruction = Box::new(UpdateMeterReadingCpiBuilderInstruction {
      __program: program,
              meter_account: None,
              oracle_authority: None,
                                            energy_generated: None,
                                energy_consumed: None,
                                reading_timestamp: None,
                    __remaining_accounts: Vec::new(),
    });
    Self { instruction }
  }
      #[inline(always)]
    pub fn meter_account(&mut self, meter_account: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.meter_account = Some(meter_account);
                    self
    }
      #[inline(always)]
    pub fn oracle_authority(&mut self, oracle_authority: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.oracle_authority = Some(oracle_authority);
                    self
    }
                    #[inline(always)]
      pub fn energy_generated(&mut self, energy_generated: u64) -> &mut Self {
        self.instruction.energy_generated = Some(energy_generated);
        self
      }
                #[inline(always)]
      pub fn energy_consumed(&mut self, energy_consumed: u64) -> &mut Self {
        self.instruction.energy_consumed = Some(energy_consumed);
        self
      }
                #[inline(always)]
      pub fn reading_timestamp(&mut self, reading_timestamp: i64) -> &mut Self {
        self.instruction.reading_timestamp = Some(reading_timestamp);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: &'b solana_account_info::AccountInfo<'a>, is_writable: bool, is_signer: bool) -> &mut Self {
    self.instruction.__remaining_accounts.push((account, is_writable, is_signer));
    self
  }
  /// Add additional accounts to the instruction.
  ///
  /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
  /// and a `bool` indicating whether the account is a signer or not.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> &mut Self {
    self.instruction.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed(&[])
  }
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
          let args = UpdateMeterReadingInstructionArgs {
                                                              energy_generated: self.instruction.energy_generated.clone().expect("energy_generated is not set"),
                                                                  energy_consumed: self.instruction.energy_consumed.clone().expect("energy_consumed is not set"),
                                                                  reading_timestamp: self.instruction.reading_timestamp.clone().expect("reading_timestamp is not set"),
                                    };
        let instruction = UpdateMeterReadingCpi {
        __program: self.instruction.__program,
                  
          meter_account: self.instruction.meter_account.expect("meter_account is not set"),
                  
          oracle_authority: self.instruction.oracle_authority.expect("oracle_authority is not set"),
                          __args: args,
            };
    instruction.invoke_signed_with_remaining_accounts(signers_seeds, &self.instruction.__remaining_accounts)
  }
}

#[derive(Clone, Debug)]
struct UpdateMeterReadingCpiBuilderInstruction<'a, 'b> {
  __program: &'b solana_account_info::AccountInfo<'a>,
            meter_account: Option<&'b solana_account_info::AccountInfo<'a>>,
                oracle_authority: Option<&'b solana_account_info::AccountInfo<'a>>,
                        energy_generated: Option<u64>,
                energy_consumed: Option<u64>,
                reading_timestamp: Option<i64>,
        /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
  __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}

