/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export type BuyOrderCreated = {
  buyer: Address;
  orderId: Address;
  amount: bigint;
  pricePerKwh: bigint;
  timestamp: bigint;
};

export type BuyOrderCreatedArgs = {
  buyer: Address;
  orderId: Address;
  amount: number | bigint;
  pricePerKwh: number | bigint;
  timestamp: number | bigint;
};

export function getBuyOrderCreatedEncoder(): FixedSizeEncoder<BuyOrderCreatedArgs> {
  return getStructEncoder([
    ['buyer', getAddressEncoder()],
    ['orderId', getAddressEncoder()],
    ['amount', getU64Encoder()],
    ['pricePerKwh', getU64Encoder()],
    ['timestamp', getI64Encoder()],
  ]);
}

export function getBuyOrderCreatedDecoder(): FixedSizeDecoder<BuyOrderCreated> {
  return getStructDecoder([
    ['buyer', getAddressDecoder()],
    ['orderId', getAddressDecoder()],
    ['amount', getU64Decoder()],
    ['pricePerKwh', getU64Decoder()],
    ['timestamp', getI64Decoder()],
  ]);
}

export function getBuyOrderCreatedCodec(): FixedSizeCodec<
  BuyOrderCreatedArgs,
  BuyOrderCreated
> {
  return combineCodec(getBuyOrderCreatedEncoder(), getBuyOrderCreatedDecoder());
}
