/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export enum OrderType {
  Sell,
  Buy,
}

export type OrderTypeArgs = OrderType;

export function getOrderTypeEncoder(): FixedSizeEncoder<OrderTypeArgs> {
  return getEnumEncoder(OrderType);
}

export function getOrderTypeDecoder(): FixedSizeDecoder<OrderType> {
  return getEnumDecoder(OrderType);
}

export function getOrderTypeCodec(): FixedSizeCodec<OrderTypeArgs, OrderType> {
  return combineCodec(getOrderTypeEncoder(), getOrderTypeDecoder());
}
