/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export type OrderMatched = {
  sellOrder: Address;
  buyOrder: Address;
  seller: Address;
  buyer: Address;
  amount: bigint;
  price: bigint;
  totalValue: bigint;
  feeAmount: bigint;
  timestamp: bigint;
};

export type OrderMatchedArgs = {
  sellOrder: Address;
  buyOrder: Address;
  seller: Address;
  buyer: Address;
  amount: number | bigint;
  price: number | bigint;
  totalValue: number | bigint;
  feeAmount: number | bigint;
  timestamp: number | bigint;
};

export function getOrderMatchedEncoder(): FixedSizeEncoder<OrderMatchedArgs> {
  return getStructEncoder([
    ['sellOrder', getAddressEncoder()],
    ['buyOrder', getAddressEncoder()],
    ['seller', getAddressEncoder()],
    ['buyer', getAddressEncoder()],
    ['amount', getU64Encoder()],
    ['price', getU64Encoder()],
    ['totalValue', getU64Encoder()],
    ['feeAmount', getU64Encoder()],
    ['timestamp', getI64Encoder()],
  ]);
}

export function getOrderMatchedDecoder(): FixedSizeDecoder<OrderMatched> {
  return getStructDecoder([
    ['sellOrder', getAddressDecoder()],
    ['buyOrder', getAddressDecoder()],
    ['seller', getAddressDecoder()],
    ['buyer', getAddressDecoder()],
    ['amount', getU64Decoder()],
    ['price', getU64Decoder()],
    ['totalValue', getU64Decoder()],
    ['feeAmount', getU64Decoder()],
    ['timestamp', getI64Decoder()],
  ]);
}

export function getOrderMatchedCodec(): FixedSizeCodec<
  OrderMatchedArgs,
  OrderMatched
> {
  return combineCodec(getOrderMatchedEncoder(), getOrderMatchedDecoder());
}
