//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshSerialize;
use borsh::BorshDeserialize;

pub const MINT_GRID_TOKENS_DISCRIMINATOR: [u8; 8] = [216, 110, 76, 206, 212, 49, 238, 59];

/// Accounts.
#[derive(Debug)]
pub struct MintGridTokens {
      
              
          pub token_info: solana_pubkey::Pubkey,
          
              
          pub mint: solana_pubkey::Pubkey,
          
              
          pub meter_account: solana_pubkey::Pubkey,
          
              
          pub user_token_account: solana_pubkey::Pubkey,
          
              
          pub meter_owner: solana_pubkey::Pubkey,
          
              
          pub token_program: solana_pubkey::Pubkey,
          
              
          pub registry_program: solana_pubkey::Pubkey,
          
              
          pub system_program: solana_pubkey::Pubkey,
      }

impl MintGridTokens {
  pub fn instruction(&self) -> solana_instruction::Instruction {
    self.instruction_with_remaining_accounts(&[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::vec_init_then_push)]
  pub fn instruction_with_remaining_accounts(&self, remaining_accounts: &[solana_instruction::AccountMeta]) -> solana_instruction::Instruction {
    let mut accounts = Vec::with_capacity(8+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new(
            self.token_info,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.mint,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.meter_account,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.user_token_account,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.meter_owner,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.token_program,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.registry_program,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.system_program,
            false
          ));
                      accounts.extend_from_slice(remaining_accounts);
    let data = MintGridTokensInstructionData::new().try_to_vec().unwrap();
    
    solana_instruction::Instruction {
      program_id: crate::ENERGY_TOKEN_ID,
      accounts,
      data,
    }
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct MintGridTokensInstructionData {
            discriminator: [u8; 8],
      }

impl MintGridTokensInstructionData {
  pub fn new() -> Self {
    Self {
                        discriminator: [216, 110, 76, 206, 212, 49, 238, 59],
                  }
  }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
    borsh::to_vec(self)
  }
  }

impl Default for MintGridTokensInstructionData {
  fn default() -> Self {
    Self::new()
  }
}



/// Instruction builder for `MintGridTokens`.
///
/// ### Accounts:
///
                ///   0. `[writable]` token_info
                ///   1. `[writable]` mint
                ///   2. `[writable]` meter_account
                ///   3. `[writable]` user_token_account
                ///   4. `[signer]` meter_owner
                ///   5. `[optional]` token_program (default to `TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA`)
          ///   6. `[]` registry_program
                ///   7. `[optional]` system_program (default to `11111111111111111111111111111111`)
#[derive(Clone, Debug, Default)]
pub struct MintGridTokensBuilder {
            token_info: Option<solana_pubkey::Pubkey>,
                mint: Option<solana_pubkey::Pubkey>,
                meter_account: Option<solana_pubkey::Pubkey>,
                user_token_account: Option<solana_pubkey::Pubkey>,
                meter_owner: Option<solana_pubkey::Pubkey>,
                token_program: Option<solana_pubkey::Pubkey>,
                registry_program: Option<solana_pubkey::Pubkey>,
                system_program: Option<solana_pubkey::Pubkey>,
                __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl MintGridTokensBuilder {
  pub fn new() -> Self {
    Self::default()
  }
            #[inline(always)]
    pub fn token_info(&mut self, token_info: solana_pubkey::Pubkey) -> &mut Self {
                        self.token_info = Some(token_info);
                    self
    }
            #[inline(always)]
    pub fn mint(&mut self, mint: solana_pubkey::Pubkey) -> &mut Self {
                        self.mint = Some(mint);
                    self
    }
            #[inline(always)]
    pub fn meter_account(&mut self, meter_account: solana_pubkey::Pubkey) -> &mut Self {
                        self.meter_account = Some(meter_account);
                    self
    }
            #[inline(always)]
    pub fn user_token_account(&mut self, user_token_account: solana_pubkey::Pubkey) -> &mut Self {
                        self.user_token_account = Some(user_token_account);
                    self
    }
            #[inline(always)]
    pub fn meter_owner(&mut self, meter_owner: solana_pubkey::Pubkey) -> &mut Self {
                        self.meter_owner = Some(meter_owner);
                    self
    }
            /// `[optional account, default to 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA']`
#[inline(always)]
    pub fn token_program(&mut self, token_program: solana_pubkey::Pubkey) -> &mut Self {
                        self.token_program = Some(token_program);
                    self
    }
            #[inline(always)]
    pub fn registry_program(&mut self, registry_program: solana_pubkey::Pubkey) -> &mut Self {
                        self.registry_program = Some(registry_program);
                    self
    }
            /// `[optional account, default to '11111111111111111111111111111111']`
#[inline(always)]
    pub fn system_program(&mut self, system_program: solana_pubkey::Pubkey) -> &mut Self {
                        self.system_program = Some(system_program);
                    self
    }
            /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
    self.__remaining_accounts.push(account);
    self
  }
  /// Add additional accounts to the instruction.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[solana_instruction::AccountMeta]) -> &mut Self {
    self.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[allow(clippy::clone_on_copy)]
  pub fn instruction(&self) -> solana_instruction::Instruction {
    let accounts = MintGridTokens {
                              token_info: self.token_info.expect("token_info is not set"),
                                        mint: self.mint.expect("mint is not set"),
                                        meter_account: self.meter_account.expect("meter_account is not set"),
                                        user_token_account: self.user_token_account.expect("user_token_account is not set"),
                                        meter_owner: self.meter_owner.expect("meter_owner is not set"),
                                        token_program: self.token_program.unwrap_or(solana_pubkey::pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA")),
                                        registry_program: self.registry_program.expect("registry_program is not set"),
                                        system_program: self.system_program.unwrap_or(solana_pubkey::pubkey!("11111111111111111111111111111111")),
                      };
    
    accounts.instruction_with_remaining_accounts(&self.__remaining_accounts)
  }
}

  /// `mint_grid_tokens` CPI accounts.
  pub struct MintGridTokensCpiAccounts<'a, 'b> {
          
                    
              pub token_info: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub mint: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub meter_account: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub user_token_account: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub meter_owner: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub token_program: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub registry_program: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub system_program: &'b solana_account_info::AccountInfo<'a>,
            }

/// `mint_grid_tokens` CPI instruction.
pub struct MintGridTokensCpi<'a, 'b> {
  /// The program to invoke.
  pub __program: &'b solana_account_info::AccountInfo<'a>,
      
              
          pub token_info: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub mint: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub meter_account: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub user_token_account: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub meter_owner: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub token_program: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub registry_program: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub system_program: &'b solana_account_info::AccountInfo<'a>,
        }

impl<'a, 'b> MintGridTokensCpi<'a, 'b> {
  pub fn new(
    program: &'b solana_account_info::AccountInfo<'a>,
          accounts: MintGridTokensCpiAccounts<'a, 'b>,
          ) -> Self {
    Self {
      __program: program,
              token_info: accounts.token_info,
              mint: accounts.mint,
              meter_account: accounts.meter_account,
              user_token_account: accounts.user_token_account,
              meter_owner: accounts.meter_owner,
              token_program: accounts.token_program,
              registry_program: accounts.registry_program,
              system_program: accounts.system_program,
                }
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], &[])
  }
  #[inline(always)]
  pub fn invoke_with_remaining_accounts(&self, remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
  }
  #[inline(always)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed_with_remaining_accounts(
    &self,
    signers_seeds: &[&[&[u8]]],
    remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]
  ) -> solana_program_error::ProgramResult {
    let mut accounts = Vec::with_capacity(8+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new(
            *self.token_info.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.mint.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.meter_account.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.user_token_account.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.meter_owner.key,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.token_program.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.registry_program.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.system_program.key,
            false
          ));
                      remaining_accounts.iter().for_each(|remaining_account| {
      accounts.push(solana_instruction::AccountMeta {
          pubkey: *remaining_account.0.key,
          is_signer: remaining_account.1,
          is_writable: remaining_account.2,
      })
    });
    let data = MintGridTokensInstructionData::new().try_to_vec().unwrap();
    
    let instruction = solana_instruction::Instruction {
      program_id: crate::ENERGY_TOKEN_ID,
      accounts,
      data,
    };
    let mut account_infos = Vec::with_capacity(9 + remaining_accounts.len());
    account_infos.push(self.__program.clone());
                  account_infos.push(self.token_info.clone());
                        account_infos.push(self.mint.clone());
                        account_infos.push(self.meter_account.clone());
                        account_infos.push(self.user_token_account.clone());
                        account_infos.push(self.meter_owner.clone());
                        account_infos.push(self.token_program.clone());
                        account_infos.push(self.registry_program.clone());
                        account_infos.push(self.system_program.clone());
              remaining_accounts.iter().for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

    if signers_seeds.is_empty() {
      solana_cpi::invoke(&instruction, &account_infos)
    } else {
      solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
    }
  }
}

/// Instruction builder for `MintGridTokens` via CPI.
///
/// ### Accounts:
///
                ///   0. `[writable]` token_info
                ///   1. `[writable]` mint
                ///   2. `[writable]` meter_account
                ///   3. `[writable]` user_token_account
                ///   4. `[signer]` meter_owner
          ///   5. `[]` token_program
          ///   6. `[]` registry_program
          ///   7. `[]` system_program
#[derive(Clone, Debug)]
pub struct MintGridTokensCpiBuilder<'a, 'b> {
  instruction: Box<MintGridTokensCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> MintGridTokensCpiBuilder<'a, 'b> {
  pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
    let instruction = Box::new(MintGridTokensCpiBuilderInstruction {
      __program: program,
              token_info: None,
              mint: None,
              meter_account: None,
              user_token_account: None,
              meter_owner: None,
              token_program: None,
              registry_program: None,
              system_program: None,
                                __remaining_accounts: Vec::new(),
    });
    Self { instruction }
  }
      #[inline(always)]
    pub fn token_info(&mut self, token_info: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.token_info = Some(token_info);
                    self
    }
      #[inline(always)]
    pub fn mint(&mut self, mint: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.mint = Some(mint);
                    self
    }
      #[inline(always)]
    pub fn meter_account(&mut self, meter_account: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.meter_account = Some(meter_account);
                    self
    }
      #[inline(always)]
    pub fn user_token_account(&mut self, user_token_account: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.user_token_account = Some(user_token_account);
                    self
    }
      #[inline(always)]
    pub fn meter_owner(&mut self, meter_owner: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.meter_owner = Some(meter_owner);
                    self
    }
      #[inline(always)]
    pub fn token_program(&mut self, token_program: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.token_program = Some(token_program);
                    self
    }
      #[inline(always)]
    pub fn registry_program(&mut self, registry_program: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.registry_program = Some(registry_program);
                    self
    }
      #[inline(always)]
    pub fn system_program(&mut self, system_program: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.system_program = Some(system_program);
                    self
    }
            /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: &'b solana_account_info::AccountInfo<'a>, is_writable: bool, is_signer: bool) -> &mut Self {
    self.instruction.__remaining_accounts.push((account, is_writable, is_signer));
    self
  }
  /// Add additional accounts to the instruction.
  ///
  /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
  /// and a `bool` indicating whether the account is a signer or not.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> &mut Self {
    self.instruction.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed(&[])
  }
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        let instruction = MintGridTokensCpi {
        __program: self.instruction.__program,
                  
          token_info: self.instruction.token_info.expect("token_info is not set"),
                  
          mint: self.instruction.mint.expect("mint is not set"),
                  
          meter_account: self.instruction.meter_account.expect("meter_account is not set"),
                  
          user_token_account: self.instruction.user_token_account.expect("user_token_account is not set"),
                  
          meter_owner: self.instruction.meter_owner.expect("meter_owner is not set"),
                  
          token_program: self.instruction.token_program.expect("token_program is not set"),
                  
          registry_program: self.instruction.registry_program.expect("registry_program is not set"),
                  
          system_program: self.instruction.system_program.expect("system_program is not set"),
                    };
    instruction.invoke_signed_with_remaining_accounts(signers_seeds, &self.instruction.__remaining_accounts)
  }
}

#[derive(Clone, Debug)]
struct MintGridTokensCpiBuilderInstruction<'a, 'b> {
  __program: &'b solana_account_info::AccountInfo<'a>,
            token_info: Option<&'b solana_account_info::AccountInfo<'a>>,
                mint: Option<&'b solana_account_info::AccountInfo<'a>>,
                meter_account: Option<&'b solana_account_info::AccountInfo<'a>>,
                user_token_account: Option<&'b solana_account_info::AccountInfo<'a>>,
                meter_owner: Option<&'b solana_account_info::AccountInfo<'a>>,
                token_program: Option<&'b solana_account_info::AccountInfo<'a>>,
                registry_program: Option<&'b solana_account_info::AccountInfo<'a>>,
                system_program: Option<&'b solana_account_info::AccountInfo<'a>>,
                /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
  __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}

