//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use num_derive::FromPrimitive;
use thiserror::Error;

#[derive(Clone, Debug, Eq, Error, FromPrimitive, PartialEq)]
pub enum EnergyTokenError {
    /// 6000 - Unauthorized authority
    #[error("Unauthorized authority")]
    UnauthorizedAuthority = 0x1770,
    /// 6001 - Invalid meter
    #[error("Invalid meter")]
    InvalidMeter = 0x1771,
    /// 6002 - Insufficient token balance
    #[error("Insufficient token balance")]
    InsufficientBalance = 0x1772,
    /// 6003 - Invalid metadata account
    #[error("Invalid metadata account")]
    InvalidMetadataAccount = 0x1773,
}

impl From<EnergyTokenError> for solana_program_error::ProgramError {
    fn from(e: EnergyTokenError) -> Self {
        solana_program_error::ProgramError::Custom(e as u32)
    }
}

