/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  isProgramError,
  type Address,
  type SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM,
  type SolanaError,
} from '@solana/kit';
import { REGISTRY_PROGRAM_ADDRESS } from '../programs';

/** UnauthorizedUser: Unauthorized user */
export const REGISTRY_ERROR__UNAUTHORIZED_USER = 0x1770; // 6000
/** UnauthorizedAuthority: Unauthorized authority */
export const REGISTRY_ERROR__UNAUTHORIZED_AUTHORITY = 0x1771; // 6001
/** InvalidUserStatus: Invalid user status */
export const REGISTRY_ERROR__INVALID_USER_STATUS = 0x1772; // 6002
/** InvalidMeterStatus: Invalid meter status */
export const REGISTRY_ERROR__INVALID_METER_STATUS = 0x1773; // 6003
/** UserNotFound: User not found */
export const REGISTRY_ERROR__USER_NOT_FOUND = 0x1774; // 6004
/** MeterNotFound: Meter not found */
export const REGISTRY_ERROR__METER_NOT_FOUND = 0x1775; // 6005
/** NoUnsettledBalance: No unsettled balance to tokenize */
export const REGISTRY_ERROR__NO_UNSETTLED_BALANCE = 0x1776; // 6006

export type RegistryError =
  | typeof REGISTRY_ERROR__INVALID_METER_STATUS
  | typeof REGISTRY_ERROR__INVALID_USER_STATUS
  | typeof REGISTRY_ERROR__METER_NOT_FOUND
  | typeof REGISTRY_ERROR__NO_UNSETTLED_BALANCE
  | typeof REGISTRY_ERROR__UNAUTHORIZED_AUTHORITY
  | typeof REGISTRY_ERROR__UNAUTHORIZED_USER
  | typeof REGISTRY_ERROR__USER_NOT_FOUND;

let registryErrorMessages: Record<RegistryError, string> | undefined;
if (process.env.NODE_ENV !== 'production') {
  registryErrorMessages = {
    [REGISTRY_ERROR__INVALID_METER_STATUS]: `Invalid meter status`,
    [REGISTRY_ERROR__INVALID_USER_STATUS]: `Invalid user status`,
    [REGISTRY_ERROR__METER_NOT_FOUND]: `Meter not found`,
    [REGISTRY_ERROR__NO_UNSETTLED_BALANCE]: `No unsettled balance to tokenize`,
    [REGISTRY_ERROR__UNAUTHORIZED_AUTHORITY]: `Unauthorized authority`,
    [REGISTRY_ERROR__UNAUTHORIZED_USER]: `Unauthorized user`,
    [REGISTRY_ERROR__USER_NOT_FOUND]: `User not found`,
  };
}

export function getRegistryErrorMessage(code: RegistryError): string {
  if (process.env.NODE_ENV !== 'production') {
    return (registryErrorMessages as Record<RegistryError, string>)[code];
  }

  return 'Error message not available in production bundles.';
}

export function isRegistryError<TProgramErrorCode extends RegistryError>(
  error: unknown,
  transactionMessage: {
    instructions: Record<number, { programAddress: Address }>;
  },
  code?: TProgramErrorCode
): error is SolanaError<typeof SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM> &
  Readonly<{ context: Readonly<{ code: TProgramErrorCode }> }> {
  return isProgramError<TProgramErrorCode>(
    error,
    transactionMessage,
    REGISTRY_PROGRAM_ADDRESS,
    code
  );
}
