/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  containsBytes,
  fixEncoderSize,
  getBytesEncoder,
  type Address,
  type ReadonlyUint8Array,
} from '@solana/kit';
import {
  type ParsedGetUnsettledBalanceInstruction,
  type ParsedInitializeInstruction,
  type ParsedIsValidMeterInstruction,
  type ParsedIsValidUserInstruction,
  type ParsedRegisterMeterInstruction,
  type ParsedRegisterUserInstruction,
  type ParsedSettleMeterBalanceInstruction,
  type ParsedUpdateMeterReadingInstruction,
  type ParsedUpdateUserStatusInstruction,
} from '../instructions';

export const REGISTRY_PROGRAM_ADDRESS =
  '2XPQmFYMdXjP7ffoBB3mXeCdboSFg5Yeb6QmTSGbW8a7' as Address<'2XPQmFYMdXjP7ffoBB3mXeCdboSFg5Yeb6QmTSGbW8a7'>;

export enum RegistryAccount {
  MeterAccount,
  Registry,
  UserAccount,
}

export function identifyRegistryAccount(
  account: { data: ReadonlyUint8Array } | ReadonlyUint8Array
): RegistryAccount {
  const data = 'data' in account ? account.data : account;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([87, 111, 139, 87, 181, 20, 104, 255])
      ),
      0
    )
  ) {
    return RegistryAccount.MeterAccount;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([47, 174, 110, 246, 184, 182, 252, 218])
      ),
      0
    )
  ) {
    return RegistryAccount.Registry;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([211, 33, 136, 16, 186, 110, 242, 127])
      ),
      0
    )
  ) {
    return RegistryAccount.UserAccount;
  }
  throw new Error(
    'The provided account could not be identified as a registry account.'
  );
}

export enum RegistryInstruction {
  GetUnsettledBalance,
  Initialize,
  IsValidMeter,
  IsValidUser,
  RegisterMeter,
  RegisterUser,
  SettleMeterBalance,
  UpdateMeterReading,
  UpdateUserStatus,
}

export function identifyRegistryInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array
): RegistryInstruction {
  const data = 'data' in instruction ? instruction.data : instruction;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([178, 120, 95, 9, 18, 81, 181, 83])
      ),
      0
    )
  ) {
    return RegistryInstruction.GetUnsettledBalance;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([175, 175, 109, 31, 13, 152, 155, 237])
      ),
      0
    )
  ) {
    return RegistryInstruction.Initialize;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([151, 114, 52, 252, 238, 233, 81, 91])
      ),
      0
    )
  ) {
    return RegistryInstruction.IsValidMeter;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([204, 118, 77, 53, 39, 63, 237, 250])
      ),
      0
    )
  ) {
    return RegistryInstruction.IsValidUser;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([49, 106, 87, 72, 138, 214, 224, 125])
      ),
      0
    )
  ) {
    return RegistryInstruction.RegisterMeter;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([2, 241, 150, 223, 99, 214, 116, 97])
      ),
      0
    )
  ) {
    return RegistryInstruction.RegisterUser;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([178, 46, 241, 202, 53, 99, 79, 119])
      ),
      0
    )
  ) {
    return RegistryInstruction.SettleMeterBalance;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([192, 220, 135, 23, 89, 22, 163, 130])
      ),
      0
    )
  ) {
    return RegistryInstruction.UpdateMeterReading;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([4, 129, 231, 220, 216, 44, 151, 55])
      ),
      0
    )
  ) {
    return RegistryInstruction.UpdateUserStatus;
  }
  throw new Error(
    'The provided instruction could not be identified as a registry instruction.'
  );
}

export type ParsedRegistryInstruction<
  TProgram extends string = '2XPQmFYMdXjP7ffoBB3mXeCdboSFg5Yeb6QmTSGbW8a7',
> =
  | ({
      instructionType: RegistryInstruction.GetUnsettledBalance;
    } & ParsedGetUnsettledBalanceInstruction<TProgram>)
  | ({
      instructionType: RegistryInstruction.Initialize;
    } & ParsedInitializeInstruction<TProgram>)
  | ({
      instructionType: RegistryInstruction.IsValidMeter;
    } & ParsedIsValidMeterInstruction<TProgram>)
  | ({
      instructionType: RegistryInstruction.IsValidUser;
    } & ParsedIsValidUserInstruction<TProgram>)
  | ({
      instructionType: RegistryInstruction.RegisterMeter;
    } & ParsedRegisterMeterInstruction<TProgram>)
  | ({
      instructionType: RegistryInstruction.RegisterUser;
    } & ParsedRegisterUserInstruction<TProgram>)
  | ({
      instructionType: RegistryInstruction.SettleMeterBalance;
    } & ParsedSettleMeterBalanceInstruction<TProgram>)
  | ({
      instructionType: RegistryInstruction.UpdateMeterReading;
    } & ParsedUpdateMeterReadingInstruction<TProgram>)
  | ({
      instructionType: RegistryInstruction.UpdateUserStatus;
    } & ParsedUpdateUserStatusInstruction<TProgram>);
