/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getUtf8Decoder,
  getUtf8Encoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';

export type AuthorityInfoUpdated = {
  authority: Address;
  oldContact: string;
  newContact: string;
  timestamp: bigint;
};

export type AuthorityInfoUpdatedArgs = {
  authority: Address;
  oldContact: string;
  newContact: string;
  timestamp: number | bigint;
};

export function getAuthorityInfoUpdatedEncoder(): Encoder<AuthorityInfoUpdatedArgs> {
  return getStructEncoder([
    ['authority', getAddressEncoder()],
    ['oldContact', addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
    ['newContact', addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
    ['timestamp', getI64Encoder()],
  ]);
}

export function getAuthorityInfoUpdatedDecoder(): Decoder<AuthorityInfoUpdated> {
  return getStructDecoder([
    ['authority', getAddressDecoder()],
    ['oldContact', addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
    ['newContact', addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
    ['timestamp', getI64Decoder()],
  ]);
}

export function getAuthorityInfoUpdatedCodec(): Codec<
  AuthorityInfoUpdatedArgs,
  AuthorityInfoUpdated
> {
  return combineCodec(
    getAuthorityInfoUpdatedEncoder(),
    getAuthorityInfoUpdatedDecoder()
  );
}
