/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export enum ErcStatus {
  Valid,
  Expired,
  Revoked,
  Pending,
}

export type ErcStatusArgs = ErcStatus;

export function getErcStatusEncoder(): FixedSizeEncoder<ErcStatusArgs> {
  return getEnumEncoder(ErcStatus);
}

export function getErcStatusDecoder(): FixedSizeDecoder<ErcStatus> {
  return getEnumDecoder(ErcStatus);
}

export function getErcStatusCodec(): FixedSizeCodec<ErcStatusArgs, ErcStatus> {
  return combineCodec(getErcStatusEncoder(), getErcStatusDecoder());
}
