/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getBooleanDecoder,
  getBooleanEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export type GovernanceConfigUpdated = {
  authority: Address;
  ercValidationEnabled: boolean;
  oldEnabled: boolean;
  timestamp: bigint;
};

export type GovernanceConfigUpdatedArgs = {
  authority: Address;
  ercValidationEnabled: boolean;
  oldEnabled: boolean;
  timestamp: number | bigint;
};

export function getGovernanceConfigUpdatedEncoder(): FixedSizeEncoder<GovernanceConfigUpdatedArgs> {
  return getStructEncoder([
    ['authority', getAddressEncoder()],
    ['ercValidationEnabled', getBooleanEncoder()],
    ['oldEnabled', getBooleanEncoder()],
    ['timestamp', getI64Encoder()],
  ]);
}

export function getGovernanceConfigUpdatedDecoder(): FixedSizeDecoder<GovernanceConfigUpdated> {
  return getStructDecoder([
    ['authority', getAddressDecoder()],
    ['ercValidationEnabled', getBooleanDecoder()],
    ['oldEnabled', getBooleanDecoder()],
    ['timestamp', getI64Decoder()],
  ]);
}

export function getGovernanceConfigUpdatedCodec(): FixedSizeCodec<
  GovernanceConfigUpdatedArgs,
  GovernanceConfigUpdated
> {
  return combineCodec(
    getGovernanceConfigUpdatedEncoder(),
    getGovernanceConfigUpdatedDecoder()
  );
}
