/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getUtf8Decoder,
  getUtf8Encoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';

export type PoAInitialized = {
  authority: Address;
  authorityName: string;
  timestamp: bigint;
};

export type PoAInitializedArgs = {
  authority: Address;
  authorityName: string;
  timestamp: number | bigint;
};

export function getPoAInitializedEncoder(): Encoder<PoAInitializedArgs> {
  return getStructEncoder([
    ['authority', getAddressEncoder()],
    ['authorityName', addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
    ['timestamp', getI64Encoder()],
  ]);
}

export function getPoAInitializedDecoder(): Decoder<PoAInitialized> {
  return getStructDecoder([
    ['authority', getAddressDecoder()],
    ['authorityName', addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
    ['timestamp', getI64Decoder()],
  ]);
}

export function getPoAInitializedCodec(): Codec<
  PoAInitializedArgs,
  PoAInitialized
> {
  return combineCodec(getPoAInitializedEncoder(), getPoAInitializedDecoder());
}
