/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export enum MeterType {
  Solar,
  Wind,
  Battery,
  Grid,
}

export type MeterTypeArgs = MeterType;

export function getMeterTypeEncoder(): FixedSizeEncoder<MeterTypeArgs> {
  return getEnumEncoder(MeterType);
}

export function getMeterTypeDecoder(): FixedSizeDecoder<MeterType> {
  return getEnumDecoder(MeterType);
}

export function getMeterTypeCodec(): FixedSizeCodec<MeterTypeArgs, MeterType> {
  return combineCodec(getMeterTypeEncoder(), getMeterTypeDecoder());
}
