/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU64Decoder,
  getU64Encoder,
  getUtf8Decoder,
  getUtf8Encoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';

export type MeterBalanceSettled = {
  meterId: string;
  owner: Address;
  tokensToMint: bigint;
  totalSettled: bigint;
  timestamp: bigint;
};

export type MeterBalanceSettledArgs = {
  meterId: string;
  owner: Address;
  tokensToMint: number | bigint;
  totalSettled: number | bigint;
  timestamp: number | bigint;
};

export function getMeterBalanceSettledEncoder(): Encoder<MeterBalanceSettledArgs> {
  return getStructEncoder([
    ['meterId', addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
    ['owner', getAddressEncoder()],
    ['tokensToMint', getU64Encoder()],
    ['totalSettled', getU64Encoder()],
    ['timestamp', getI64Encoder()],
  ]);
}

export function getMeterBalanceSettledDecoder(): Decoder<MeterBalanceSettled> {
  return getStructDecoder([
    ['meterId', addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
    ['owner', getAddressDecoder()],
    ['tokensToMint', getU64Decoder()],
    ['totalSettled', getU64Decoder()],
    ['timestamp', getI64Decoder()],
  ]);
}

export function getMeterBalanceSettledCodec(): Codec<
  MeterBalanceSettledArgs,
  MeterBalanceSettled
> {
  return combineCodec(
    getMeterBalanceSettledEncoder(),
    getMeterBalanceSettledDecoder()
  );
}
