/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU64Decoder,
  getU64Encoder,
  getUtf8Decoder,
  getUtf8Encoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';

export type MeterReadingUpdated = {
  meterId: string;
  owner: Address;
  energyGenerated: bigint;
  energyConsumed: bigint;
  timestamp: bigint;
};

export type MeterReadingUpdatedArgs = {
  meterId: string;
  owner: Address;
  energyGenerated: number | bigint;
  energyConsumed: number | bigint;
  timestamp: number | bigint;
};

export function getMeterReadingUpdatedEncoder(): Encoder<MeterReadingUpdatedArgs> {
  return getStructEncoder([
    ['meterId', addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
    ['owner', getAddressEncoder()],
    ['energyGenerated', getU64Encoder()],
    ['energyConsumed', getU64Encoder()],
    ['timestamp', getI64Encoder()],
  ]);
}

export function getMeterReadingUpdatedDecoder(): Decoder<MeterReadingUpdated> {
  return getStructDecoder([
    ['meterId', addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
    ['owner', getAddressDecoder()],
    ['energyGenerated', getU64Decoder()],
    ['energyConsumed', getU64Decoder()],
    ['timestamp', getI64Decoder()],
  ]);
}

export function getMeterReadingUpdatedCodec(): Codec<
  MeterReadingUpdatedArgs,
  MeterReadingUpdated
> {
  return combineCodec(
    getMeterReadingUpdatedEncoder(),
    getMeterReadingUpdatedDecoder()
  );
}
