/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export type RegistryInitialized = { authority: Address; timestamp: bigint };

export type RegistryInitializedArgs = {
  authority: Address;
  timestamp: number | bigint;
};

export function getRegistryInitializedEncoder(): FixedSizeEncoder<RegistryInitializedArgs> {
  return getStructEncoder([
    ['authority', getAddressEncoder()],
    ['timestamp', getI64Encoder()],
  ]);
}

export function getRegistryInitializedDecoder(): FixedSizeDecoder<RegistryInitialized> {
  return getStructDecoder([
    ['authority', getAddressDecoder()],
    ['timestamp', getI64Decoder()],
  ]);
}

export function getRegistryInitializedCodec(): FixedSizeCodec<
  RegistryInitializedArgs,
  RegistryInitialized
> {
  return combineCodec(
    getRegistryInitializedEncoder(),
    getRegistryInitializedDecoder()
  );
}
