/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export enum UserStatus {
  Active,
  Suspended,
  Inactive,
}

export type UserStatusArgs = UserStatus;

export function getUserStatusEncoder(): FixedSizeEncoder<UserStatusArgs> {
  return getEnumEncoder(UserStatus);
}

export function getUserStatusDecoder(): FixedSizeDecoder<UserStatus> {
  return getEnumDecoder(UserStatus);
}

export function getUserStatusCodec(): FixedSizeCodec<
  UserStatusArgs,
  UserStatus
> {
  return combineCodec(getUserStatusEncoder(), getUserStatusDecoder());
}
