/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';
import {
  getUserStatusDecoder,
  getUserStatusEncoder,
  type UserStatus,
  type UserStatusArgs,
} from '.';

export type UserStatusUpdated = {
  user: Address;
  oldStatus: UserStatus;
  newStatus: UserStatus;
  timestamp: bigint;
};

export type UserStatusUpdatedArgs = {
  user: Address;
  oldStatus: UserStatusArgs;
  newStatus: UserStatusArgs;
  timestamp: number | bigint;
};

export function getUserStatusUpdatedEncoder(): FixedSizeEncoder<UserStatusUpdatedArgs> {
  return getStructEncoder([
    ['user', getAddressEncoder()],
    ['oldStatus', getUserStatusEncoder()],
    ['newStatus', getUserStatusEncoder()],
    ['timestamp', getI64Encoder()],
  ]);
}

export function getUserStatusUpdatedDecoder(): FixedSizeDecoder<UserStatusUpdated> {
  return getStructDecoder([
    ['user', getAddressDecoder()],
    ['oldStatus', getUserStatusDecoder()],
    ['newStatus', getUserStatusDecoder()],
    ['timestamp', getI64Decoder()],
  ]);
}

export function getUserStatusUpdatedCodec(): FixedSizeCodec<
  UserStatusUpdatedArgs,
  UserStatusUpdated
> {
  return combineCodec(
    getUserStatusUpdatedEncoder(),
    getUserStatusUpdatedDecoder()
  );
}
