//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use solana_pubkey::Pubkey;
use borsh::BorshSerialize;
use borsh::BorshDeserialize;


#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct PoAConfig {
pub discriminator: [u8; 8],
/// Single authority - REC certifying entity
#[cfg_attr(feature = "serde", serde(with = "serde_with::As::<serde_with::DisplayFromStr>"))]
pub authority: Pubkey,
/// Authority name (e.g., "REC")
pub authority_name: String,
/// Authority contact information
pub contact_info: String,
/// Governance version for upgrades
pub version: u8,
/// Emergency pause status
pub emergency_paused: bool,
/// Emergency pause timestamp
pub emergency_timestamp: Option<i64>,
/// Emergency pause reason
pub emergency_reason: Option<String>,
/// System maintenance mode
pub maintenance_mode: bool,
/// Whether ERC validation is enabled
pub erc_validation_enabled: bool,
/// Minimum energy amount for ERC issuance (kWh)
pub min_energy_amount: u64,
/// Maximum ERC amount per certificate (kWh)
pub max_erc_amount: u64,
/// ERC certificate validity period (seconds)
pub erc_validity_period: i64,
/// Auto-revoke expired certificates
pub auto_revoke_expired: bool,
/// Require oracle validation for ERC issuance
pub require_oracle_validation: bool,
/// Whether the authority can delegate ERC validation
pub delegation_enabled: bool,
/// Oracle authority for AMI data validation
pub oracle_authority: Option<Pubkey>,
/// Minimum confidence score for oracle validation (0-100)
pub min_oracle_confidence: u8,
/// Allow certificate transfers between accounts
pub allow_certificate_transfers: bool,
/// Total ERCs issued since inception
pub total_ercs_issued: u64,
/// Total ERCs validated for trading
pub total_ercs_validated: u64,
/// Total ERCs revoked
pub total_ercs_revoked: u64,
/// Total energy certified (kWh)
pub total_energy_certified: u64,
/// When governance was initialized
pub created_at: i64,
/// Last configuration update
pub last_updated: i64,
/// Last ERC issued timestamp
pub last_erc_issued_at: Option<i64>,
}


pub const PO_A_CONFIG_DISCRIMINATOR: [u8; 8] = [119, 6, 28, 138, 199, 43, 5, 184];

impl PoAConfig {
  
  
  
  #[inline(always)]
  pub fn from_bytes(data: &[u8]) -> Result<Self, std::io::Error> {
    let mut data = data;
    Self::deserialize(&mut data)
  }
}

impl<'a> TryFrom<&solana_account_info::AccountInfo<'a>> for PoAConfig {
  type Error = std::io::Error;

  fn try_from(account_info: &solana_account_info::AccountInfo<'a>) -> Result<Self, Self::Error> {
      let mut data: &[u8] = &(*account_info.data).borrow();
      Self::deserialize(&mut data)
  }
}

#[cfg(feature = "fetch")]
pub fn fetch_po_a_config(
  rpc: &solana_client::rpc_client::RpcClient,
  address: &solana_pubkey::Pubkey,
) -> Result<crate::shared::DecodedAccount<PoAConfig>, std::io::Error> {
  let accounts = fetch_all_po_a_config(rpc, &[*address])?;
  Ok(accounts[0].clone())
}

#[cfg(feature = "fetch")]
pub fn fetch_all_po_a_config(
  rpc: &solana_client::rpc_client::RpcClient,
  addresses: &[solana_pubkey::Pubkey],
) -> Result<Vec<crate::shared::DecodedAccount<PoAConfig>>, std::io::Error> {
    let accounts = rpc.get_multiple_accounts(addresses)
      .map_err(|e| std::io::Error::new(std::io::ErrorKind::Other, e.to_string()))?;
    let mut decoded_accounts: Vec<crate::shared::DecodedAccount<PoAConfig>> = Vec::new();
    for i in 0..addresses.len() {
      let address = addresses[i];
      let account = accounts[i].as_ref()
        .ok_or(std::io::Error::new(std::io::ErrorKind::Other, format!("Account not found: {}", address)))?;
      let data = PoAConfig::from_bytes(&account.data)?;
      decoded_accounts.push(crate::shared::DecodedAccount { address, account: account.clone(), data });
    }
    Ok(decoded_accounts)
}

#[cfg(feature = "fetch")]
pub fn fetch_maybe_po_a_config(
  rpc: &solana_client::rpc_client::RpcClient,
  address: &solana_pubkey::Pubkey,
) -> Result<crate::shared::MaybeAccount<PoAConfig>, std::io::Error> {
    let accounts = fetch_all_maybe_po_a_config(rpc, &[*address])?;
    Ok(accounts[0].clone())
}

#[cfg(feature = "fetch")]
pub fn fetch_all_maybe_po_a_config(
  rpc: &solana_client::rpc_client::RpcClient,
  addresses: &[solana_pubkey::Pubkey],
) -> Result<Vec<crate::shared::MaybeAccount<PoAConfig>>, std::io::Error> {
    let accounts = rpc.get_multiple_accounts(addresses)
      .map_err(|e| std::io::Error::new(std::io::ErrorKind::Other, e.to_string()))?;
    let mut decoded_accounts: Vec<crate::shared::MaybeAccount<PoAConfig>> = Vec::new();
    for i in 0..addresses.len() {
      let address = addresses[i];
      if let Some(account) = accounts[i].as_ref() {
        let data = PoAConfig::from_bytes(&account.data)?;
        decoded_accounts.push(crate::shared::MaybeAccount::Exists(crate::shared::DecodedAccount { address, account: account.clone(), data }));
      } else {
        decoded_accounts.push(crate::shared::MaybeAccount::NotFound(address));
      }
    }
  Ok(decoded_accounts)
}

  #[cfg(feature = "anchor")]
  impl anchor_lang::AccountDeserialize for PoAConfig {
      fn try_deserialize_unchecked(buf: &mut &[u8]) -> anchor_lang::Result<Self> {
        Ok(Self::deserialize(buf)?)
      }
  }

  #[cfg(feature = "anchor")]
  impl anchor_lang::AccountSerialize for PoAConfig {}

  #[cfg(feature = "anchor")]
  impl anchor_lang::Owner for PoAConfig {
      fn owner() -> Pubkey {
        crate::GOVERNANCE_ID
      }
  }

  #[cfg(feature = "anchor-idl-build")]
  impl anchor_lang::IdlBuild for PoAConfig {}

  
  #[cfg(feature = "anchor-idl-build")]
  impl anchor_lang::Discriminator for PoAConfig {
    const DISCRIMINATOR: &[u8] = &[0; 8];
  }

